from django.db.models import TextChoices
from .skills import SkillName


class Background(TextChoices):
    ACOLYTE = "acolyte", "Acolyte"
    CRIMINAL = "criminal", "Criminal"
    FOLK_HERO = "folk_hero", "Folk Hero"
    NOBLE = "noble", "Noble"
    SAGE = "sage", "Sage"
    SOLDIER = "soldier", "Soldier"


BACKGROUNDS: dict = {
    Background.ACOLYTE: {
        "skill_proficiencies": {SkillName.INSIGHT, SkillName.RELIGION},
        "tool_proficiencies": {},
        "languages": {},
        "equipment": {},
        "personality_traits": {
            1: "I idolize a particular hero of my faith, and constantly refer to that person's deeds and example.",
            2: "I can find common ground between the fiercest enemies, empathizing with them and always working toward peace.",
            3: "I see omens in every event and action. The gods try to speak to us, we just need to listen.",
            4: "Nothing can shake my optimistic attitude.",
            5: "I quote (or misquote) sacred texts and proverbs in almost every situation.",
            6: "I am tolerant (or intolerant) of other faiths and respect (or condemn) the worship of other gods.",
            7: "I've enjoyed fine food, drink, and high society among my temple's elite. Rough living grates on me.",
            8: "I've spent so long in the temple that I have little practical experience dealing with people in the outside world.",
        },
        "ideals": {
            1: "Tradition. The ancient traditions of worship and sacrifice must be preserved and upheld. (Lawful)",
            2: "Charity. I always try to help those in need, no matter what the personal cost. (Good)",
            3: "Change. We must help bring about the changes the gods are constantly working in the world. (Chaotic)",
            4: "Power. I hope to one day rise to the top of my faith's religious hierarchy. (Lawful)",
            5: "Faith. I trust that my deity will guide my actions. I have faith that if I work hard, things will go well. (Lawful)",
            6: "Aspiration. I seek to prove myself worthy of my god's favor by matching my actions against his or her teachings. (Any)",
        },
        "bonds": {
            1: "I would die to recover an ancient relic of my faith that was lost long ago.",
            2: "I will someday get revenge on the corrupt temple hierarchy who branded me a heretic.",
            3: "I owe my life to the priest who took me in when my parents died.",
            4: "Everything I do is for the common people.",
            5: "I will do anything to protect the temple where I served.",
            6: "I seek to preserve a sacred text that my enemies consider heretical and seek to destroy.",
        },
        "flaws": {
            1: "I judge others harshly, and myself even more severely.",
            2: "I put too much trust in those who wield power within my temple's hierarchy.",
            3: "My piety sometimes leads me to blindly trust those that profess faith in my god.",
            4: "I am inflexible in my thinking.",
            5: "I am suspicious of strangers and expect the worst of them.",
            6: "Once I pick a goal, I become obsessed with it to the detriment of everything else in my life.",
        },
    },
    Background.CRIMINAL: {
        "skill_proficiencies": {SkillName.DECEPTION, SkillName.STEALTH},
        "tool_proficiencies": {},
        "languages": {},
        "equipment": {},
        "personality_traits": {
            1: "I always have a plan for what to do when things go wrong.",
            2: "I am always calm, no matter what the situation. I never raise my voice or let my emotions control me.",
            3: "The first thing I do in a new place is note the locations of everything valuable — or where such things could be hidden.",
            4: "I would rather make a new friend than a new enemy.",
            5: "I am incredibly slow to trust. Those who seem the fairest often have the most to hide.",
            6: "I don't pay attention to the risks in a situation. Never tell me the odds.",
            7: "The best way to get me to do something is to tell me I can't do it.",
            8: "I blow up at the slightest insult.",
        },
        "ideals": {
            1: "Honor. I don't steal from others in the trade. (Lawful)",
            2: "Freedom. Chains are meant to be broken, as are those who would forge them. (Chaotic)",
            3: "Charity. I steal from the wealthy so that I can help people in need. (Good)",
            4: "Greed. I will do whatever it takes to become wealthy. (Evil)",
            5: "People. I'm loyal to my friends, not to any ideals, and everyone else can take a trip down the Styx for all I care. (Neutral)",
            6: "Redemption. There’s a spark of good in everyone. (Good)",
        },
        "bonds": {
            1: "I'm trying to pay off an old debt I owe to a generous benefactor.",
            2: "My ill-gotten gains go to support my family.",
            3: "Something important was taken from me, and I aim to steal it back.",
            4: "I will become the greatest thief that ever lived.",
            5: "I'm guilty of a terrible crime. I hope I can redeem myself for it.",
            6: "Someone I loved died because of I mistake I made. That will never happen again.",
        },
        "flaws": {
            1: "When I see something valuable, I can't think about anything but how to steal it.",
            2: "When faced with a choice between money and my friends, I usually choose the money.",
            3: "If there's a plan, I'll forget it. If I don't forget it, I'll ignore it.",
            4: "I have a 'tell' that reveals when I'm lying.",
            5: "I turn tail and run when things look bad.",
            6: "An innocent person is in prison for a crime that I committed. I'm okay with that.",
        },
    },
    Background.FOLK_HERO: {
        "skill_proficiencies": {SkillName.ANIMAL_HANDLING, SkillName.SURVIVAL},
        "tool_proficiencies": {},
        "languages": {},
        "equipment": {},
        "personality_traits": {
            1: "I judge people by their actions, not their words.",
            2: "If someone is in trouble, I'm always ready to lend help.",
            3: "When I set my mind to something, I follow through no matter what gets in my way.",
            4: "I have a strong sense of fair play and always try to find the most equitable solution to arguments.",
            6: "Thinking is for other people. I prefer action.",
            7: "I misuse long words in an attempt to sound smarter.",
            8: "I get bored easily. When am I going to get on with my destiny?",
        },
        "ideals": {
            1: "Respect. People deserve to be treated with dignity and respect. (Good)",
            2: "Fairness. No one should get preferential treatment before the law, and no one is above the law. (Lawful)",
            3: "Freedom. Tyrants must not be allowed to oppress the people. (Chaotic)",
            4: "Might. If I become strong, I can take what I want—what I deserve. (Evil)",
            5: "Sincerity. There's no good in pretending to be something I'm not. (Neutral)",
            6: "Destiny. Nothing and no one can steer me away from my higher calling. (Any)",
        },
        "bonds": {
            1: "I have a family, but I have no idea where they are. One day, I hope to see them again.",
            2: "I worked the land, I love the land, and I will protect the land.",
            3: "A proud noble once gave me a horrible beating, and I will take my revenge on any bully I encounter.",
            4: "My tools are symbols of my past life, and I carry them so that I will never forget my roots.",
            5: "I protect those who cannot protect themselves.",
            6: "I wish my childhood sweetheart had come with me to pursue my destiny.",
        },
        "flaws": {
            1: "The tyrant who rules my land will stop at nothing to see me killed.",
            2: "I'm convinced of the significance of my destiny, and blind to my shortcomings and the risk of failure.",
            3: "The people who knew me when I was young know my shameful secret, so I can never go home again.",
            4: "I have a weakness for the vices of the city, especially hard drink.",
            5: "Secretly, I believe that things would be better if I were a tyrant lording over the land.",
            6: "I have trouble trusting in my allies.",
        },
    },
    Background.NOBLE: {
        "skill_proficiencies": {SkillName.HISTORY, SkillName.PERSUASION},
        "tool_proficiencies": {},
        "languages": {},
        "equipment": {},
        "personality_traits": {
            1: "My eloquent flattery makes everyone I talk to feel like the most wonderful and important person in the world.",
            2: "The common folk love me for my kindness and generosity.",
            3: "No one could doubt by looking at my regal bearing that I am a cut above the unwashed masses.",
            4: "I take great pains to always look my best and follow the latest fashions.",
            5: "I don't like to get my hands dirty, and I won't be caught dead in unsuitable accommodations.",
            6: "Despite my noble birth, I do not place myself above other folk. We all have the same blood.",
            7: "My favor, once lost, is lost forever.",
            8: "If you do me an injury, I will crush you, ruin your name, and salt your fields.",
        },
        "ideals": {
            1: "Respect. Respect is due to me because of my position, but all people regardless of station deserve to be treated with dignity. (Good)",
            2: "Responsibility. It is my duty to respect the authority of those above me, just as those below me must respect mine. (Lawful)",
            3: "Independence. I must prove that I can handle myself without the coddling of my family. (Chaotic)",
            4: "Power. If I can attain more power, no one will tell me what to do. (Evil)",
            5: "Family. Blood runs thicker than water. (Any)",
            6: "Noble Obligation. It is my duty to protect and care for the people beneath me. (Good)",
        },
        "bonds": {
            1: "I will face any challenge to win the approval of my family.",
            2: "My house's alliance with another noble family must be sustained at all costs.",
            3: "Nothing is more important than the other members of my family.",
            4: "I am in love with the heir of a family that my family despises.",
            5: "My loyalty to my sovereign is unwavering.",
            6: "The common folk must see me as a hero of the people.",
        },
        "flaws": {
            1: "I secretly believe that everyone is beneath me.",
            2: "I hide a truly scandalous secret that could ruin my family forever.",
            3: "I too often hear veiled insults and threats in every word addressed to me, and I'm quick to anger.",
            4: "I have an insatiable desire for carnal pleasures.",
            5: "In fact, the world does revolve around me.",
            6: "By my words and actions, I often bring shame to my family.",
        },
    },
    Background.SAGE: {
        "skill_proficiencies": {SkillName.ARCANA, SkillName.HISTORY},
        "tool_proficiencies": {},
        "languages": {},
        "equipment": {},
        "personality_traits": {
            1: "I use polysyllabic words that convey the impression of great erudition.",
            2: "I've read every book in the world's greatest libraries—or I like to boast that I have.",
            3: "I'm used to helping out those who aren't as smart as I am, and I patiently explain anything and everything to others.",
            4: "There's nothing I like more than a good mystery.",
            5: "I'm willing to listen to every side of an argument before I make my own judgment.",
            6: "I . . . speak . . . slowly . . . when talking . . . to idiots, . . . which . . . almost . . . everyone . . . is . . . compared . . . to me.",
            7: "I am horribly, horribly awkward in social situations.",
            8: "I'm convinced that people are always trying to steal my secrets.",
        },
        "ideals": {
            1: "Knowledge. The path to power and self-improvement is through knowledge. (Neutral)",
            2: "Beauty. What is beautiful points us beyond itself toward what is true. (Good)",
            3: "Logic. Emotions must not cloud our logical thinking. (Lawful)",
            4: "No Limits. Nothing should fetter the infinite possibility inherent in all existence. (Chaotic)",
            5: "Power. Knowledge is the path to power and domination. (Evil)",
            6: "Self-Improvement. The goal of a life of study is the betterment of oneself. (Any)",
        },
        "bonds": {
            1: "It is my duty to protect my students.",
            2: "I have an ancient text that holds terrible secrets that must not fall into the wrong hands.",
            3: "I work to preserve a library, university, scriptorium, or monastery.",
            4: "My life's work is a series of tomes related to a specific field of lore.",
            5: "I've been searching my whole life for the answer to a certain question.",
            6: "I sold my soul for knowledge. I hope to do great deeds and win it back.",
        },
        "flaws": {
            1: "I am easily distracted by the promise of information.",
            2: "Most people scream and run when they see a demon. I stop and take notes on its anatomy.",
            3: "Unlocking an ancient mystery is worth the price of a civilization.",
            4: "I overlook obvious solutions in favor of complicated ones.",
            5: "I speak without really thinking through my words, invariably insulting others.",
            6: "I can't keep a secret to save my life, or anyone else's.",
        },
    },
    Background.SOLDIER: {
        "skill_proficiencies": {SkillName.ATHLETICS, SkillName.INTIMIDATION},
        "tool_proficiencies": {},
        "languages": {},
        "equipment": {},
        "personality_traits": {
            1: "I'm always polite and respectful.",
            2: "I'm haunted by memories of war. I can't get the images of violence out of my mind.",
            3: "I've lost too many friends, and I'm slow to make new ones.",
            4: "I'm full of inspiring and cautionary tales from my military experience relevant to almost every combat situation.",
            5: "I can stare down a hell hound without flinching.",
            6: "I enjoy being strong and like breaking things.",
            7: "I have a crude sense of humor.",
            8: "I face problems head-on. A simple, direct solution is the best path to success.",
        },
        "ideals": {
            1: "Greater Good. Our lot is to lay down our lives in defense of others. (Good)",
            2: "Responsibility. I do what I must and obey just authority. (Lawful)",
            3: "Independence. When people follow orders blindly, they embrace a kind of tyranny. (Chaotic)",
            4: "Might. In life as in war, the stronger force wins. (Evil)",
            5: "Live and Let Live. Ideals aren't worth killing over or going to war for. (Neutral)",
            6: "Nation. My city, nation, or people are all that matter. (Any)",
        },
        "bonds": {
            1: "I would still lay down my life for the people I served with.",
            2: "Someone saved my life on the battlefield. To this day, I will never leave a friend behind.",
            3: "My honor is my life.",
            4: "I'll never forget the crushing defeat my company suffered or the enemies who dealt it.",
            5: "Those who fight beside me are those worth dying for.",
            6: "I fight for those who cannot fight for themselves.",
        },
        "flaws": {
            1: "The monstrous enemy we faced in battle still leaves me quivering with fear.",
            2: "I have little respect for anyone who is not a proven warrior.",
            3: "I made a terrible mistake in battle that cost many lives — and I would do anything to keep that mistake secret.",
            4: "My hatred of my enemies is blind and unreasoning.",
            5: "I obey the law, even if the law causes misery.",
            6: "I'd rather eat my armor than admit when I'm wrong.",
        },
    },
}
