from django.urls import path

from .views import (
    action_panel,
    attack,
    common,
    concentration,
    dice_roller,
    initiative,
    master,
    player,
)

urlpatterns = [
    path("", common.IndexView.as_view(), name="index"),
    path("games", common.GameListView.as_view(), name="game-list"),
    path("<int:game_id>/", common.GameView.as_view(), name="game"),
    path(
        "create_game/<slug:campaign_slug>",
        common.GameCreateView.as_view(),
        name="game-create",
    ),
    path(
        "create_game/<slug:campaign_slug>/error",
        common.GameCreateErrorView.as_view(),
        name="game-create-error",
    ),
    path(
        "<int:game_id>/invite_user",
        master.UserInviteView.as_view(),
        name="game-invite-user",
    ),
    path(
        "<int:game_id>/invite_user/<int:pk>/confirm",
        master.UserInviteConfirmView.as_view(),
        name="game-invite-user-confirm",
    ),
    path(
        "<int:pk>/start_game",
        master.GameStartView.as_view(),
        name="game-start",
    ),
    path(
        "<int:pk>/start_game/error",
        master.GameStartErrorView.as_view(),
        name="game-start-error",
    ),
    path(
        "<int:game_id>/create_quest",
        master.QuestCreateView.as_view(),
        name="quest-create",
    ),
    path(
        "<int:game_id>/request_ability_check",
        master.AbilityCheckRequestView.as_view(),
        name="ability-check-request-create",
    ),
    path(
        "<int:game_id>/create_combat",
        master.CombatCreateView.as_view(),
        name="combat-create",
    ),
    path(
        "<int:game_id>/combat/<int:combat_id>/advance_turn",
        master.CombatAdvanceTurnView.as_view(),
        name="combat-advance-turn",
    ),
    path(
        "<int:game_id>/combat/<int:combat_id>/end",
        master.CombatEndView.as_view(),
        name="combat-end",
    ),
    path(
        "<int:game_id>/combat/<int:combat_id>/action",
        player.TakeActionView.as_view(),
        name="combat-take-action",
    ),
    path(
        "<int:game_id>/combat/<int:combat_id>/turn-state",
        player.TurnStateView.as_view(),
        name="combat-turn-state",
    ),
    path(
        "<int:game_id>/combat/<int:combat_id>/move",
        player.MoveView.as_view(),
        name="combat-move",
    ),
    path(
        "<int:game_id>/combat/<int:combat_id>/initiative-tracker/",
        initiative.InitiativeTrackerView.as_view(),
        name="initiative-tracker",
    ),
    path(
        "<int:game_id>/combat/<int:combat_id>/action-panel/",
        action_panel.ActionPanelView.as_view(),
        name="action-panel",
    ),
    path(
        "<int:game_id>/combat/<int:combat_id>/ready/",
        initiative.ReadyActionView.as_view(),
        name="combat-ready",
    ),
    path(
        "<int:game_id>/combat/<int:combat_id>/delay/",
        initiative.DelayTurnView.as_view(),
        name="combat-delay",
    ),
    path(
        "<int:game_id>/combat/<int:combat_id>/attack/",
        attack.AttackModalView.as_view(),
        name="combat-attack-modal",
    ),
    path(
        "<int:game_id>/combat/<int:combat_id>/attack/roll/",
        attack.AttackRollView.as_view(),
        name="combat-attack-roll",
    ),
    path(
        "<int:game_id>/combat/<int:combat_id>/attack/damage/",
        attack.DamageRollView.as_view(),
        name="combat-damage-roll",
    ),
    path(
        "<int:game_id>/combat/<int:combat_id>/attack/apply/",
        attack.ApplyDamageView.as_view(),
        name="combat-apply-damage",
    ),
    path(
        "<int:game_id>/dice-roller/",
        dice_roller.DiceRollerModalView.as_view(),
        name="dice-roller-modal",
    ),
    path(
        "<int:game_id>/roll/",
        dice_roller.DiceRollView.as_view(),
        name="dice-roll",
    ),
    path(
        "<int:game_id>/quick-roll/",
        dice_roller.QuickRollView.as_view(),
        name="quick-roll",
    ),
    path(
        "<int:game_id>/concentration/<int:character_id>/",
        concentration.ConcentrationSaveModalView.as_view(),
        name="concentration-save-modal",
    ),
    path(
        "<int:game_id>/concentration/<int:character_id>/roll/",
        concentration.ConcentrationSaveRollView.as_view(),
        name="concentration-save-roll",
    ),
]
