# Generated by Django 5.0.8 on 2024-08-14 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_quest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questupdate",
            name="content",
        ),
        migrations.AddField(
            model_name="questupdate",
            name="quest",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="game.quest"
            ),
            preserve_default=False,
        ),
    ]
