# Generated by Django 6.0.1 on 2026-02-10 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("character", "0023_add_location_field"),
        ("game", "0008_add_concentration_events"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="SpellSettings",
                    fields=[
                        (
                            "name",
                            models.CharField(
                                max_length=100, primary_key=True, serialize=False
                            ),
                        ),
                        (
                            "level",
                            models.PositiveSmallIntegerField(
                                choices=[
                                    (0, "Cantrip"),
                                    (1, "1st Level"),
                                    (2, "2nd Level"),
                                    (3, "3rd Level"),
                                    (4, "4th Level"),
                                    (5, "5th Level"),
                                    (6, "6th Level"),
                                    (7, "7th Level"),
                                    (8, "8th Level"),
                                    (9, "9th Level"),
                                ]
                            ),
                        ),
                        (
                            "school",
                            models.CharField(
                                choices=[
                                    ("abjuration", "Abjuration"),
                                    ("conjuration", "Conjuration"),
                                    ("divination", "Divination"),
                                    ("enchantment", "Enchantment"),
                                    ("evocation", "Evocation"),
                                    ("illusion", "Illusion"),
                                    ("necromancy", "Necromancy"),
                                    ("transmutation", "Transmutation"),
                                ],
                                max_length=15,
                            ),
                        ),
                        (
                            "casting_time",
                            models.CharField(
                                choices=[
                                    ("action", "1 Action"),
                                    ("bonus_action", "1 Bonus Action"),
                                    ("reaction", "1 Reaction"),
                                    ("1_minute", "1 Minute"),
                                    ("10_minutes", "10 Minutes"),
                                    ("1_hour", "1 Hour"),
                                    ("8_hours", "8 Hours"),
                                    ("12_hours", "12 Hours"),
                                    ("24_hours", "24 Hours"),
                                ],
                                max_length=15,
                            ),
                        ),
                        (
                            "casting_time_detail",
                            models.CharField(
                                blank=True,
                                help_text="Additional casting time info (e.g., reaction trigger)",
                                max_length=100,
                            ),
                        ),
                        (
                            "range",
                            models.CharField(
                                choices=[
                                    ("self", "Self"),
                                    ("touch", "Touch"),
                                    ("5_feet", "5 feet"),
                                    ("10_feet", "10 feet"),
                                    ("30_feet", "30 feet"),
                                    ("60_feet", "60 feet"),
                                    ("90_feet", "90 feet"),
                                    ("120_feet", "120 feet"),
                                    ("150_feet", "150 feet"),
                                    ("300_feet", "300 feet"),
                                    ("500_feet", "500 feet"),
                                    ("1_mile", "1 mile"),
                                    ("sight", "Sight"),
                                    ("unlimited", "Unlimited"),
                                    ("special", "Special"),
                                ],
                                max_length=15,
                            ),
                        ),
                        (
                            "range_detail",
                            models.CharField(
                                blank=True,
                                help_text="Additional range info (e.g., area of effect)",
                                max_length=50,
                            ),
                        ),
                        (
                            "components",
                            models.JSONField(
                                default=list, help_text="List of components: V, S, M"
                            ),
                        ),
                        (
                            "material_components",
                            models.CharField(
                                blank=True,
                                help_text="Description of material components if any",
                                max_length=500,
                            ),
                        ),
                        (
                            "material_cost",
                            models.PositiveIntegerField(
                                default=0,
                                help_text="GP cost of material components (0 if no cost)",
                            ),
                        ),
                        (
                            "material_consumed",
                            models.BooleanField(
                                default=False,
                                help_text="Whether material components are consumed",
                            ),
                        ),
                        (
                            "duration",
                            models.CharField(
                                choices=[
                                    ("instantaneous", "Instantaneous"),
                                    ("1_round", "1 round"),
                                    ("1_minute", "1 minute"),
                                    ("10_minutes", "10 minutes"),
                                    ("1_hour", "1 hour"),
                                    ("8_hours", "8 hours"),
                                    ("24_hours", "24 hours"),
                                    ("7_days", "7 days"),
                                    ("10_days", "10 days"),
                                    ("30_days", "30 days"),
                                    ("until_dispelled", "Until dispelled"),
                                    ("special", "Special"),
                                ],
                                max_length=20,
                            ),
                        ),
                        ("concentration", models.BooleanField(default=False)),
                        ("ritual", models.BooleanField(default=False)),
                        ("description", models.TextField(max_length=5000)),
                        (
                            "higher_levels",
                            models.TextField(
                                blank=True,
                                help_text="Effect when cast at higher levels",
                                max_length=1000,
                            ),
                        ),
                        (
                            "classes",
                            models.JSONField(
                                default=list,
                                help_text="List of class names that can learn this spell",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name_plural": "spell settings",
                        "db_table": "character_spellsettings",
                        "ordering": ["level", "name"],
                    },
                ),
                migrations.CreateModel(
                    name="ClassSpellcasting",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "caster_type",
                            models.CharField(
                                blank=True,
                                choices=[
                                    ("prepared", "Prepared"),
                                    ("known", "Known"),
                                    ("pact", "Pact"),
                                ],
                                help_text="Empty for non-casters",
                                max_length=10,
                            ),
                        ),
                        (
                            "spellcasting_ability",
                            models.CharField(
                                blank=True,
                                choices=[
                                    ("intelligence", "Intelligence"),
                                    ("wisdom", "Wisdom"),
                                    ("charisma", "Charisma"),
                                ],
                                max_length=15,
                            ),
                        ),
                        ("learns_cantrips", models.BooleanField(default=False)),
                        (
                            "spell_list_access",
                            models.BooleanField(
                                default=False,
                                help_text="True if class has access to full class spell list (prepared casters)",
                            ),
                        ),
                        ("ritual_casting", models.BooleanField(default=False)),
                        (
                            "spellcasting_focus",
                            models.CharField(
                                blank=True,
                                help_text="Type of focus (arcane, druidic, holy symbol)",
                                max_length=50,
                            ),
                        ),
                        (
                            "klass",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="spellcasting",
                                to="character.class",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name_plural": "class spellcasting",
                        "db_table": "character_classspellcasting",
                    },
                ),
                migrations.CreateModel(
                    name="SpellEffectTemplate",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "effect_type",
                            models.CharField(
                                choices=[
                                    ("damage", "Damage"),
                                    ("healing", "Healing"),
                                    ("condition", "Condition"),
                                    ("buff", "Buff"),
                                    ("debuff", "Debuff"),
                                    ("summon", "Summon"),
                                    ("utility", "Utility"),
                                ],
                                max_length=20,
                            ),
                        ),
                        (
                            "target_type",
                            models.CharField(
                                choices=[
                                    ("self", "Self"),
                                    ("single", "Single Target"),
                                    ("multiple", "Multiple Targets"),
                                    ("area", "Area"),
                                    ("line", "Line"),
                                    ("cone", "Cone"),
                                ],
                                max_length=20,
                            ),
                        ),
                        (
                            "damage_type",
                            models.CharField(
                                blank=True,
                                choices=[
                                    ("acid", "Acid"),
                                    ("bludgeoning", "Bludgeoning"),
                                    ("cold", "Cold"),
                                    ("fire", "Fire"),
                                    ("force", "Force"),
                                    ("lightning", "Lightning"),
                                    ("necrotic", "Necrotic"),
                                    ("piercing", "Piercing"),
                                    ("poison", "Poison"),
                                    ("psychic", "Psychic"),
                                    ("radiant", "Radiant"),
                                    ("slashing", "Slashing"),
                                    ("thunder", "Thunder"),
                                ],
                                max_length=20,
                            ),
                        ),
                        (
                            "base_dice",
                            models.CharField(
                                blank=True,
                                help_text="Base damage/healing dice (e.g., '8d6')",
                                max_length=20,
                            ),
                        ),
                        (
                            "dice_per_level",
                            models.CharField(
                                blank=True,
                                help_text="Additional dice per spell level above base (e.g., '1d6')",
                                max_length=20,
                            ),
                        ),
                        (
                            "save_type",
                            models.CharField(
                                choices=[
                                    ("none", "None"),
                                    ("STR", "Strength"),
                                    ("DEX", "Dexterity"),
                                    ("CON", "Constitution"),
                                    ("INT", "Intelligence"),
                                    ("WIS", "Wisdom"),
                                    ("CHA", "Charisma"),
                                ],
                                default="none",
                                max_length=5,
                            ),
                        ),
                        (
                            "save_effect",
                            models.CharField(
                                choices=[
                                    ("none", "None"),
                                    ("half_damage", "Half Damage"),
                                    ("negates", "Negates"),
                                ],
                                default="none",
                                max_length=15,
                            ),
                        ),
                        (
                            "buff_description",
                            models.TextField(
                                blank=True,
                                help_text="Description of the buff/debuff effect",
                            ),
                        ),
                        (
                            "ac_modifier",
                            models.SmallIntegerField(
                                default=0,
                                help_text="Modifier to AC (positive for buff, negative for debuff)",
                            ),
                        ),
                        (
                            "attack_modifier",
                            models.SmallIntegerField(
                                default=0, help_text="Modifier to attack rolls"
                            ),
                        ),
                        (
                            "damage_modifier",
                            models.SmallIntegerField(
                                default=0, help_text="Modifier to damage rolls"
                            ),
                        ),
                        (
                            "area_radius",
                            models.PositiveSmallIntegerField(
                                default=0,
                                help_text="Radius in feet (0 for non-area effects)",
                            ),
                        ),
                        (
                            "area_shape",
                            models.CharField(
                                blank=True,
                                help_text="Shape of area (sphere, cube, cone, line)",
                                max_length=20,
                            ),
                        ),
                        (
                            "duration_type",
                            models.CharField(
                                choices=[
                                    ("instantaneous", "Instantaneous"),
                                    ("rounds", "Rounds"),
                                    ("minutes", "Minutes"),
                                    ("hours", "Hours"),
                                    ("until_dispelled", "Until Dispelled"),
                                    ("concentration", "Concentration"),
                                ],
                                default="instantaneous",
                                max_length=20,
                            ),
                        ),
                        (
                            "duration_value",
                            models.PositiveSmallIntegerField(
                                default=0,
                                help_text="Duration value (number of rounds, minutes, hours, etc.)",
                            ),
                        ),
                        (
                            "condition",
                            models.ForeignKey(
                                blank=True,
                                help_text="Condition applied by this effect",
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="character.condition",
                            ),
                        ),
                        (
                            "spell",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="effect_templates",
                                to="magic.spellsettings",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "character_spelleffecttemplate",
                        "ordering": ["spell", "effect_type"],
                    },
                ),
                migrations.CreateModel(
                    name="ActiveSpellEffect",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "rounds_remaining",
                            models.PositiveSmallIntegerField(
                                blank=True,
                                help_text="Rounds remaining (null for non-round durations)",
                                null=True,
                            ),
                        ),
                        (
                            "is_concentration",
                            models.BooleanField(
                                default=False,
                                help_text="Whether this effect requires concentration",
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "caster",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="cast_effects",
                                to="character.character",
                            ),
                        ),
                        (
                            "character",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="active_spell_effects",
                                to="character.character",
                            ),
                        ),
                        (
                            "template",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="magic.spelleffecttemplate",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "character_activespelleffect",
                        "ordering": ["-created_at"],
                    },
                ),
                migrations.CreateModel(
                    name="Concentration",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("started_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "rounds_remaining",
                            models.PositiveSmallIntegerField(
                                blank=True,
                                help_text="Rounds remaining if duration is measured in rounds",
                                null=True,
                            ),
                        ),
                        (
                            "character",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="concentration",
                                to="character.character",
                            ),
                        ),
                        (
                            "spell",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="active_concentrations",
                                to="magic.spellsettings",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "character_concentration",
                    },
                ),
                migrations.CreateModel(
                    name="SpellSlotTable",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "class_name",
                            models.CharField(
                                choices=[
                                    ("barbarian", "Barbarian"),
                                    ("bard", "Bard"),
                                    ("cleric", "Cleric"),
                                    ("druid", "Druid"),
                                    ("fighter", "Fighter"),
                                    ("monk", "Monk"),
                                    ("paladin", "Paladin"),
                                    ("ranger", "Ranger"),
                                    ("rogue", "Rogue"),
                                    ("sorcerer", "Sorcerer"),
                                    ("warlock", "Warlock"),
                                    ("wizard", "Wizard"),
                                ],
                                max_length=20,
                            ),
                        ),
                        ("class_level", models.PositiveSmallIntegerField()),
                        (
                            "slot_level",
                            models.PositiveSmallIntegerField(
                                choices=[
                                    (1, "1"),
                                    (2, "2"),
                                    (3, "3"),
                                    (4, "4"),
                                    (5, "5"),
                                    (6, "6"),
                                    (7, "7"),
                                    (8, "8"),
                                    (9, "9"),
                                ]
                            ),
                        ),
                        ("slots", models.PositiveSmallIntegerField(default=0)),
                    ],
                    options={
                        "verbose_name_plural": "spell slot tables",
                        "db_table": "character_spellslottable",
                        "ordering": ["class_name", "class_level", "slot_level"],
                        "unique_together": {
                            ("class_name", "class_level", "slot_level")
                        },
                    },
                ),
                migrations.CreateModel(
                    name="SummonedCreature",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("name", models.CharField(max_length=100)),
                        ("hp_current", models.PositiveIntegerField()),
                        ("hp_max", models.PositiveIntegerField()),
                        ("ac", models.PositiveSmallIntegerField()),
                        (
                            "rounds_remaining",
                            models.PositiveSmallIntegerField(
                                blank=True,
                                help_text="Rounds remaining (null for non-round durations)",
                                null=True,
                            ),
                        ),
                        (
                            "is_concentration",
                            models.BooleanField(
                                default=False,
                                help_text="Whether this summon requires concentration",
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "combat",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="summoned_creatures",
                                to="game.combat",
                            ),
                        ),
                        (
                            "spell",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="magic.spellsettings",
                            ),
                        ),
                        (
                            "summoner",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="summoned_creatures",
                                to="character.character",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "character_summonedcreature",
                        "ordering": ["-created_at"],
                    },
                ),
                migrations.CreateModel(
                    name="WarlockSpellSlot",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("slot_level", models.PositiveSmallIntegerField(default=1)),
                        ("total", models.PositiveSmallIntegerField(default=1)),
                        ("used", models.PositiveSmallIntegerField(default=0)),
                        (
                            "character",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="pact_magic",
                                to="character.character",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "character_warlockspellslot",
                    },
                ),
                migrations.CreateModel(
                    name="CharacterSpellSlot",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "slot_level",
                            models.PositiveSmallIntegerField(
                                choices=[
                                    (1, "Level 1"),
                                    (2, "Level 2"),
                                    (3, "Level 3"),
                                    (4, "Level 4"),
                                    (5, "Level 5"),
                                    (6, "Level 6"),
                                    (7, "Level 7"),
                                    (8, "Level 8"),
                                    (9, "Level 9"),
                                ]
                            ),
                        ),
                        ("total", models.PositiveSmallIntegerField(default=0)),
                        ("used", models.PositiveSmallIntegerField(default=0)),
                        (
                            "character",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="spell_slots",
                                to="character.character",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "character_characterspellslot",
                        "ordering": ["character", "slot_level"],
                        "unique_together": {("character", "slot_level")},
                    },
                ),
                migrations.CreateModel(
                    name="SpellPreparation",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "always_prepared",
                            models.BooleanField(
                                default=False,
                                help_text="Domain/subclass spells that don't count against limit",
                            ),
                        ),
                        (
                            "character",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="prepared_spells",
                                to="character.character",
                            ),
                        ),
                        (
                            "settings",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="magic.spellsettings",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "character_spellpreparation",
                        "ordering": ["settings__level", "settings__name"],
                        "unique_together": {("character", "settings")},
                    },
                ),
                migrations.CreateModel(
                    name="Spell",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "source",
                            models.CharField(
                                blank=True,
                                help_text="Source of the spell (e.g., class, feat, item)",
                                max_length=50,
                            ),
                        ),
                        (
                            "character",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="spells_known",
                                to="character.character",
                            ),
                        ),
                        (
                            "settings",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="magic.spellsettings",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "character_spell",
                        "ordering": ["settings__level", "settings__name"],
                        "unique_together": {("character", "settings")},
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
