# Generated by Django 6.0.1 on 2026-02-10 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("character", "0023_add_location_field"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="ArmorSettings",
                    fields=[
                        (
                            "name",
                            models.CharField(
                                choices=[
                                    ("Padded", "Padded"),
                                    ("Leather", "Leather"),
                                    ("Studded leather", "Studded Leather"),
                                    ("Hide", "Hide"),
                                    ("Chain shirt", "Chain Shirt"),
                                    ("Scale mail", "Scale Mail"),
                                    ("Breastplate", "Breastplate"),
                                    ("Half plate", "Half Plate"),
                                    ("Ring mail", "Ring Mail"),
                                    ("Chain mail", "Chain Mail"),
                                    ("Splint", "Splint"),
                                    ("Plate", "Plate"),
                                    ("Shield", "Shield"),
                                ],
                                max_length=30,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "armor_type",
                            models.CharField(
                                choices=[
                                    ("LA", "Light Armor"),
                                    ("MA", "Medium Armor"),
                                    ("HA", "Heavy Armor"),
                                    ("SH", "Shield"),
                                ],
                                max_length=2,
                            ),
                        ),
                        ("cost", models.SmallIntegerField()),
                        ("ac", models.CharField(max_length=25)),
                        (
                            "strength",
                            models.CharField(blank=True, max_length=6, null=True),
                        ),
                        (
                            "stealth",
                            models.CharField(blank=True, max_length=1, null=True),
                        ),
                        ("weight", models.SmallIntegerField()),
                    ],
                    options={
                        "verbose_name_plural": "armor settings",
                        "db_table": "character_armorsettings",
                    },
                ),
                migrations.CreateModel(
                    name="GearSettings",
                    fields=[
                        (
                            "name",
                            models.CharField(
                                choices=[
                                    ("Abacus", "Abacus"),
                                    ("Acid", "Acid"),
                                    ("Alchemist's fire", "Alchemists Fire"),
                                    ("Arrows", "Arrows"),
                                    ("Blowgun needles", "Blowgun Needles"),
                                    ("Crossbow bolts", "Crossbow Bolts"),
                                    ("Sling bullets", "Sling Bullets"),
                                    ("Antitoxin", "Antitoxin"),
                                    ("Crystal", "Crystal"),
                                    ("Orb", "Orb"),
                                    ("Rod", "Rod"),
                                    ("Staff", "Staff"),
                                    ("Wand", "Wand"),
                                    ("Backpack", "Backpack"),
                                    ("Ball bearings", "Ball Bearings"),
                                    ("Basket", "Basket"),
                                    ("Bedroll", "Bedroll"),
                                    ("Bell", "Bell"),
                                    ("Blanket", "Blanket"),
                                    ("Block and tackle", "Block And Tackle"),
                                    ("Book", "Book"),
                                    ("Bottle, glass", "Bottle Glass"),
                                    ("Caltrops", "Caltrops"),
                                    ("Candle", "Candle"),
                                    ("Case, crossbow bolt", "Case Crossbow Bolt"),
                                    ("Case, map or scroll", "Case Map Or Scroll"),
                                    ("Chain", "Chain"),
                                    ("Chalk", "Chalk"),
                                    ("Chest", "Chest"),
                                    ("Climber's kit", "Climbers Kit"),
                                    ("Clothes, common", "Clothes Common"),
                                    ("Clothes, costume", "Clothes Costume"),
                                    ("Clothes, fine", "Clothes Fine"),
                                    ("Clothes, traveler's", "Clothes Travelers"),
                                    ("Component pouch", "Component Pouch"),
                                    ("Crowbar", "Crowbar"),
                                    ("Sprig of mistletoe", "Spring Of Mistletoe"),
                                    ("Totem", "Totem"),
                                    ("Wooden staff", "Wooden Staff"),
                                    ("Yew wand", "Yew Wand"),
                                    ("Fishing tackle", "Fishing Tackle"),
                                    ("Flask or tankard", "Flask Or Tankard"),
                                    ("Grappling hook", "Grappling Hook"),
                                    ("Hammer", "Hammer"),
                                    ("Hammer, sledge", "Hammer Sledge"),
                                    ("Healer's kit", "Healers Kit"),
                                    ("Amulet", "Amulet"),
                                    ("Emblem", "Emblem"),
                                    ("Reliquary", "Reliquary"),
                                    ("Holy water", "Holy Water"),
                                    ("Hourglass", "Hourglass"),
                                    ("Hunting trap", "Hunting Trap"),
                                    ("Ink", "Ink"),
                                    ("Ink pen", "Ink Pen"),
                                    ("Jug or pitcher", "Jug Or Pitcher"),
                                    ("Ladder", "Ladder"),
                                    ("Lamp", "Lamp"),
                                    ("Lantern, bullseye", "Lantern Bullseye"),
                                    ("Lantern, hooded", "Lantern Hooded"),
                                    ("Lock", "Lock"),
                                    ("Magnifying glass", "Magnifying Glass"),
                                    ("Manacles", "Manacles"),
                                    ("Mess kit", "Mess Kit"),
                                    ("Mirror, steel", "Mirror Steel"),
                                    ("Oil", "Oil"),
                                    ("Paper", "Paper"),
                                    ("Parchment", "Parchment"),
                                    ("Perfume", "Perfume"),
                                    ("Pick, miner's", "Pick Miners"),
                                    ("Piton", "Piton"),
                                    ("Poison, basic", "Poison Basic"),
                                    ("Pole", "Pole"),
                                    ("Pot, iron", "Pot Iron"),
                                    ("Potion of healing", "Potion Of Healing"),
                                    ("Pouch", "Pouch"),
                                    ("Quiver", "Quiver"),
                                    ("Ram, portable", "Ram Portable"),
                                    ("Rations", "Rations"),
                                    ("Robes", "Robes"),
                                    ("Rope, hempen", "Rope Hempen"),
                                    ("Rope, silk", "Rope Silk"),
                                    ("Sack", "Sack"),
                                    ("Scale, merchant's", "Scale Merchants"),
                                    ("Sealing wax", "Sealing Wax"),
                                    ("Shovel", "Shovel"),
                                    ("Signal whistle", "Signal Whistle"),
                                    ("Signet ring", "Signet Ring"),
                                    ("Soap", "Soap"),
                                    ("Spellbook", "Spellbook"),
                                    ("Spikes, iron", "Spikes Iron"),
                                    ("Spyglass", "Spyglass"),
                                    ("Tent, two-person", "Tent Two Persons"),
                                    ("Tinderbox", "Tinderbox"),
                                    ("Torch", "Torch"),
                                    ("Vial", "Vial"),
                                    ("Waterskin", "Waterskin"),
                                    ("Whetstone", "Whetstone"),
                                ],
                                max_length=30,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "gear_type",
                            models.CharField(
                                choices=[
                                    ("AM", "Ammunition"),
                                    ("AF", "Arcane focus"),
                                    ("DF", "Druidic focus"),
                                    ("HS", "Holy symbol"),
                                    ("MI", "Misc"),
                                ],
                                default="MI",
                                max_length=2,
                            ),
                        ),
                    ],
                    options={
                        "verbose_name_plural": "gear settings",
                        "db_table": "character_gearsettings",
                    },
                ),
                migrations.CreateModel(
                    name="Inventory",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("capacity", models.SmallIntegerField(default=0)),
                        ("gp", models.SmallIntegerField(default=0)),
                    ],
                    options={
                        "db_table": "character_inventory",
                    },
                ),
                migrations.CreateModel(
                    name="MagicItemSettings",
                    fields=[
                        (
                            "name",
                            models.CharField(
                                choices=[
                                    ("Weapon +1", "Weapon Plus 1"),
                                    ("Weapon +2", "Weapon Plus 2"),
                                    ("Weapon +3", "Weapon Plus 3"),
                                    ("Armor +1", "Armor Plus 1"),
                                    ("Armor +2", "Armor Plus 2"),
                                    ("Armor +3", "Armor Plus 3"),
                                    ("Shield +1", "Shield Plus 1"),
                                    ("Shield +2", "Shield Plus 2"),
                                    ("Shield +3", "Shield Plus 3"),
                                    ("Potion of Healing", "Potion Of Healing"),
                                    (
                                        "Potion of Greater Healing",
                                        "Potion Of Greater Healing",
                                    ),
                                    (
                                        "Potion of Superior Healing",
                                        "Potion Of Superior Healing",
                                    ),
                                    (
                                        "Potion of Supreme Healing",
                                        "Potion Of Supreme Healing",
                                    ),
                                    (
                                        "Wand of Magic Missiles",
                                        "Wand Of Magic Missiles",
                                    ),
                                    (
                                        "Wand of the War Mage +1",
                                        "Wand Of The War Mage Plus 1",
                                    ),
                                    (
                                        "Wand of the War Mage +2",
                                        "Wand Of The War Mage Plus 2",
                                    ),
                                    (
                                        "Wand of the War Mage +3",
                                        "Wand Of The War Mage Plus 3",
                                    ),
                                    ("Staff of the Magi", "Staff Of The Magi"),
                                    ("Staff of Power", "Staff Of Power"),
                                    ("Staff of Healing", "Staff Of Healing"),
                                    (
                                        "Staff of the Woodlands",
                                        "Staff Of The Woodlands",
                                    ),
                                    ("Ring of Protection", "Ring Of Protection"),
                                    ("Ring of Spell Storing", "Ring Of Spell Storing"),
                                    ("Amulet of Health", "Amulet Of Health"),
                                    ("Bag of Holding", "Bag Of Holding"),
                                    ("Boots of Elvenkind", "Boots Of Elvenkind"),
                                    ("Boots of Speed", "Boots Of Speed"),
                                    ("Bracers of Defense", "Bracers Of Defense"),
                                    ("Cloak of Elvenkind", "Cloak Of Elvenkind"),
                                    ("Cloak of Protection", "Cloak Of Protection"),
                                    (
                                        "Gauntlets of Ogre Power",
                                        "Gauntlets Of Ogre Power",
                                    ),
                                    ("Headband of Intellect", "Headband Of Intellect"),
                                    ("Pearl of Power", "Pearl Of Power"),
                                ],
                                max_length=50,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "item_type",
                            models.CharField(
                                choices=[
                                    ("armor", "Armor"),
                                    ("potion", "Potion"),
                                    ("ring", "Ring"),
                                    ("rod", "Rod"),
                                    ("scroll", "Scroll"),
                                    ("staff", "Staff"),
                                    ("wand", "Wand"),
                                    ("weapon", "Weapon"),
                                    ("wondrous", "Wondrous Item"),
                                ],
                                max_length=10,
                            ),
                        ),
                        (
                            "rarity",
                            models.CharField(
                                choices=[
                                    ("common", "Common"),
                                    ("uncommon", "Uncommon"),
                                    ("rare", "Rare"),
                                    ("very_rare", "Very Rare"),
                                    ("legendary", "Legendary"),
                                ],
                                max_length=15,
                            ),
                        ),
                        ("requires_attunement", models.BooleanField(default=False)),
                        (
                            "attunement_requirement",
                            models.CharField(
                                blank=True,
                                help_text="E.g., 'by a spellcaster', 'by a cleric or paladin'",
                                max_length=100,
                            ),
                        ),
                        ("description", models.TextField(max_length=2000)),
                        (
                            "bonus",
                            models.CharField(
                                blank=True,
                                choices=[
                                    ("+1", "+1"),
                                    ("+2", "+2"),
                                    ("+3", "+3"),
                                    ("+1", "+1"),
                                    ("+2", "+2"),
                                    ("+3", "+3"),
                                ],
                                max_length=2,
                            ),
                        ),
                        ("effects", models.JSONField(blank=True, default=dict)),
                        ("is_consumable", models.BooleanField(default=False)),
                        ("weight", models.PositiveSmallIntegerField(default=0)),
                        ("cost", models.PositiveIntegerField(default=0)),
                    ],
                    options={
                        "verbose_name": "magic item settings",
                        "verbose_name_plural": "magic item settings",
                        "db_table": "character_magicitemsettings",
                        "ordering": ["rarity", "name"],
                    },
                ),
                migrations.CreateModel(
                    name="PackSettings",
                    fields=[
                        (
                            "name",
                            models.CharField(
                                choices=[
                                    ("Burglar's Pack", "Burglars Pack"),
                                    ("Diplomat's Pack", "Diplomats Pack"),
                                    ("Dungeoneer's Pack", "Dungeoneers Pack"),
                                    ("Entertainer's Pack", "Entertainers Pack"),
                                    ("Explorer's Pack", "Explorers Pack"),
                                    ("Priest's Pack", "Priests Pack"),
                                    ("Scholar's Pack", "Scholars Pack"),
                                ],
                                max_length=30,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                    ],
                    options={
                        "verbose_name_plural": "pack settings",
                        "db_table": "character_packsettings",
                    },
                ),
                migrations.CreateModel(
                    name="ToolSettings",
                    fields=[
                        (
                            "name",
                            models.CharField(
                                choices=[
                                    ("alchemists_supplies", "Alchemist's supplies"),
                                    ("brewers_supplies", "Brewer's supplies"),
                                    (
                                        "calligraphers_supplies",
                                        "Calligrapher's supplies",
                                    ),
                                    ("carpenters_tools", "Carpenter's tools"),
                                    ("cartographers_tools", "Cartographer's tools"),
                                    ("cobblers_tools", "Cobbler's tools"),
                                    ("cooks_utensils", "Cook's utensils"),
                                    ("glassblowers_tools", "Glassblower's tools"),
                                    ("jewelers_tools", "Jeweler's tools"),
                                    ("leatherworkers_tools", "Leatherworker's tools"),
                                    ("masons_tools", "Mason's tools"),
                                    ("painters_supplies", "Painter's supplies"),
                                    ("potters_tools", "Potter's tools"),
                                    ("smiths_tools", "Smith's tools"),
                                    ("tinkers_tools", "Tinker's tools"),
                                    ("weavers_tools", "Weaver's tools"),
                                    ("woodcarvers_tools", "Woodcarver's tools"),
                                    ("disguise_kit", "Disguise kit"),
                                    ("forgery_kit", "Forgery kit"),
                                    ("dice_set", "Dice set"),
                                    ("dragonchess_set", "Dragonchess set"),
                                    ("playing_card_set", "Playing card set"),
                                    ("three_dragon_ante_set", "Three-Dragon Ante set"),
                                    ("herbalism_kit", "Herbalism kit"),
                                    ("bagpipes", "Bagpipes"),
                                    ("drum", "Drum"),
                                    ("dulcimer", "Dulcimer"),
                                    ("flute", "Flute"),
                                    ("lute", "Lute"),
                                    ("lyre", "Lyre"),
                                    ("horn", "Horn"),
                                    ("pan_flute", "Pan flute"),
                                    ("shawm", "Shawm"),
                                    ("viol", "Viol"),
                                    ("navigators_tools", "Navigator's tools"),
                                    ("poisoners_kit", "Poisoner's kit"),
                                    ("thieves_tools", "Thieves' tools"),
                                ],
                                max_length=30,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "tool_type",
                            models.CharField(
                                choices=[
                                    ("AT", "Artisan's tools"),
                                    ("GS", "Gaming set"),
                                    ("MU", "Musical instrument"),
                                    ("MI", "Misc"),
                                ],
                                default="MI",
                                max_length=2,
                            ),
                        ),
                    ],
                    options={
                        "verbose_name_plural": "tool settings",
                        "db_table": "character_toolsettings",
                    },
                ),
                migrations.CreateModel(
                    name="WeaponSettings",
                    fields=[
                        (
                            "name",
                            models.CharField(
                                choices=[
                                    ("Club", "Club"),
                                    ("Dagger", "Dagger"),
                                    ("Greatclub", "Greatclub"),
                                    ("Handaxe", "Handaxe"),
                                    ("Javelin", "Javelin"),
                                    ("Light hammer", "Light Hammer"),
                                    ("Mace", "Mace"),
                                    ("Quarterstaff", "Quarterstaff"),
                                    ("Sickle", "Sickle"),
                                    ("Spear", "Spear"),
                                    ("Crossbow, light", "Crossbow Light"),
                                    ("Dart", "Dart"),
                                    ("Shortbow", "Shortbow"),
                                    ("Sling", "Sling"),
                                    ("Battleaxe", "Battleaxe"),
                                    ("Flail", "Flail"),
                                    ("Glaive", "Glaive"),
                                    ("Greataxe", "Greataxe"),
                                    ("Greatsword", "Greatsword"),
                                    ("Halberd", "Halberd"),
                                    ("Lance", "Lance"),
                                    ("Longsword", "Longsword"),
                                    ("Maul", "Maul"),
                                    ("Morningstar", "Morningstar"),
                                    ("Pike", "Pike"),
                                    ("Rapier", "Rapier"),
                                    ("Scimitar", "Scimitar"),
                                    ("Shortsword", "Shortsword"),
                                    ("Trident", "Trident"),
                                    ("War pick", "War Pick"),
                                    ("Warhammer", "Warhammer"),
                                    ("Whip", "Whip"),
                                    ("Blowgun", "Blowgun"),
                                    ("Crossbow, hand", "Crossbow Hand"),
                                    ("Crossbow, heavy", "Crossbow Heavy"),
                                    ("Longbow", "Longbow"),
                                    ("Net", "Net"),
                                ],
                                max_length=30,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "weapon_type",
                            models.CharField(
                                choices=[
                                    ("SM", "Simple Melee"),
                                    ("SR", "Simple Ranged"),
                                    ("MM", "Martial Melee"),
                                    ("MR", "Marial Ranged"),
                                ],
                                max_length=2,
                            ),
                        ),
                        ("cost", models.SmallIntegerField()),
                        ("damage", models.CharField(max_length=15, null=True)),
                        ("weight", models.SmallIntegerField()),
                        ("properties", models.CharField(max_length=60, null=True)),
                        (
                            "mastery",
                            models.CharField(
                                blank=True,
                                choices=[
                                    ("cleave", "Cleave"),
                                    ("graze", "Graze"),
                                    ("nick", "Nick"),
                                    ("push", "Push"),
                                    ("sap", "Sap"),
                                    ("slow", "Slow"),
                                    ("topple", "Topple"),
                                    ("vex", "Vex"),
                                ],
                                max_length=10,
                                null=True,
                            ),
                        ),
                    ],
                    options={
                        "verbose_name_plural": "weapon settings",
                        "db_table": "character_weaponsettings",
                    },
                ),
                migrations.CreateModel(
                    name="Gear",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "settings",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="equipment.gearsettings",
                            ),
                        ),
                        (
                            "inventory",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="equipment.inventory",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "character_gear",
                    },
                ),
                migrations.CreateModel(
                    name="Armor",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "settings",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="equipment.armorsettings",
                            ),
                        ),
                        (
                            "inventory",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="equipment.inventory",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "character_armor",
                    },
                ),
                migrations.CreateModel(
                    name="MagicItem",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "current_charges",
                            models.PositiveSmallIntegerField(blank=True, null=True),
                        ),
                        ("is_identified", models.BooleanField(default=True)),
                        ("is_cursed", models.BooleanField(default=False)),
                        ("curse_revealed", models.BooleanField(default=False)),
                        ("notes", models.TextField(blank=True, max_length=500)),
                        (
                            "inventory",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="equipment.inventory",
                            ),
                        ),
                        (
                            "settings",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="equipment.magicitemsettings",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "magic item",
                        "verbose_name_plural": "magic items",
                        "db_table": "character_magicitem",
                        "ordering": ["settings__name"],
                    },
                ),
                migrations.CreateModel(
                    name="Attunement",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("attuned_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "character",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="attunements",
                                to="character.character",
                            ),
                        ),
                        (
                            "magic_item",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="attunement",
                                to="equipment.magicitem",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "attunement",
                        "verbose_name_plural": "attunements",
                        "db_table": "character_attunement",
                        "ordering": ["attuned_at"],
                    },
                ),
                migrations.CreateModel(
                    name="Pack",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "inventory",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="equipment.inventory",
                            ),
                        ),
                        (
                            "settings",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="equipment.packsettings",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "character_pack",
                    },
                ),
                migrations.CreateModel(
                    name="Tool",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "inventory",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="equipment.inventory",
                            ),
                        ),
                        (
                            "settings",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="equipment.toolsettings",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "character_tool",
                    },
                ),
                migrations.CreateModel(
                    name="Weapon",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "inventory",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="equipment.inventory",
                            ),
                        ),
                        (
                            "settings",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="equipment.weaponsettings",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "character_weapon",
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
