# Generated by Django 6.0.1 on 2026-02-14 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bestiary", "0006_migrate_remaining_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monstersettings",
            name="actions_json",
        ),
        migrations.RemoveField(
            model_name="monstersettings",
            name="lair_actions_json",
        ),
        migrations.RemoveField(
            model_name="monstersettings",
            name="legendary_actions_json",
        ),
        migrations.RemoveField(
            model_name="monstersettings",
            name="reactions_json",
        ),
        migrations.RemoveField(
            model_name="monstersettings",
            name="spellcasting_json",
        ),
        migrations.RemoveField(
            model_name="monstersettings",
            name="traits_json",
        ),
    ]
