# Generated by Django 4.2.3 on 2023-07-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("synopis", models.CharField(max_length=3000)),
                ("main_conflict", models.CharField(max_length=1000)),
            ],
        ),
    ]
