# Generated by Django 4.2.5 on 2023-09-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "synopsis",
                    models.TextField(
                        help_text="This is the background story of your game.",
                        max_length=3000,
                    ),
                ),
                (
                    "main_conflict",
                    models.TextField(
                        help_text="The conflict could be a person, such as a villain, or an event,\n        such as a natural disaster or viral disease.\n        The conflict will help to provide the objective of the game.",
                        max_length=1000,
                    ),
                ),
                (
                    "objective",
                    models.TextField(
                        help_text="This needs to be clearly outlined in the rules so that all the players\n        understand what the main objective of the game is.\n        Popular win objectives include reaching a certain number of points,\n        achieving an objective, or reaching a certain point in the map.",
                        max_length=500,
                    ),
                ),
            ],
        ),
    ]
