# Generated by Django 4.2.3 on 2023-07-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master", "0002_rename_synopis_story_synopsis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="main_conflict",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="story",
            name="synopsis",
            field=models.TextField(max_length=3000),
        ),
    ]
