# Generated by Django 4.2.3 on 2023-07-09 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("master", "0003_alter_story_main_conflict_alter_story_synopsis"),
    ]

    operations = [
        migrations.RenameField(
            model_name="story",
            old_name="name",
            new_name="title",
        ),
    ]
