# Generated by Django 4.2.3 on 2023-07-09 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master", "0004_rename_name_story_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="slug",
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
