# Generated by Django 4.2.3 on 2023-07-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master", "0005_story_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
