# Generated by Django 4.2.3 on 2023-07-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master", "0007_story_objective"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="story",
            options={"verbose_name_plural": "stories"},
        ),
        migrations.AlterField(
            model_name="story",
            name="main_conflict",
            field=models.TextField(
                help_text="The conflict could be a person, such as a villain, or an event,\n        such as a natural disaster or viral disease.\n        The conflict will help to provide the objective of the game.",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="objective",
            field=models.TextField(
                help_text="This needs to be clearly outlined in the rules so that all the players\n        understand what the main objective of the game is.\n        Popular win objectives include reaching a certain number of points,\n        achieving an objective, or reaching a certain point in the map.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="synopsis",
            field=models.TextField(
                help_text="This is the background story of your game.", max_length=3000
            ),
        ),
    ]
