# Generated by Django 4.2.4 on 2023-08-26 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0014_rename_tale_quest"),
        ("master", "0010_delete_master"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Story",
            new_name="Campaign",
        ),
    ]
