# Generated by Django 4.2.4 on 2023-08-26 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("master", "0011_rename_story_campaign"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={},
        ),
    ]
