# Generated by Django 4.2 on 2023-04-12 19:57

import django.db.models.deletion
import django.utils.timezone
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("game", "0001_initial"),
        ("game", "0002_alter_choice_selection"),
        ("game", "0003_game_status"),
        ("game", "0004_damage_healing_xpincrease"),
        ("game", "0005_alter_game_status"),
        ("game", "0006_alter_game_status"),
        ("game", "0007_xpincrease_character"),
        ("game", "0008_damage_character"),
        ("game", "0009_healing_character"),
        ("game", "0010_alter_choice_selection"),
        ("game", "0011_character_user"),
        ("game", "0012_alter_character_user"),
        ("game", "0013_game_user"),
        ("game", "0014_alter_game_user"),
        ("game", "0015_alter_pendingaction_character"),
        ("game", "0016_alter_event_options_event_game_event_date_707313_idx"),
        ("game", "0017_alter_tale_options"),
        ("game", "0018_alter_tale_options_and_more"),
        ("game", "0019_alter_event_options_event_game_event_date_707313_idx"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("message", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("P", "Under preparation"),
                            ("O", "Ongoing"),
                            ("F", "Finished"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tale",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                ("description", models.CharField(max_length=1000)),
            ],
            bases=("game.event",),
        ),
        migrations.AddField(
            model_name="event",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game.game"
            ),
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "race",
                    models.CharField(
                        choices=[
                            ("H", "Human"),
                            ("O", "Orc"),
                            ("E", "Elf"),
                            ("D", "Dwarf"),
                        ],
                        max_length=1,
                    ),
                ),
                ("xp", models.SmallIntegerField(default=0)),
                ("hp", models.SmallIntegerField(default=100)),
                ("max_hp", models.SmallIntegerField(default=100)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game.game",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiceLaunch",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                ("score", models.SmallIntegerField()),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.character"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("game.event",),
        ),
        migrations.CreateModel(
            name="XpIncrease",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                ("xp", models.SmallIntegerField()),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.character"
                    ),
                ),
            ],
            bases=("game.event",),
        ),
        migrations.CreateModel(
            name="Damage",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                ("hp", models.SmallIntegerField()),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.character"
                    ),
                ),
            ],
            bases=("game.event",),
        ),
        migrations.CreateModel(
            name="Healing",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                ("hp", models.SmallIntegerField()),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.character"
                    ),
                ),
            ],
            bases=("game.event",),
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                ("selection", models.CharField(max_length=50)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.character"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("game.event",),
        ),
        migrations.CreateModel(
            name="PendingAction",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[("D", "Launch dice"), ("C", "Make choice")],
                        max_length=1,
                    ),
                ),
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="game.character"
                    ),
                ),
            ],
            bases=("game.event",),
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-date"]},
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["-date"], name="game_event_date_707313_idx"),
        ),
        migrations.AlterModelOptions(
            name="tale",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="event",
            name="game_event_date_707313_idx",
        ),
        migrations.AlterModelOptions(
            name="event",
            options={},
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["-date"], name="game_event_date_707313_idx"),
        ),
    ]
