# Generated by Django 5.0.8 on 2024-08-14 17:43

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("character", "0002_initial"),
        ("game", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="master",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="character",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="character.character"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game.game"
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="combat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game.combat"
            ),
        ),
        migrations.AddField(
            model_name="turn",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game.player"
            ),
        ),
        migrations.AddField(
            model_name="turn",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game.round"
            ),
        ),
        migrations.AddField(
            model_name="characterinvitation",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="character.character"
            ),
        ),
        migrations.AddField(
            model_name="combatinitialization",
            name="combat",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="game.combat"
            ),
        ),
        migrations.AddField(
            model_name="combatinitiativerequest",
            name="fighter",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="game.fighter"
            ),
        ),
        migrations.AddField(
            model_name="combatinitiativeresponse",
            name="request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="game.combatinitiativerequest",
            ),
        ),
        migrations.AddField(
            model_name="combatinitiativeresult",
            name="fighter",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="game.fighter"
            ),
        ),
        migrations.AddField(
            model_name="combatinitiativeresult",
            name="request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="game.combatinitiativerequest",
            ),
        ),
        migrations.AddField(
            model_name="combatinitiativeresult",
            name="response",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="game.combatinitiativeresponse",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="author",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="game.player"
            ),
        ),
        migrations.AddField(
            model_name="rollrequest",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="character.character"
            ),
        ),
        migrations.AddField(
            model_name="rollresponse",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="character.character"
            ),
        ),
        migrations.AddField(
            model_name="rollresponse",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game.rollrequest"
            ),
        ),
        migrations.AddField(
            model_name="rollresult",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="character.character"
            ),
        ),
        migrations.AddField(
            model_name="rollresult",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game.rollrequest"
            ),
        ),
        migrations.AddField(
            model_name="rollresult",
            name="response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game.rollresponse"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                django.db.models.functions.text.Upper("name"),
                name="game_name_upper_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["-date"], name="game_event_date_707313_idx"),
        ),
    ]
