# Generated by Django 4.1.7 on 2023-03-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="selection",
            field=models.CharField(max_length=300),
        ),
    ]
