# Generated by Django 4.2.3 on 2023-07-18 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master", "0009_master"),
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="master",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="master.master"
            ),
        ),
    ]
