# Generated by Django 5.0.7 on 2024-08-03 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="combat",
            name="game",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="game.game"
            ),
            preserve_default=False,
        ),
    ]
