# Generated by Django 5.0.1 on 2024-01-26 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0021_skill_description"),
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbilityCheckRequest",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                (
                    "difficulty_class",
                    models.SmallIntegerField(
                        choices=[
                            (5, "Very easy"),
                            (10, "Easy"),
                            (15, "Medium"),
                            (20, "Hard"),
                            (25, "Very hard"),
                            (30, "Nearly impossible"),
                        ]
                    ),
                ),
                (
                    "ability_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.abilitytype",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("game.event",),
        ),
    ]
