# Generated by Django 4.1.6 on 2023-02-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_alter_pendingaction_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="pendingaction",
            name="action_type",
            field=models.CharField(
                choices=[("D", "Launch dice"), ("C", "Make choice")], max_length=1
            ),
        ),
    ]
