# Generated by Django 5.0.7 on 2024-08-03 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_alter_fighter_character"),
    ]

    operations = [
        migrations.CreateModel(
            name="CombatInitiativeRequest",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                (
                    "combat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="game.combat"
                    ),
                ),
            ],
            bases=("game.event",),
        ),
        migrations.CreateModel(
            name="CombatInitiativeResponse",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                (
                    "combat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="game.combat"
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.combatinitiativerequest",
                    ),
                ),
            ],
            bases=("game.event",),
        ),
        migrations.CreateModel(
            name="CombatInitiativeResult",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                (
                    "combat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="game.combat"
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.combatinitiativerequest",
                    ),
                ),
                (
                    "response",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.combatinitiativeresponse",
                    ),
                ),
            ],
            bases=("game.event",),
        ),
    ]
