# Generated by Django 5.2.8 on 2026-01-01 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_alter_rollrequest_ability_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fighter",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game.player"
            ),
        ),
    ]
