# Generated by Django 5.1.4 on 2024-12-30 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_remove_message_author_event_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rollresponse",
            name="player",
        ),
        migrations.RemoveField(
            model_name="rollresult",
            name="player",
        ),
    ]
