# Generated by Django 5.0.1 on 2024-02-02 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_abilitycheckrequest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Instruction",
        ),
    ]
