# Generated by Django 5.0.7 on 2024-07-29 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_event_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="author",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="game.player"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_from_master",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
