# Generated by Django 5.0.7 on 2024-08-03 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_combat_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="combatinitialization",
            name="combat",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="game.combat"
            ),
            preserve_default=False,
        ),
    ]
