# Generated by Django 5.0.6 on 2024-06-15 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0066_alter_weaponsettings_damage_and_more"),
        ("game", "0002_rename_status_game_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Combat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.game"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fighter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_surprised", models.BooleanField(default=False)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                    ),
                ),
                (
                    "combat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.combat"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "combat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.combat"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Turn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("move", models.IntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("attack", "Attack"),
                            ("cast_spell", "Cast Spell"),
                            ("dash", "Dash"),
                            ("disangage", "Disengage"),
                            ("dodge", "Dodge"),
                            ("help", "Help"),
                            ("hide", "Hide"),
                            ("ready", "Ready"),
                            ("search", "Search"),
                            ("use_object", "Use Object"),
                        ]
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.player"
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.round"
                    ),
                ),
            ],
        ),
    ]
