# Generated by Django 5.2.9 on 2026-01-12 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_fighter_player_to_fk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fighter",
            options={"ordering": ["-dexterity_check"]},
        ),
        migrations.AlterModelOptions(
            name="round",
            options={"ordering": ["number"]},
        ),
        migrations.AlterModelOptions(
            name="turn",
            options={"ordering": ["round__number"]},
        ),
        migrations.RemoveField(
            model_name="turn",
            name="move",
        ),
        migrations.RemoveField(
            model_name="turn",
            name="player",
        ),
        migrations.AddField(
            model_name="combat",
            name="current_fighter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_turn_combat",
                to="game.fighter",
            ),
        ),
        migrations.AddField(
            model_name="combat",
            name="current_round",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="combat",
            name="current_turn_index",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="combat",
            name="state",
            field=models.CharField(
                choices=[("RI", "Rolling Initiative"), ("A", "Active"), ("E", "Ended")],
                default="RI",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="number",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="turn",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="turn",
            name="fighter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.fighter",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="combat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rounds",
                to="game.combat",
            ),
        ),
        migrations.AlterField(
            model_name="turn",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("attack", "Attack"),
                    ("cast_spell", "Cast Spell"),
                    ("dash", "Dash"),
                    ("disangage", "Disengage"),
                    ("dodge", "Dodge"),
                    ("help", "Help"),
                    ("hide", "Hide"),
                    ("ready", "Ready"),
                    ("search", "Search"),
                    ("use_object", "Use Object"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="turn",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turns",
                to="game.round",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="round",
            unique_together={("combat", "number")},
        ),
        migrations.CreateModel(
            name="CombatEnded",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                (
                    "combat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combat_ended_events",
                        to="game.combat",
                    ),
                ),
            ],
            bases=("game.event",),
        ),
        migrations.CreateModel(
            name="CombatStarted",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                (
                    "combat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combat_started_events",
                        to="game.combat",
                    ),
                ),
            ],
            bases=("game.event",),
        ),
        migrations.CreateModel(
            name="RoundEnded",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                ("round_number", models.PositiveSmallIntegerField()),
                (
                    "combat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_ended_events",
                        to="game.combat",
                    ),
                ),
            ],
            bases=("game.event",),
        ),
        migrations.CreateModel(
            name="TurnEnded",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                ("round_number", models.PositiveSmallIntegerField()),
                (
                    "combat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turn_ended_events",
                        to="game.combat",
                    ),
                ),
                (
                    "fighter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turn_ended_events",
                        to="game.fighter",
                    ),
                ),
            ],
            bases=("game.event",),
        ),
        migrations.CreateModel(
            name="TurnStarted",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                ("round_number", models.PositiveSmallIntegerField()),
                (
                    "combat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turn_started_events",
                        to="game.combat",
                    ),
                ),
                (
                    "fighter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turn_started_events",
                        to="game.fighter",
                    ),
                ),
            ],
            bases=("game.event",),
        ),
    ]
