# Generated by Django 5.1.4 on 2025-01-08 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_remove_rollresponse_player_remove_rollresult_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="fighter",
            name="player",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="game.player"
            ),
            preserve_default=False,
        ),
    ]
