# Generated by Django 4.1.7 on 2023-03-09 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_game_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Damage",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                ("hp", models.SmallIntegerField()),
            ],
            bases=("game.event",),
        ),
        migrations.CreateModel(
            name="Healing",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                ("hp", models.SmallIntegerField()),
            ],
            bases=("game.event",),
        ),
        migrations.CreateModel(
            name="XpIncrease",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                ("xp", models.SmallIntegerField()),
            ],
            bases=("game.event",),
        ),
    ]
