# Generated by Django 4.1.6 on 2023-02-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_alter_game_name_alter_pendingaction_action_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="narrative",
            name="message",
            field=models.CharField(max_length=1000),
        ),
    ]
