# Generated by Django 5.0.1 on 2024-02-02 06:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_delete_instruction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Choice",
        ),
    ]
