# Generated by Django 5.0.6 on 2024-06-15 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_combat_fighter_round_turn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="combat",
            name="game",
        ),
        migrations.RemoveField(
            model_name="combat",
            name="id",
        ),
        migrations.AddField(
            model_name="combat",
            name="event_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="game.event",
            ),
            preserve_default=False,
        ),
    ]
