# Generated by Django 5.0.7 on 2024-07-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_remove_combat_game_remove_combat_id_combat_event_ptr"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("message", "Message"),
                    ("game.start", "Game Start"),
                    ("quest.update", "Quest Update"),
                    ("ability.check.request", "Ability Check Request"),
                    ("ability.check", "Ability Check"),
                    ("ability.check.result", "Ability Check Result"),
                    ("saving.throw.request", "Saving Throw Request"),
                    ("saving.throw", "Saving Throw"),
                    ("saving.throw.result", "Saving Throw Result"),
                    ("combat.initiation", "Combat Initiation"),
                ],
                default="",
                max_length=30,
            ),
            preserve_default=False,
        ),
    ]
