# Generated by Django 5.0.7 on 2024-08-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_remove_combatinitiativerequest_combat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="combatinitiativerequest",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("D", "Done")], default="P", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="combatinitiativeresult",
            name="score",
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
