# Generated by Django 4.1.7 on 2023-02-24 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_alter_narrative_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.game",
            ),
        ),
    ]
