# Generated by Django 5.0.6 on 2024-07-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_remove_combat_game_remove_combat_id_combat_event_ptr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rollrequest",
            name="difficulty_class",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (5, "Very easy"),
                    (10, "Easy"),
                    (15, "Medium"),
                    (20, "Hard"),
                    (25, "Very hard"),
                    (30, "Nearly impossible"),
                ],
                null=True,
            ),
        ),
    ]
