# Generated by Django 4.1.7 on 2023-03-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_damage_healing_xpincrease"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Under preparation"),
                    ("O", "Ongoing"),
                    ("F", "Finished"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
