# Generated by Django 5.2.9 on 2026-01-13 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_initiative_tracking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="turn",
            name="action",
        ),
        migrations.AddField(
            model_name="turn",
            name="action_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="turn",
            name="bonus_action_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="turn",
            name="movement_total",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="turn",
            name="movement_used",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="turn",
            name="reaction_used",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="TurnAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("A", "Action"),
                            ("B", "Bonus Action"),
                            ("R", "Reaction"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("attack", "Attack"),
                            ("cast_spell", "Cast a Spell"),
                            ("dash", "Dash"),
                            ("disengage", "Disengage"),
                            ("dodge", "Dodge"),
                            ("help", "Help"),
                            ("hide", "Hide"),
                            ("ready", "Ready"),
                            ("search", "Search"),
                            ("use_object", "Use an Object"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_fighter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="targeted_by",
                        to="game.fighter",
                    ),
                ),
                (
                    "turn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="game.turn",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActionTaken",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                (
                    "combat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_events",
                        to="game.combat",
                    ),
                ),
                (
                    "fighter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_events",
                        to="game.fighter",
                    ),
                ),
                (
                    "turn_action",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.turnaction",
                    ),
                ),
            ],
            bases=("game.event",),
        ),
    ]
