# Generated by Django 4.2.2 on 2023-07-04 17:43

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_alter_game_name"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                django.db.models.functions.text.Upper("name"),
                name="game_name_upper_idx",
            ),
        ),
    ]
