# Generated by Django 5.0.7 on 2024-07-16 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0005_event_event_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="event_type",
        ),
    ]
