# Generated by Django 4.1.7 on 2023-03-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0005_alter_character_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
