# Generated by Django 5.0.1 on 2024-02-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0005_remove_dicelaunch_character_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="abilitycheckrequest",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("D", "Done")], default="P", max_length=1
            ),
        ),
    ]
