# Generated by Django 5.2.9 on 2026-01-18 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0017_spelleffecttemplate_activespelleffect_and_more"),
        ("game", "0005_action_economy"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpellCast",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                ("slot_level", models.PositiveSmallIntegerField()),
                (
                    "caster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spell_cast_events",
                        to="character.character",
                    ),
                ),
                (
                    "spell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cast_events",
                        to="character.spellsettings",
                    ),
                ),
                (
                    "targets",
                    models.ManyToManyField(
                        related_name="targeted_by_spell_events",
                        to="character.character",
                    ),
                ),
            ],
            bases=("game.event",),
        ),
        migrations.CreateModel(
            name="SpellConditionApplied",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spell_applied_events",
                        to="character.condition",
                    ),
                ),
                (
                    "spell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condition_events",
                        to="character.spellsettings",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spell_condition_events",
                        to="character.character",
                    ),
                ),
            ],
            bases=("game.event",),
        ),
        migrations.CreateModel(
            name="SpellDamageDealt",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                ("damage", models.PositiveIntegerField()),
                ("damage_type", models.CharField(max_length=20)),
                (
                    "spell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="damage_events",
                        to="character.spellsettings",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spell_damage_received_events",
                        to="character.character",
                    ),
                ),
            ],
            bases=("game.event",),
        ),
        migrations.CreateModel(
            name="SpellHealingReceived",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                ("healing", models.PositiveIntegerField()),
                (
                    "spell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="healing_events",
                        to="character.spellsettings",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spell_healing_received_events",
                        to="character.character",
                    ),
                ),
            ],
            bases=("game.event",),
        ),
        migrations.CreateModel(
            name="SpellSavingThrow",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                ("save_type", models.CharField(max_length=5)),
                ("dc", models.PositiveSmallIntegerField()),
                ("roll", models.PositiveSmallIntegerField()),
                ("success", models.BooleanField()),
                (
                    "spell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saving_throw_events",
                        to="character.spellsettings",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spell_save_events",
                        to="character.character",
                    ),
                ),
            ],
            bases=("game.event",),
        ),
    ]
