# Generated by Django 5.0.7 on 2024-08-04 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0005_combatinitiativerequest_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="combatinitiativeresponse",
            name="combat",
        ),
        migrations.RemoveField(
            model_name="combatinitiativeresult",
            name="combat",
        ),
        migrations.AddField(
            model_name="combatinitiativeresponse",
            name="fighter",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.fighter",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="combatinitiativeresult",
            name="fighter",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.fighter",
            ),
            preserve_default=False,
        ),
    ]
