# Generated by Django 4.1.7 on 2023-03-17 18:22

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0005_alter_game_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("P", "Under preparation"),
                    ("O", "Ongoing"),
                    ("F", "Finished"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
