# Generated by Django 4.1.3 on 2022-12-04 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_character_hp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='mp',
        ),
        migrations.AddField(
            model_name='character',
            name='max_hp',
            field=models.SmallIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 15, 55, 23, 969893)),
        ),
    ]
