# Generated by Django 4.2.2 on 2023-07-04 17:45

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0005_game_game_name_upper_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="character",
            index=models.Index(
                django.db.models.functions.text.Upper("name"),
                name="character_name_upper_idx",
            ),
        ),
    ]
