# Generated by Django 4.2.3 on 2023-07-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0005_remove_player_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
