# Generated by Django 5.0.6 on 2024-07-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0006_alter_roll_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="fighter",
            name="dexterity_check",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
