# Generated by Django 4.1.7 on 2023-03-18 07:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0006_alter_game_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="xpincrease",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="game.character",
            ),
            preserve_default=False,
        ),
    ]
