# Generated by Django 4.1.3 on 2022-12-04 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_character_mp_character_max_hp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 15, 55, 34, 550372)),
        ),
    ]
