# Generated by Django 4.1.7 on 2023-03-03 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0006_alter_game_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game.game",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
