# Generated by Django 5.0.1 on 2024-02-02 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0021_skill_description"),
        ("game", "0006_abilitycheckrequest_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbilityCheck",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                ("result", models.BooleanField()),
                (
                    "ability_check_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.abilitycheckrequest",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("game.event",),
        ),
    ]
