# Generated by Django 6.0.1 on 2026-01-31 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0006_spell_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiceRoll",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                ("dice_notation", models.CharField(max_length=20)),
                ("dice_type", models.SmallIntegerField()),
                ("num_dice", models.SmallIntegerField(default=1)),
                ("modifier", models.SmallIntegerField(default=0)),
                ("individual_rolls", models.JSONField()),
                ("total", models.SmallIntegerField()),
                ("roll_purpose", models.CharField(blank=True, max_length=50)),
            ],
            bases=("game.event",),
        ),
    ]
