# Generated by Django 5.1.1 on 2024-09-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0006_combatinitativeorderset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rollrequest",
            name="ability_type",
            field=models.CharField(
                choices=[
                    ("STR", "strength"),
                    ("DEX", "dexterity"),
                    ("CON", "constitution"),
                    ("INT", "intelligence"),
                    ("WIS", "wisdom"),
                    ("CHA", "charisma"),
                ],
                max_length=3,
            ),
        ),
    ]
