# Generated by Django 4.2.3 on 2023-07-09 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master", "0008_alter_story_options_alter_story_main_conflict_and_more"),
        ("game", "0006_character_character_name_upper_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="story",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master.story",
            ),
        ),
    ]
