# Generated by Django 5.0.7 on 2024-07-16 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0066_alter_weaponsettings_damage_and_more"),
        ("game", "0007_gamestart"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterInvitation",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                    ),
                ),
            ],
            bases=("game.event",),
        ),
    ]
