# Generated by Django 5.0.1 on 2024-02-02 07:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0007_abilitycheck"),
    ]

    operations = [
        migrations.RenameField(
            model_name="abilitycheck",
            old_name="ability_check_request",
            new_name="request",
        ),
    ]
