# Generated by Django 4.1.3 on 2022-12-04 16:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_game_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrative',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
