# Generated by Django 6.0.1 on 2026-02-01 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0022_add_temp_hp_and_death_saves"),
        ("game", "0007_dice_roll"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConcentrationBroken",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                ("reason", models.CharField(max_length=100)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concentration_broken_events",
                        to="character.character",
                    ),
                ),
                (
                    "spell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broken_concentration_events",
                        to="character.spellsettings",
                    ),
                ),
            ],
            bases=("game.event",),
        ),
        migrations.CreateModel(
            name="ConcentrationSaveRequired",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                ("damage_taken", models.PositiveSmallIntegerField()),
                ("dc", models.PositiveSmallIntegerField()),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concentration_save_events",
                        to="character.character",
                    ),
                ),
                (
                    "spell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concentration_check_events",
                        to="character.spellsettings",
                    ),
                ),
            ],
            bases=("game.event",),
        ),
        migrations.CreateModel(
            name="ConcentrationSaveResult",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                ("dc", models.PositiveSmallIntegerField()),
                ("roll", models.PositiveSmallIntegerField()),
                ("modifier", models.SmallIntegerField()),
                ("total", models.SmallIntegerField()),
                ("success", models.BooleanField()),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concentration_save_result_events",
                        to="character.character",
                    ),
                ),
                (
                    "spell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concentration_result_events",
                        to="character.spellsettings",
                    ),
                ),
            ],
            bases=("game.event",),
        ),
        migrations.CreateModel(
            name="ConcentrationStarted",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.event",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concentration_started_events",
                        to="character.character",
                    ),
                ),
                (
                    "spell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="started_concentration_events",
                        to="character.spellsettings",
                    ),
                ),
            ],
            bases=("game.event",),
        ),
    ]
