# Generated by Django 4.1.3 on 2022-12-18 12:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_narrative_game_alter_game_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('C', 'Make choice'), ('D', 'Launch dice')], max_length=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.character')),
            ],
        ),
        migrations.CreateModel(
            name='ActionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.character')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(max_length=255)),
                ('action_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.actionresponse')),
            ],
        ),
        migrations.CreateModel(
            name='DiceLaunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField()),
                ('action_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.actionresponse')),
            ],
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='action_required',
        ),
        migrations.AlterField(
            model_name='narrative',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.AddField(
            model_name='actionresponse',
            name='narrative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.narrative'),
        ),
        migrations.AddField(
            model_name='actionrequest',
            name='narrative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.narrative'),
        ),
    ]
