# Generated by Django 4.1.7 on 2023-03-03 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0008_alter_character_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="narrative",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game.game"
            ),
        ),
    ]
