# Generated by Django 4.2.3 on 2023-08-02 19:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0008_instruction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instruction",
            name="pending_action",
        ),
        migrations.RemoveField(
            model_name="instruction",
            name="player",
        ),
    ]
