# Generated by Django 5.0.7 on 2024-07-27 19:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0008_characterinvitation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="message",
        ),
    ]
