# Generated by Django 4.1.7 on 2023-03-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0009_healing_character"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="selection",
            field=models.CharField(max_length=50),
        ),
    ]
