# Generated by Django 4.2.4 on 2023-08-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0009_remove_instruction_pending_action_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="event",
            name="game_event_date_707313_idx",
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["date"], name="game_event_date_779614_idx"),
        ),
    ]
