# Generated by Django 4.1.3 on 2022-12-18 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_actionrequest_actionresponse_choice_dicelaunch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='action_response',
        ),
        migrations.RemoveField(
            model_name='dicelaunch',
            name='action_response',
        ),
        migrations.AddField(
            model_name='choice',
            name='character',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='game.character'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='narrative',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='game.narrative'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dicelaunch',
            name='character',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='game.character'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dicelaunch',
            name='narrative',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='game.narrative'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ActionResponse',
        ),
    ]
