# Generated by Django 4.2.4 on 2023-08-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0010_remove_event_game_event_date_707313_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="event",
            name="game_event_date_779614_idx",
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["-date"], name="game_event_date_707313_idx"),
        ),
    ]
