# Generated by Django 4.1.3 on 2022-12-18 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_choice_action_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicelaunch',
            name='character',
        ),
        migrations.RemoveField(
            model_name='dicelaunch',
            name='narrative',
        ),
        migrations.RemoveField(
            model_name='actionrequest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='actionrequest',
            name='narrative',
        ),
        migrations.AddField(
            model_name='actionrequest',
            name='narrative_ptr',
            field=models.OneToOneField(auto_created=True, default=3, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.narrative'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='DiceLaunch',
        ),
    ]
