# Generated by Django 6.0.2 on 2026-02-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adventure", "0006_migrate_from_master"),
        ("game", "0010_game_campaign_fk_to_adventure"),
    ]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="scene",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quests",
                to="adventure.scene",
            ),
        ),
    ]
