# Generated by Django 4.1.3 on 2022-12-23 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_remove_dicelaunch_character_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiceLaunch',
            fields=[
                ('narrative_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.narrative')),
                ('score', models.SmallIntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.character')),
            ],
            options={
                'abstract': False,
            },
            bases=('game.narrative',),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('narrative_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.narrative')),
                ('selection', models.CharField(max_length=255)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.character')),
            ],
            options={
                'abstract': False,
            },
            bases=('game.narrative',),
        ),
    ]
