# Generated by Django 4.2.4 on 2023-08-06 13:42

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0011_remove_event_game_event_date_779614_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="end_date",
        ),
        migrations.AlterField(
            model_name="game",
            name="status",
            field=django_fsm.FSMField(
                choices=[("P", "Under preparation"), ("O", "Ongoing")],
                default="P",
                max_length=1,
            ),
        ),
    ]
