# Generated by Django 5.0.2 on 2024-02-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0011_rollrequest_against"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rollrequest",
            name="ability_type",
            field=models.CharField(
                choices=[
                    ("STR", "Strength"),
                    ("DEX", "Dexterity"),
                    ("CON", "Constitution"),
                    ("INT", "Intelligence"),
                    ("WIS", "Wisdom"),
                    ("CHA", "Charisma"),
                ],
                max_length=3,
            ),
        ),
    ]
