# Generated by Django 4.2.4 on 2023-08-26 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0012_remove_game_end_date_alter_game_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PendingAction",
        ),
    ]
