# Generated by Django 4.1.3 on 2022-12-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_dicelaunch_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='age',
        ),
    ]
