# Generated by Django 4.2.4 on 2023-08-26 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0013_delete_pendingaction"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tale",
            new_name="Quest",
        ),
    ]
