# Generated by Django 4.2 on 2023-04-06 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0014_alter_game_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingaction",
            name="character",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="game.character"
            ),
        ),
    ]
