# Generated by Django 4.2 on 2023-04-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0015_alter_pendingaction_character"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-date"]},
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["-date"], name="game_event_date_707313_idx"),
        ),
    ]
