# Generated by Django 4.2 on 2023-04-12 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0017_alter_tale_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tale",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="event",
            name="game_event_date_707313_idx",
        ),
    ]
