# Generated by Django 4.2 on 2023-04-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0018_alter_tale_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={},
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["-date"], name="game_event_date_707313_idx"),
        ),
    ]
