# Generated by Django 4.2.1 on 2023-05-05 16:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "game",
            "0001_squashed_0019_alter_event_options_event_game_event_date_707313_idx",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="tale",
            old_name="description",
            new_name="content",
        ),
    ]
