# Generated by Django 4.2.3 on 2023-07-09 20:10

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "race",
                    models.CharField(
                        choices=[
                            ("H", "Human"),
                            ("O", "Orc"),
                            ("E", "Elf"),
                            ("D", "Dwarf"),
                        ],
                        max_length=1,
                    ),
                ),
                ("xp", models.SmallIntegerField(default=0)),
                ("hp", models.SmallIntegerField(default=100)),
                ("max_hp", models.SmallIntegerField(default=100)),
            ],
            options={
                "indexes": [
                    models.Index(
                        django.db.models.functions.text.Upper("name"),
                        name="character_name_upper_idx",
                    )
                ],
            },
        ),
    ]
