# Generated by Django 4.2.5 on 2023-09-10 15:19

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("description", models.TextField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "abilities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Advancement",
            fields=[
                ("xp", models.IntegerField()),
                ("level", models.SmallIntegerField(primary_key=True, serialize=False)),
                ("proficiency_bonus", models.SmallIntegerField()),
            ],
            options={
                "ordering": ["xp"],
            },
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "race",
                    models.CharField(
                        choices=[
                            ("H", "Human"),
                            ("G", "Halfling"),
                            ("E", "Elf"),
                            ("D", "Dwarf"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "class_name",
                    models.CharField(
                        choices=[
                            ("C", "Cleric"),
                            ("F", "Fighter"),
                            ("R", "Rogue"),
                            ("W", "Wizard"),
                        ],
                        max_length=1,
                        verbose_name="class",
                    ),
                ),
                ("level", models.SmallIntegerField(default=1)),
                ("xp", models.IntegerField(default=0)),
                ("hp", models.SmallIntegerField(default=100)),
                ("max_hp", models.SmallIntegerField(default=100)),
                ("proficiency_bonus", models.SmallIntegerField(default=2)),
                ("strength", models.SmallIntegerField(default=0)),
                ("dexterity", models.SmallIntegerField(default=0)),
                ("constitution", models.SmallIntegerField(default=0)),
                ("intelligence", models.SmallIntegerField(default=0)),
                ("wisdom", models.SmallIntegerField(default=0)),
                ("charisma", models.SmallIntegerField(default=0)),
                ("strength_modifier", models.SmallIntegerField(default=0)),
                ("dexterity_modifier", models.SmallIntegerField(default=0)),
                ("constitution_modifier", models.SmallIntegerField(default=0)),
                ("intelligence_modifier", models.SmallIntegerField(default=0)),
                ("wisdom_modifier", models.SmallIntegerField(default=0)),
                ("charisma_modifier", models.SmallIntegerField(default=0)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("U", "Undefined")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("ac", models.SmallIntegerField(default=0)),
                ("adult_age", models.SmallIntegerField(blank=True, null=True)),
                ("life_expectancy", models.SmallIntegerField(blank=True, null=True)),
                (
                    "alignment",
                    models.CharField(
                        blank=True,
                        choices=[("L", "Lawful"), ("F", "Freedom"), ("N", "None")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[("S", "Small"), ("M", "Medium")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("speed", models.SmallIntegerField(blank=True, null=True)),
                ("abilities", models.ManyToManyField(to="character.ability")),
            ],
        ),
        migrations.CreateModel(
            name="ClassAdvancement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_name",
                    models.CharField(
                        choices=[
                            ("C", "Cleric"),
                            ("F", "Fighter"),
                            ("R", "Rogue"),
                            ("W", "Wizard"),
                        ],
                        max_length=1,
                    ),
                ),
                ("level", models.SmallIntegerField(unique=True)),
                ("proficiency_bonus", models.SmallIntegerField()),
            ],
            options={
                "ordering": ["class_name"],
            },
        ),
        migrations.CreateModel(
            name="HitPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hit_dice", models.CharField(max_length=5)),
                ("hit_points_first_level", models.CharField(max_length=20)),
                ("hit_points_higher_levels", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("C", "Common"),
                            ("D", "Dwarvish"),
                            ("E", "Elvish"),
                            ("H", "Halfling"),
                        ],
                        max_length=1,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proficiency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("armor", models.TextField(max_length=50)),
                ("weapons", models.TextField(max_length=50)),
                ("tools", models.TextField(max_length=50)),
                ("saving_throws", models.TextField(max_length=50)),
                ("skills", models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="RacialTrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "race",
                    models.CharField(
                        choices=[
                            ("H", "Human"),
                            ("G", "Halfling"),
                            ("E", "Elf"),
                            ("D", "Dwarf"),
                        ],
                        max_length=1,
                        unique=True,
                    ),
                ),
                ("adult_age", models.SmallIntegerField()),
                ("life_expectancy", models.SmallIntegerField()),
                (
                    "alignment",
                    models.CharField(
                        choices=[("L", "Lawful"), ("F", "Freedom"), ("N", "None")],
                        max_length=1,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[("S", "Small"), ("M", "Medium")], max_length=1
                    ),
                ),
                ("speed", models.SmallIntegerField()),
                ("abilities", models.ManyToManyField(to="character.ability")),
                ("languages", models.ManyToManyField(to="character.language")),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacity", models.SmallIntegerField(default=0)),
                ("gp", models.SmallIntegerField(default=0)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("weight", models.SmallIntegerField()),
                (
                    "inventory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="character.inventory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClassFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_name",
                    models.CharField(
                        choices=[
                            ("C", "Cleric"),
                            ("F", "Fighter"),
                            ("R", "Rogue"),
                            ("W", "Wizard"),
                        ],
                        max_length=1,
                        unique=True,
                    ),
                ),
                ("equipment", models.ManyToManyField(to="character.equipment")),
                ("hit_points", models.ManyToManyField(to="character.hitpoint")),
                ("proficiencies", models.ManyToManyField(to="character.proficiency")),
            ],
        ),
        migrations.AddField(
            model_name="character",
            name="languages",
            field=models.ManyToManyField(to="character.language"),
        ),
        migrations.AddField(
            model_name="character",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="AbilityScoreIncrease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ability",
                    models.CharField(
                        choices=[
                            ("strength", "Strength"),
                            ("dexterity", "Dexterity"),
                            ("constitution", "Constitution"),
                            ("intelligence", "Intelligence"),
                            ("wisdom", "Wisdom"),
                            ("charisma", "Charisma"),
                        ],
                        max_length=20,
                    ),
                ),
                ("increase", models.SmallIntegerField()),
                (
                    "racial_trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.racialtrait",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(
                django.db.models.functions.text.Upper("name"),
                name="character_name_upper_idx",
            ),
        ),
    ]
