# Generated by Django 4.2.5 on 2023-10-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentPack",
            fields=[
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Burglar's Pack", "Burglars Pack"),
                            ("Diplomat's Pack", "Diplomats Pack"),
                            ("Dungeoneer's Pack", "Dungeoneers Pack"),
                            ("Entertainer's Pack", "Entertainers Pack"),
                            ("Explorer's Pack", "Explorers Pack"),
                            ("Priest's Pack", "Priests Pack"),
                            ("Scholar's Pack", "Scholars Pack"),
                        ],
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
    ]
