# Generated by Django 4.2.5 on 2023-09-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classadvancement",
            name="level",
            field=models.SmallIntegerField(),
        ),
    ]
