# Generated by Django 5.0.8 on 2024-08-14 17:43

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("character", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="attackrolldisadvantage",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="character.character"
            ),
        ),
        migrations.AddField(
            model_name="armorproficiency",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="character.character"
            ),
        ),
        migrations.AddField(
            model_name="abilitycheckdisadvantage",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="character.character"
            ),
        ),
        migrations.AddField(
            model_name="gear",
            name="settings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="character.gearsettings"
            ),
        ),
        migrations.AddField(
            model_name="gear",
            name="inventory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="character.inventory",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="inventory",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="character.inventory",
            ),
        ),
        migrations.AddField(
            model_name="armor",
            name="inventory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="character.inventory",
            ),
        ),
        migrations.AddField(
            model_name="hitpoints",
            name="klass_feature",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="character.klassfeature",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="languages",
            field=models.ManyToManyField(to="character.language"),
        ),
        migrations.AddField(
            model_name="pack",
            name="inventory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="character.inventory",
            ),
        ),
        migrations.AddField(
            model_name="pack",
            name="settings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="character.packsettings"
            ),
        ),
        migrations.AddField(
            model_name="savingthrowdisadvantage",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="character.character"
            ),
        ),
        migrations.AddField(
            model_name="savingthrowproficiency",
            name="ability_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="character.abilitytype"
            ),
        ),
        migrations.AddField(
            model_name="savingthrowproficiency",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="character.character"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="senses",
            field=models.ManyToManyField(to="character.sense"),
        ),
        migrations.AddField(
            model_name="skill",
            name="ability_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="character.abilitytype"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="skills",
            field=models.ManyToManyField(to="character.skill"),
        ),
        migrations.AddField(
            model_name="skillproficiency",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="character.character"
            ),
        ),
        migrations.AddField(
            model_name="skillproficiency",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="character.skill"
            ),
        ),
        migrations.AddField(
            model_name="spellcastdisadvantage",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="character.character"
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="inventory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="character.inventory",
            ),
        ),
        migrations.AddField(
            model_name="toolproficiency",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="character.character"
            ),
        ),
        migrations.AddField(
            model_name="toolproficiency",
            name="tool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="character.toolsettings"
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="settings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="character.toolsettings"
            ),
        ),
        migrations.AddField(
            model_name="weapon",
            name="inventory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="character.inventory",
            ),
        ),
        migrations.AddField(
            model_name="weaponproficiency",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="character.character"
            ),
        ),
        migrations.AddField(
            model_name="weaponproficiency",
            name="weapon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="character.weaponsettings",
            ),
        ),
        migrations.AddField(
            model_name="weapon",
            name="settings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="character.weaponsettings",
            ),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(
                django.db.models.functions.text.Upper("name"),
                name="character_name_upper_idx",
            ),
        ),
    ]
