# Generated by Django 4.2.4 on 2023-08-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0002_character_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="race",
            field=models.CharField(
                choices=[
                    ("H", "Human"),
                    ("G", "Halfling"),
                    ("E", "Elf"),
                    ("D", "Dwarf"),
                ],
                max_length=1,
            ),
        ),
    ]
