# Generated by Django 4.2.5 on 2023-09-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0002_alter_classadvancement_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classfeature",
            name="hit_points",
        ),
        migrations.AddField(
            model_name="classfeature",
            name="hit_dice",
            field=models.CharField(default="1d8", max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classfeature",
            name="hp_first_level",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classfeature",
            name="hp_higher_levels",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="HitPoint",
        ),
    ]
