# Generated by Django 4.2.4 on 2023-08-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0003_alter_character_race"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="level",
            field=models.SmallIntegerField(default=1),
        ),
    ]
