# Generated by Django 4.2.5 on 2023-09-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "character",
            "0003_remove_classfeature_hit_points_classfeature_hit_dice_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="classfeature",
            name="hp_first_level",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="classfeature",
            name="hp_higher_levels",
            field=models.SmallIntegerField(),
        ),
    ]
