# Generated by Django 5.1.1 on 2024-09-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0003_character_creation_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="creation_state",
        ),
        migrations.AlterField(
            model_name="abilitytype",
            name="name",
            field=models.CharField(
                choices=[
                    ("STR", "strength"),
                    ("DEX", "dexterity"),
                    ("CON", "constitution"),
                    ("INT", "intelligence"),
                    ("WIS", "wisdom"),
                    ("CHA", "charisma"),
                ],
                max_length=3,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
