# Generated by Django 5.1.4 on 2024-12-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0004_remove_character_creation_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolsettings",
            name="name",
            field=models.CharField(
                choices=[
                    ("alchemists_supplies", "Alchemist's supplies"),
                    ("brewers_supplies", "Brewer's supplies"),
                    ("calligraphers_supplies", "Calligrapher's supplies"),
                    ("carpenters_tools", "Carpenter's tools"),
                    ("cartographers_tools", "Cartographer's tools"),
                    ("cobblers_tools", "Cobbler's tools"),
                    ("cooks_utensils", "Cook's utensils"),
                    ("glassblowers_tools", "Glassblower's tools"),
                    ("jewelers_tools", "Jeweler's tools"),
                    ("leatherworkers_tools", "Leatherworker's tools"),
                    ("masons_tools", "Mason's tools"),
                    ("painters_supplies", "Painter's supplies"),
                    ("potters_tools", "Potter's tools"),
                    ("smiths_tools", "Smith's tools"),
                    ("tinkers_tools", "Tinker's tools"),
                    ("weavers_tools", "Weaver's tools"),
                    ("woodcarvers_tools", "Woodcarver's tools"),
                    ("disguise_kit", "Disguise kit"),
                    ("forgery_kit", "Forgery kit"),
                    ("dice_set", "Dice set"),
                    ("dragonchess_set", "Dragonchess set"),
                    ("playing_card_set", "Playing card set"),
                    ("three_dragon_ante_set", "Three-Dragon Ante set"),
                    ("herbalism_kit", "Herbalism kit"),
                    ("bagpipes", "Bagpipes"),
                    ("drum", "Drum"),
                    ("dulcimer", "Dulcimer"),
                    ("flute", "Flute"),
                    ("lute", "Lute"),
                    ("lyre", "Lyre"),
                    ("horn", "Horn"),
                    ("pan_flute", "Pan flute"),
                    ("shawm", "Shawm"),
                    ("viol", "Viol"),
                    ("navigators_tools", "Navigator's tools"),
                    ("poisoners_kit", "Poisoner's kit"),
                    ("thieves_tools", "Thieves' tools"),
                ],
                max_length=30,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
