# Generated by Django 4.2.5 on 2023-09-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0004_alter_classfeature_hp_first_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="hit_dice",
            field=models.CharField(default="1d8", max_length=5),
        ),
    ]
