# Generated by Django 4.2.6 on 2023-10-11 20:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0004_rename_adventuringgear_gear"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EquipmentPack",
            new_name="Pack",
        ),
    ]
