# Generated by Django 4.2.4 on 2023-08-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0004_character_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="proficiency_bonus",
            field=models.SmallIntegerField(default=2),
        ),
    ]
