# Generated by Django 4.2.5 on 2023-09-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0005_character_hit_dice"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="hp_increase",
            field=models.SmallIntegerField(default=0),
        ),
    ]
