# Generated by Django 4.2.4 on 2023-08-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0005_character_proficiency_bonus"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="class_name",
            field=models.CharField(
                choices=[("F", "Fighter")], default="F", max_length=1
            ),
            preserve_default=False,
        ),
    ]
