# Generated by Django 5.2.8 on 2026-01-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0006_alter_character_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abilitytype",
            name="name",
            field=models.CharField(
                choices=[
                    ("STR", "Strength"),
                    ("DEX", "Dexterity"),
                    ("CON", "Constitution"),
                    ("INT", "Intelligence"),
                    ("WIS", "Wisdom"),
                    ("CHA", "Charisma"),
                ],
                max_length=3,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
