# Generated by Django 5.1.5 on 2025-01-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0006_alter_character_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="portrait",
            field=models.ImageField(blank=True, null=True, upload_to="portraits/"),
        ),
    ]
