# Generated by Django 5.2.9 on 2026-01-10 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0007_alter_abilitytype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ability",
            name="modifier",
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="ability",
            name="score",
            field=models.SmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ]
            ),
        ),
    ]
