# Generated by Django 5.0.1 on 2024-01-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0007_remove_tool_id_tool_name_tool_tool_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Athletics", "Athletics"),
                            ("Acrobatics", "Acrobatics"),
                            ("Sleight of Hand", "Sleight Of Hand"),
                            ("Stealth", "Stealth"),
                            ("Arcana", "Arcana"),
                            ("History", "History"),
                            ("Investigation", "Investigation"),
                            ("Nature", "Nature"),
                            ("Religion", "Religion"),
                            ("Animal Handling", "Animal Handling"),
                            ("Insight", "Insight"),
                            ("Medicine", "Medicine"),
                            ("Perception", "Perception"),
                            ("Survival", "Survival"),
                            ("Deception", "Deception"),
                            ("Intimidation", "Intimidation"),
                            ("Performance", "Performance"),
                            ("Persuasion", "Persuasion"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
