# Generated by Django 4.2.4 on 2023-08-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0007_character_charisma_character_constitution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("U", "Undefined")],
                default="M",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="class_name",
            field=models.CharField(
                choices=[("F", "Fighter")], max_length=1, verbose_name="class"
            ),
        ),
    ]
