# Generated by Django 5.0.1 on 2024-01-12 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0007_remove_tool_id_tool_name_tool_tool_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("description", models.TextField(max_length=50)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="ability",
            options={"verbose_name_plural": "abilities"},
        ),
        migrations.RemoveField(
            model_name="ability",
            name="description",
        ),
        migrations.RemoveField(
            model_name="ability",
            name="id",
        ),
        migrations.RemoveField(
            model_name="character",
            name="abilities",
        ),
        migrations.RemoveField(
            model_name="racialtrait",
            name="abilities",
        ),
        migrations.AlterField(
            model_name="ability",
            name="name",
            field=models.CharField(
                choices=[
                    ("STR", "Strength"),
                    ("DEX", "Dexterity"),
                    ("CON", "Constitution"),
                    ("INT", "Intelligence"),
                    ("WIS", "Wisdom"),
                    ("CHA", "Charisma"),
                ],
                max_length=3,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="senses",
            field=models.ManyToManyField(to="character.sense"),
        ),
        migrations.AddField(
            model_name="racialtrait",
            name="senses",
            field=models.ManyToManyField(to="character.sense"),
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Athletics", "Athletics"),
                            ("Acrobatics", "Acrobatics"),
                            ("Sleight of Hand", "Sleight Of Hand"),
                            ("Stealth", "Stealth"),
                            ("Arcana", "Arcana"),
                            ("History", "History"),
                            ("Investigation", "Investigation"),
                            ("Nature", "Nature"),
                            ("Religion", "Religion"),
                            ("Animal Handling", "Animal Handling"),
                            ("Insight", "Insight"),
                            ("Medicine", "Medicine"),
                            ("Perception", "Perception"),
                            ("Survival", "Survival"),
                            ("Deception", "Deception"),
                            ("Intimidation", "Intimidation"),
                            ("Performance", "Performance"),
                            ("Persuasion", "Persuasion"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "ability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.ability",
                    ),
                ),
            ],
        ),
    ]
