# Generated by Django 5.0.1 on 2024-01-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0008_skill"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("description", models.TextField(max_length=50)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="ability",
            options={"verbose_name_plural": "abilities"},
        ),
        migrations.RemoveField(
            model_name="ability",
            name="description",
        ),
        migrations.AddField(
            model_name="ability",
            name="modifier",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ability",
            name="name",
            field=models.CharField(
                choices=[
                    ("STR", "Strength"),
                    ("DEX", "Dexterity"),
                    ("CON", "Constitution"),
                    ("INT", "Intelligence"),
                    ("WIS", "Wisdom"),
                    ("CHA", "Charisma"),
                ],
                max_length=3,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="racialtrait",
            name="abilities",
            field=models.ManyToManyField(to="character.sense"),
        ),
    ]
