# Generated by Django 5.0.1 on 2024-01-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0008_sense_alter_ability_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="id",
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(
                choices=[
                    ("Athletics", "Athletics"),
                    ("Acrobatics", "Acrobatics"),
                    ("Sleight of Hand", "Sleight Of Hand"),
                    ("Stealth", "Stealth"),
                    ("Arcana", "Arcana"),
                    ("History", "History"),
                    ("Investigation", "Investigation"),
                    ("Nature", "Nature"),
                    ("Religion", "Religion"),
                    ("Animal Handling", "Animal Handling"),
                    ("Insight", "Insight"),
                    ("Medicine", "Medicine"),
                    ("Perception", "Perception"),
                    ("Survival", "Survival"),
                    ("Deception", "Deception"),
                    ("Intimidation", "Intimidation"),
                    ("Performance", "Performance"),
                    ("Persuasion", "Persuasion"),
                ],
                max_length=20,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
