# Generated by Django 5.2.9 on 2026-01-10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0008_alter_ability_modifier_alter_ability_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="proficiency_bonus",
        ),
    ]
