# Generated by Django 4.2.5 on 2023-09-22 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0008_remove_proficiency_class_feature_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="proficiencies",
        ),
        migrations.RemoveField(
            model_name="classfeature",
            name="proficiencies",
        ),
        migrations.AddField(
            model_name="proficiency",
            name="character",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="character.character",
            ),
        ),
        migrations.AddField(
            model_name="proficiency",
            name="class_feature",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="character.classfeature",
            ),
        ),
    ]
