# Generated by Django 4.2.5 on 2023-09-22 21:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0009_remove_character_proficiencies_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Proficiency",
            new_name="Proficiencies",
        ),
        migrations.AlterModelOptions(
            name="proficiencies",
            options={},
        ),
    ]
