# Generated by Django 5.0.1 on 2024-01-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0009_remove_skill_id_alter_skill_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="skills",
            field=models.ManyToManyField(to="character.skill"),
        ),
    ]
