# Generated by Django 5.0.1 on 2024-01-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0009_sense_alter_ability_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="abilities",
        ),
        migrations.AddField(
            model_name="character",
            name="senses",
            field=models.ManyToManyField(to="character.sense"),
        ),
    ]
