# Generated by Django 5.2.9 on 2026-01-10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0009_remove_character_proficiency_bonus"),
    ]

    operations = [
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("blinded", "Blinded"),
                            ("charmed", "Charmed"),
                            ("deafened", "Deafened"),
                            ("exhaustion", "Exhaustion"),
                            ("frightened", "Frightened"),
                            ("grappled", "Grappled"),
                            ("incapacitated", "Incapacitated"),
                            ("invisible", "Invisible"),
                            ("paralyzed", "Paralyzed"),
                            ("petrified", "Petrified"),
                            ("poisoned", "Poisoned"),
                            ("prone", "Prone"),
                            ("restrained", "Restrained"),
                            ("stunned", "Stunned"),
                            ("unconscious", "Unconscious"),
                        ],
                        max_length=15,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField(max_length=1000)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CharacterCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exhaustion_level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_conditions",
                        to="character.character",
                    ),
                ),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.condition",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "character conditions",
                "unique_together": {("character", "condition")},
            },
        ),
    ]
