# Generated by Django 5.0.1 on 2024-01-12 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0010_remove_character_abilities_character_senses"),
    ]

    operations = [
        migrations.RenameField(
            model_name="racialtrait",
            old_name="abilities",
            new_name="senses",
        ),
    ]
