# Generated by Django 5.0.1 on 2024-01-14 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0010_character_skills"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbilityScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.SmallIntegerField()),
                ("modifier", models.SmallIntegerField()),
                (
                    "ability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.ability",
                    ),
                ),
            ],
        ),
    ]
