# Generated by Django 5.2.9 on 2026-01-10 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0010_condition_charactercondition"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeciesTrait",
            fields=[
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("dwarven_resilience", "Dwarven Resilience"),
                            ("dwarven_toughness", "Dwarven Toughness"),
                            ("stonecunning", "Stonecunning"),
                            ("fey_ancestry", "Fey Ancestry"),
                            ("keen_senses", "Keen Senses"),
                            ("trance", "Trance"),
                            ("brave", "Brave"),
                            ("halfling_nimbleness", "Halfling Nimbleness"),
                            ("lucky", "Lucky"),
                            ("resourceful", "Resourceful"),
                            ("skillful", "Skillful"),
                            ("versatile", "Versatile"),
                        ],
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField(max_length=500)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="character",
            name="senses",
        ),
        migrations.RemoveField(
            model_name="character",
            name="adult_age",
        ),
        migrations.RemoveField(
            model_name="character",
            name="alignment",
        ),
        migrations.RemoveField(
            model_name="character",
            name="life_expectancy",
        ),
        migrations.RemoveField(
            model_name="character",
            name="race",
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("dwarf", "Dwarf"),
                            ("elf", "Elf"),
                            ("halfling", "Halfling"),
                            ("human", "Human"),
                        ],
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[("S", "Small"), ("M", "Medium")], max_length=1
                    ),
                ),
                ("speed", models.PositiveSmallIntegerField(default=30)),
                ("darkvision", models.PositiveSmallIntegerField(default=0)),
                ("description", models.TextField(blank=True, max_length=1000)),
                ("languages", models.ManyToManyField(to="character.language")),
                ("traits", models.ManyToManyField(to="character.speciestrait")),
            ],
            options={
                "verbose_name_plural": "species",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="character",
            name="species",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="character.species",
            ),
        ),
        migrations.DeleteModel(
            name="Sense",
        ),
    ]
