# Generated by Django 5.2.9 on 2026-01-10 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0011_speciestrait_remove_character_senses_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feat",
            fields=[
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("alert", "Alert"),
                            ("magic_initiate_cleric", "Magic Initiate (Cleric)"),
                            ("magic_initiate_wizard", "Magic Initiate (Wizard)"),
                            ("savage_attacker", "Savage Attacker"),
                        ],
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feat_type",
                    models.CharField(
                        choices=[("O", "Origin"), ("G", "General")], max_length=1
                    ),
                ),
                ("description", models.TextField(max_length=1000)),
                ("prerequisite", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="character",
            name="background",
            field=models.CharField(
                choices=[
                    ("acolyte", "Acolyte"),
                    ("criminal", "Criminal"),
                    ("sage", "Sage"),
                    ("soldier", "Soldier"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="CharacterFeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("granted_by", models.CharField(blank=True, max_length=20)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_feats",
                        to="character.character",
                    ),
                ),
                (
                    "feat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="character.feat"
                    ),
                ),
            ],
            options={
                "unique_together": {("character", "feat")},
            },
        ),
        migrations.AddField(
            model_name="character",
            name="feats",
            field=models.ManyToManyField(
                blank=True, through="character.CharacterFeat", to="character.feat"
            ),
        ),
    ]
