# Generated by Django 5.0.1 on 2024-01-12 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0011_rename_abilities_racialtrait_senses"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="ability",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="character.ability",
            ),
            preserve_default=False,
        ),
    ]
