# Generated by Django 5.0.1 on 2024-01-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0012_remove_character_charisma_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abilityscore",
            name="modifier",
            field=models.SmallIntegerField(default=0),
        ),
    ]
