# Generated by Django 4.2.4 on 2023-08-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0012_advancement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advancement",
            name="xp",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="character",
            name="xp",
            field=models.IntegerField(default=0),
        ),
    ]
