# Generated by Django 5.2.9 on 2026-01-11 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0012_add_feat_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("cleric", "Cleric"),
                            ("fighter", "Fighter"),
                            ("rogue", "Rogue"),
                            ("wizard", "Wizard"),
                        ],
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=1000)),
                ("hit_die", models.PositiveSmallIntegerField()),
                ("hp_first_level", models.PositiveSmallIntegerField()),
                ("hp_higher_levels", models.PositiveSmallIntegerField()),
                ("armor_proficiencies", models.JSONField(default=list)),
                ("weapon_proficiencies", models.JSONField(default=list)),
                ("starting_wealth_dice", models.CharField(max_length=10)),
                (
                    "primary_ability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_for_classes",
                        to="character.abilitytype",
                    ),
                ),
                (
                    "saving_throws",
                    models.ManyToManyField(
                        related_name="classes_proficient", to="character.abilitytype"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "classes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CharacterClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveSmallIntegerField(default=1)),
                ("is_primary", models.BooleanField(default=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_classes",
                        to="character.character",
                    ),
                ),
                (
                    "klass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="character.class",
                    ),
                ),
            ],
            options={
                "unique_together": {("character", "klass")},
            },
        ),
        migrations.AddField(
            model_name="character",
            name="classes",
            field=models.ManyToManyField(
                related_name="characters",
                through="character.CharacterClass",
                to="character.class",
            ),
        ),
        migrations.CreateModel(
            name="ClassFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("level", models.PositiveSmallIntegerField()),
                ("description", models.TextField(max_length=2000)),
                (
                    "klass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="character.class",
                    ),
                ),
            ],
            options={
                "ordering": ["klass", "level", "name"],
                "unique_together": {("klass", "name")},
            },
        ),
    ]
