# Generated by Django 5.0.1 on 2024-01-19 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0013_alter_abilityscore_modifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abilityscoreincrease",
            name="ability",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="character.ability"
            ),
        ),
    ]
