# Generated by Django 4.2.5 on 2023-09-26 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0013_remove_classfeature_hit_dice_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hitpoints",
            options={"verbose_name_plural": "hitpoints"},
        ),
    ]
