# Generated by Django 5.2.9 on 2026-01-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0013_class_characterclass_character_classes_classfeature"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hitpoints",
            name="klass_feature",
        ),
        migrations.DeleteModel(
            name="KlassAdvancement",
        ),
        migrations.RemoveField(
            model_name="character",
            name="klass",
        ),
        migrations.AlterField(
            model_name="class",
            name="name",
            field=models.CharField(
                choices=[
                    ("barbarian", "Barbarian"),
                    ("bard", "Bard"),
                    ("cleric", "Cleric"),
                    ("druid", "Druid"),
                    ("fighter", "Fighter"),
                    ("monk", "Monk"),
                    ("paladin", "Paladin"),
                    ("ranger", "Ranger"),
                    ("rogue", "Rogue"),
                    ("sorcerer", "Sorcerer"),
                    ("warlock", "Warlock"),
                    ("wizard", "Wizard"),
                ],
                max_length=20,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.DeleteModel(
            name="HitPoints",
        ),
        migrations.DeleteModel(
            name="KlassFeature",
        ),
    ]
