# Generated by Django 5.0.1 on 2024-01-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0014_alter_abilityscoreincrease_ability"),
    ]

    operations = [
        migrations.AddField(
            model_name="ability",
            name="description",
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
