# Generated by Django 5.2.9 on 2026-01-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0014_harmonize_class_naming"),
    ]

    operations = [
        migrations.AddField(
            model_name="weaponsettings",
            name="mastery",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cleave", "Cleave"),
                    ("graze", "Graze"),
                    ("nick", "Nick"),
                    ("push", "Push"),
                    ("sap", "Sap"),
                    ("slow", "Slow"),
                    ("topple", "Topple"),
                    ("vex", "Vex"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
