# Generated by Django 4.2.4 on 2023-09-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0014_racialtrait"),
    ]

    operations = [
        migrations.AlterField(
            model_name="racialtrait",
            name="size",
            field=models.CharField(
                choices=[("S", "Small"), ("M", "Medium")], max_length=1
            ),
        ),
    ]
