# Generated by Django 4.2.4 on 2023-09-03 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0015_alter_racialtrait_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("C", "Common"),
                            ("D", "Dwarvish"),
                            ("E", "Elvish"),
                            ("H", "Halfling"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "racial_trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.racialtrait",
                    ),
                ),
            ],
        ),
    ]
