# Generated by Django 5.0.1 on 2024-01-19 19:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0015_ability_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ability",
            new_name="AbilityType",
        ),
        migrations.AlterModelOptions(
            name="abilitytype",
            options={},
        ),
    ]
