# Generated by Django 5.2.9 on 2026-01-18 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0016_spellsettings_classspellcasting_concentration_and_more"),
        ("game", "0005_action_economy"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpellEffectTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "effect_type",
                    models.CharField(
                        choices=[
                            ("damage", "Damage"),
                            ("healing", "Healing"),
                            ("condition", "Condition"),
                            ("buff", "Buff"),
                            ("debuff", "Debuff"),
                            ("summon", "Summon"),
                            ("utility", "Utility"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("self", "Self"),
                            ("single", "Single Target"),
                            ("multiple", "Multiple Targets"),
                            ("area", "Area"),
                            ("line", "Line"),
                            ("cone", "Cone"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "damage_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("acid", "Acid"),
                            ("bludgeoning", "Bludgeoning"),
                            ("cold", "Cold"),
                            ("fire", "Fire"),
                            ("force", "Force"),
                            ("lightning", "Lightning"),
                            ("necrotic", "Necrotic"),
                            ("piercing", "Piercing"),
                            ("poison", "Poison"),
                            ("psychic", "Psychic"),
                            ("radiant", "Radiant"),
                            ("slashing", "Slashing"),
                            ("thunder", "Thunder"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "base_dice",
                    models.CharField(
                        blank=True,
                        help_text="Base damage/healing dice (e.g., '8d6')",
                        max_length=20,
                    ),
                ),
                (
                    "dice_per_level",
                    models.CharField(
                        blank=True,
                        help_text="Additional dice per spell level above base (e.g., '1d6')",
                        max_length=20,
                    ),
                ),
                (
                    "save_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("STR", "Strength"),
                            ("DEX", "Dexterity"),
                            ("CON", "Constitution"),
                            ("INT", "Intelligence"),
                            ("WIS", "Wisdom"),
                            ("CHA", "Charisma"),
                        ],
                        default="none",
                        max_length=5,
                    ),
                ),
                (
                    "save_effect",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("half_damage", "Half Damage"),
                            ("negates", "Negates"),
                        ],
                        default="none",
                        max_length=15,
                    ),
                ),
                (
                    "buff_description",
                    models.TextField(
                        blank=True, help_text="Description of the buff/debuff effect"
                    ),
                ),
                (
                    "ac_modifier",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Modifier to AC (positive for buff, negative for debuff)",
                    ),
                ),
                (
                    "attack_modifier",
                    models.SmallIntegerField(
                        default=0, help_text="Modifier to attack rolls"
                    ),
                ),
                (
                    "damage_modifier",
                    models.SmallIntegerField(
                        default=0, help_text="Modifier to damage rolls"
                    ),
                ),
                (
                    "area_radius",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Radius in feet (0 for non-area effects)"
                    ),
                ),
                (
                    "area_shape",
                    models.CharField(
                        blank=True,
                        help_text="Shape of area (sphere, cube, cone, line)",
                        max_length=20,
                    ),
                ),
                (
                    "duration_type",
                    models.CharField(
                        choices=[
                            ("instantaneous", "Instantaneous"),
                            ("rounds", "Rounds"),
                            ("minutes", "Minutes"),
                            ("hours", "Hours"),
                            ("until_dispelled", "Until Dispelled"),
                            ("concentration", "Concentration"),
                        ],
                        default="instantaneous",
                        max_length=20,
                    ),
                ),
                (
                    "duration_value",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Duration value (number of rounds, minutes, hours, etc.)",
                    ),
                ),
                (
                    "condition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Condition applied by this effect",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="character.condition",
                    ),
                ),
                (
                    "spell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effect_templates",
                        to="character.spellsettings",
                    ),
                ),
            ],
            options={
                "ordering": ["spell", "effect_type"],
            },
        ),
        migrations.CreateModel(
            name="ActiveSpellEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rounds_remaining",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Rounds remaining (null for non-round durations)",
                        null=True,
                    ),
                ),
                (
                    "is_concentration",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this effect requires concentration",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "caster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cast_effects",
                        to="character.character",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_spell_effects",
                        to="character.character",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.spelleffecttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SummonedCreature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("hp_current", models.PositiveIntegerField()),
                ("hp_max", models.PositiveIntegerField()),
                ("ac", models.PositiveSmallIntegerField()),
                (
                    "rounds_remaining",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Rounds remaining (null for non-round durations)",
                        null=True,
                    ),
                ),
                (
                    "is_concentration",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this summon requires concentration",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "combat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summoned_creatures",
                        to="game.combat",
                    ),
                ),
                (
                    "spell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.spellsettings",
                    ),
                ),
                (
                    "summoner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summoned_creatures",
                        to="character.character",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
