# Generated by Django 4.2.5 on 2023-09-26 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0016_alter_hitpoints_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proficiencies",
            options={"verbose_name_plural": "proficiencies"},
        ),
    ]
