# Generated by Django 4.2.4 on 2023-09-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0016_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="language",
            name="racial_trait",
        ),
        migrations.AddField(
            model_name="racialtrait",
            name="languages",
            field=models.ManyToManyField(to="character.language"),
        ),
    ]
