# Generated by Django 5.0.1 on 2024-01-19 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0016_rename_ability_abilitytype_alter_abilitytype_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AbilityScore",
            new_name="Ability",
        ),
        migrations.RenameField(
            model_name="ability",
            old_name="ability",
            new_name="ability_type",
        ),
    ]
