# Generated by Django 4.2.4 on 2023-09-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0017_remove_language_racial_trait_racialtrait_languages"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("description", models.TextField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="racialtrait",
            name="abilities",
            field=models.ManyToManyField(to="character.ability"),
        ),
    ]
