# Generated by Django 4.2.5 on 2023-10-01 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0017_alter_proficiencies_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="weight",
        ),
    ]
