# Generated by Django 5.2.9 on 2026-01-19 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0017_spelleffecttemplate_activespelleffect_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MagicItemSettings",
            fields=[
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Weapon +1", "Weapon Plus 1"),
                            ("Weapon +2", "Weapon Plus 2"),
                            ("Weapon +3", "Weapon Plus 3"),
                            ("Armor +1", "Armor Plus 1"),
                            ("Armor +2", "Armor Plus 2"),
                            ("Armor +3", "Armor Plus 3"),
                            ("Shield +1", "Shield Plus 1"),
                            ("Shield +2", "Shield Plus 2"),
                            ("Shield +3", "Shield Plus 3"),
                            ("Potion of Healing", "Potion Of Healing"),
                            ("Potion of Greater Healing", "Potion Of Greater Healing"),
                            (
                                "Potion of Superior Healing",
                                "Potion Of Superior Healing",
                            ),
                            ("Potion of Supreme Healing", "Potion Of Supreme Healing"),
                            ("Wand of Magic Missiles", "Wand Of Magic Missiles"),
                            ("Wand of the War Mage +1", "Wand Of The War Mage Plus 1"),
                            ("Wand of the War Mage +2", "Wand Of The War Mage Plus 2"),
                            ("Wand of the War Mage +3", "Wand Of The War Mage Plus 3"),
                            ("Staff of the Magi", "Staff Of The Magi"),
                            ("Staff of Power", "Staff Of Power"),
                            ("Staff of Healing", "Staff Of Healing"),
                            ("Staff of the Woodlands", "Staff Of The Woodlands"),
                            ("Ring of Protection", "Ring Of Protection"),
                            ("Ring of Spell Storing", "Ring Of Spell Storing"),
                            ("Amulet of Health", "Amulet Of Health"),
                            ("Bag of Holding", "Bag Of Holding"),
                            ("Boots of Elvenkind", "Boots Of Elvenkind"),
                            ("Boots of Speed", "Boots Of Speed"),
                            ("Bracers of Defense", "Bracers Of Defense"),
                            ("Cloak of Elvenkind", "Cloak Of Elvenkind"),
                            ("Cloak of Protection", "Cloak Of Protection"),
                            ("Gauntlets of Ogre Power", "Gauntlets Of Ogre Power"),
                            ("Headband of Intellect", "Headband Of Intellect"),
                            ("Pearl of Power", "Pearl Of Power"),
                        ],
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("armor", "Armor"),
                            ("potion", "Potion"),
                            ("ring", "Ring"),
                            ("rod", "Rod"),
                            ("scroll", "Scroll"),
                            ("staff", "Staff"),
                            ("wand", "Wand"),
                            ("weapon", "Weapon"),
                            ("wondrous", "Wondrous Item"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("uncommon", "Uncommon"),
                            ("rare", "Rare"),
                            ("very_rare", "Very Rare"),
                            ("legendary", "Legendary"),
                        ],
                        max_length=15,
                    ),
                ),
                ("requires_attunement", models.BooleanField(default=False)),
                (
                    "attunement_requirement",
                    models.CharField(
                        blank=True,
                        help_text="E.g., 'by a spellcaster', 'by a cleric or paladin'",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(max_length=2000)),
                (
                    "bonus",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("+1", "+1"),
                            ("+2", "+2"),
                            ("+3", "+3"),
                            ("+1", "+1"),
                            ("+2", "+2"),
                            ("+3", "+3"),
                        ],
                        max_length=2,
                    ),
                ),
                ("effects", models.JSONField(blank=True, default=dict)),
                ("is_consumable", models.BooleanField(default=False)),
                ("weight", models.PositiveSmallIntegerField(default=0)),
                ("cost", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "magic item settings",
                "verbose_name_plural": "magic item settings",
                "ordering": ["rarity", "name"],
            },
        ),
        migrations.CreateModel(
            name="MagicItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_charges",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("is_identified", models.BooleanField(default=True)),
                ("is_cursed", models.BooleanField(default=False)),
                ("curse_revealed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, max_length=500)),
                (
                    "inventory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="character.inventory",
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.magicitemsettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "magic item",
                "verbose_name_plural": "magic items",
                "ordering": ["settings__name"],
            },
        ),
        migrations.CreateModel(
            name="Attunement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attuned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attunements",
                        to="character.character",
                    ),
                ),
                (
                    "magic_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attunement",
                        to="character.magicitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "attunement",
                "verbose_name_plural": "attunements",
                "ordering": ["attuned_at"],
            },
        ),
    ]
