# Generated by Django 5.0.1 on 2024-01-19 20:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0018_alter_ability_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="abilityscoreincrease",
            old_name="ability",
            new_name="ability_type",
        ),
    ]
