# Generated by Django 4.2.4 on 2023-09-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0018_ability_racialtrait_abilities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ability",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
