# Generated by Django 5.2.9 on 2026-01-19 12:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0018_magic_items"),
        ("game", "0006_spell_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonsterSettings",
            fields=[
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Aboleth", "Aboleth"),
                            ("Ape", "Ape"),
                            ("Bat", "Bat"),
                            ("Black Bear", "Black Bear"),
                            ("Boar", "Boar"),
                            ("Brown Bear", "Brown Bear"),
                            ("Cat", "Cat"),
                            ("Constrictor Snake", "Constrictor Snake"),
                            ("Crocodile", "Crocodile"),
                            ("Dire Wolf", "Dire Wolf"),
                            ("Frog", "Frog"),
                            ("Giant Ape", "Giant Ape"),
                            ("Giant Bat", "Giant Bat"),
                            ("Giant Boar", "Giant Boar"),
                            ("Giant Constrictor Snake", "Giant Constrictor Snake"),
                            ("Giant Crocodile", "Giant Crocodile"),
                            ("Giant Eagle", "Giant Eagle"),
                            ("Giant Frog", "Giant Frog"),
                            ("Giant Goat", "Giant Goat"),
                            ("Giant Lizard", "Giant Lizard"),
                            ("Giant Octopus", "Giant Octopus"),
                            ("Giant Owl", "Giant Owl"),
                            ("Giant Poisonous Snake", "Giant Poisonous Snake"),
                            ("Giant Rat", "Giant Rat"),
                            ("Giant Scorpion", "Giant Scorpion"),
                            ("Giant Shark", "Giant Shark"),
                            ("Giant Spider", "Giant Spider"),
                            ("Giant Toad", "Giant Toad"),
                            ("Giant Vulture", "Giant Vulture"),
                            ("Giant Wasp", "Giant Wasp"),
                            ("Giant Weasel", "Giant Weasel"),
                            ("Giant Wolf Spider", "Giant Wolf Spider"),
                            ("Hawk", "Hawk"),
                            ("Hunter Shark", "Hunter Shark"),
                            ("Lion", "Lion"),
                            ("Mammoth", "Mammoth"),
                            ("Mastiff", "Mastiff"),
                            ("Owl", "Owl"),
                            ("Panther", "Panther"),
                            ("Poisonous Snake", "Poisonous Snake"),
                            ("Polar Bear", "Polar Bear"),
                            ("Rat", "Rat"),
                            ("Raven", "Raven"),
                            ("Reef Shark", "Reef Shark"),
                            ("Riding Horse", "Riding Horse"),
                            ("Saber-Toothed Tiger", "Saber Toothed Tiger"),
                            ("Tiger", "Tiger"),
                            ("Warhorse", "Warhorse"),
                            ("Wolf", "Wolf"),
                            ("Couatl", "Couatl"),
                            ("Animated Armor", "Animated Armor"),
                            ("Flying Sword", "Flying Sword"),
                            ("Iron Golem", "Iron Golem"),
                            ("Stone Golem", "Stone Golem"),
                            ("Adult Black Dragon", "Adult Black Dragon"),
                            ("Adult Blue Dragon", "Adult Blue Dragon"),
                            ("Adult Green Dragon", "Adult Green Dragon"),
                            ("Adult Red Dragon", "Adult Red Dragon"),
                            ("Adult White Dragon", "Adult White Dragon"),
                            ("Ancient Black Dragon", "Ancient Black Dragon"),
                            ("Ancient Blue Dragon", "Ancient Blue Dragon"),
                            ("Ancient Green Dragon", "Ancient Green Dragon"),
                            ("Ancient Red Dragon", "Ancient Red Dragon"),
                            ("Ancient White Dragon", "Ancient White Dragon"),
                            ("Black Dragon Wyrmling", "Black Dragon Wyrmling"),
                            ("Blue Dragon Wyrmling", "Blue Dragon Wyrmling"),
                            ("Green Dragon Wyrmling", "Green Dragon Wyrmling"),
                            ("Red Dragon Wyrmling", "Red Dragon Wyrmling"),
                            ("White Dragon Wyrmling", "White Dragon Wyrmling"),
                            ("Young Black Dragon", "Young Black Dragon"),
                            ("Young Blue Dragon", "Young Blue Dragon"),
                            ("Young Green Dragon", "Young Green Dragon"),
                            ("Young Red Dragon", "Young Red Dragon"),
                            ("Young White Dragon", "Young White Dragon"),
                            ("Air Elemental", "Air Elemental"),
                            ("Earth Elemental", "Earth Elemental"),
                            ("Fire Elemental", "Fire Elemental"),
                            ("Water Elemental", "Water Elemental"),
                            ("Balor", "Balor"),
                            ("Barbed Devil", "Barbed Devil"),
                            ("Bearded Devil", "Bearded Devil"),
                            ("Bone Devil", "Bone Devil"),
                            ("Chain Devil", "Chain Devil"),
                            ("Dretch", "Dretch"),
                            ("Erinyes", "Erinyes"),
                            ("Glabrezu", "Glabrezu"),
                            ("Hezrou", "Hezrou"),
                            ("Horned Devil", "Horned Devil"),
                            ("Ice Devil", "Ice Devil"),
                            ("Imp", "Imp"),
                            ("Lemure", "Lemure"),
                            ("Marilith", "Marilith"),
                            ("Nalfeshnee", "Nalfeshnee"),
                            ("Pit Fiend", "Pit Fiend"),
                            ("Quasit", "Quasit"),
                            ("Vrock", "Vrock"),
                            ("Cloud Giant", "Cloud Giant"),
                            ("Fire Giant", "Fire Giant"),
                            ("Frost Giant", "Frost Giant"),
                            ("Hill Giant", "Hill Giant"),
                            ("Stone Giant", "Stone Giant"),
                            ("Storm Giant", "Storm Giant"),
                            ("Acolyte", "Acolyte"),
                            ("Assassin", "Assassin"),
                            ("Bandit", "Bandit"),
                            ("Bandit Captain", "Bandit Captain"),
                            ("Berserker", "Berserker"),
                            ("Commoner", "Commoner"),
                            ("Cultist", "Cultist"),
                            ("Cult Fanatic", "Cult Fanatic"),
                            ("Gladiator", "Gladiator"),
                            ("Guard", "Guard"),
                            ("Knight", "Knight"),
                            ("Mage", "Mage"),
                            ("Noble", "Noble"),
                            ("Priest", "Priest"),
                            ("Scout", "Scout"),
                            ("Spy", "Spy"),
                            ("Thug", "Thug"),
                            ("Tribal Warrior", "Tribal Warrior"),
                            ("Veteran", "Veteran"),
                            ("Basilisk", "Basilisk"),
                            ("Cockatrice", "Cockatrice"),
                            ("Grick", "Grick"),
                            ("Griffon", "Griffon"),
                            ("Harpy", "Harpy"),
                            ("Hippogriff", "Hippogriff"),
                            ("Hydra", "Hydra"),
                            ("Medusa", "Medusa"),
                            ("Minotaur", "Minotaur"),
                            ("Owlbear", "Owlbear"),
                            ("Phase Spider", "Phase Spider"),
                            ("Remorhaz", "Remorhaz"),
                            ("Roc", "Roc"),
                            ("Winter Wolf", "Winter Wolf"),
                            ("Worg", "Worg"),
                            ("Black Pudding", "Black Pudding"),
                            ("Gelatinous Cube", "Gelatinous Cube"),
                            ("Gray Ooze", "Gray Ooze"),
                            ("Ochre Jelly", "Ochre Jelly"),
                            ("Shambling Mound", "Shambling Mound"),
                            ("Treant", "Treant"),
                            ("Ghost", "Ghost"),
                            ("Ghoul", "Ghoul"),
                            ("Lich", "Lich"),
                            ("Mummy", "Mummy"),
                            ("Mummy Lord", "Mummy Lord"),
                            ("Skeleton", "Skeleton"),
                            ("Specter", "Specter"),
                            ("Vampire", "Vampire"),
                            ("Wight", "Wight"),
                            ("Wraith", "Wraith"),
                            ("Zombie", "Zombie"),
                        ],
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("tiny", "Tiny"),
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                            ("huge", "Huge"),
                            ("gargantuan", "Gargantuan"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "creature_type",
                    models.CharField(
                        choices=[
                            ("aberration", "Aberration"),
                            ("beast", "Beast"),
                            ("celestial", "Celestial"),
                            ("construct", "Construct"),
                            ("dragon", "Dragon"),
                            ("elemental", "Elemental"),
                            ("fey", "Fey"),
                            ("fiend", "Fiend"),
                            ("giant", "Giant"),
                            ("humanoid", "Humanoid"),
                            ("monstrosity", "Monstrosity"),
                            ("ooze", "Ooze"),
                            ("plant", "Plant"),
                            ("undead", "Undead"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        blank=True,
                        help_text="E.g., 'shapechanger', 'devil', 'goblinoid'",
                        max_length=50,
                    ),
                ),
                (
                    "alignment",
                    models.CharField(
                        choices=[
                            ("LG", "Lawful Good"),
                            ("NG", "Neutral Good"),
                            ("CG", "Chaotic Good"),
                            ("LN", "Lawful Neutral"),
                            ("N", "Neutral"),
                            ("CN", "Chaotic Neutral"),
                            ("LE", "Lawful Evil"),
                            ("NE", "Neutral Evil"),
                            ("CE", "Chaotic Evil"),
                            ("U", "Unaligned"),
                            ("any", "Any Alignment"),
                        ],
                        max_length=5,
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=2000)),
                (
                    "ac",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ]
                    ),
                ),
                (
                    "ac_type",
                    models.CharField(
                        blank=True,
                        help_text="E.g., 'natural armor', 'plate armor'",
                        max_length=50,
                    ),
                ),
                (
                    "hit_dice",
                    models.CharField(
                        help_text="E.g., '8d8+16' for a creature with 8 HD and +2 CON",
                        max_length=20,
                    ),
                ),
                (
                    "hp_average",
                    models.PositiveSmallIntegerField(
                        help_text="Average HP (used for quick reference)"
                    ),
                ),
                (
                    "speed",
                    models.JSONField(
                        default=dict,
                        help_text="Movement speeds by type (e.g., {'walk': 30, 'fly': 60})",
                    ),
                ),
                (
                    "strength",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ]
                    ),
                ),
                (
                    "dexterity",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ]
                    ),
                ),
                (
                    "constitution",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ]
                    ),
                ),
                (
                    "intelligence",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ]
                    ),
                ),
                (
                    "wisdom",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ]
                    ),
                ),
                (
                    "charisma",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ]
                    ),
                ),
                (
                    "saving_throws",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Saving throw bonuses (e.g., {'STR': 5, 'CON': 7})",
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Skill bonuses (e.g., {'perception': 5, 'stealth': 6})",
                    ),
                ),
                (
                    "damage_vulnerabilities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of damage types the creature is vulnerable to",
                    ),
                ),
                (
                    "damage_resistances",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of damage types the creature resists",
                    ),
                ),
                (
                    "damage_immunities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of damage types the creature is immune to",
                    ),
                ),
                (
                    "condition_immunities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of conditions the creature is immune to",
                    ),
                ),
                (
                    "senses",
                    models.JSONField(
                        default=dict,
                        help_text="Senses (e.g., {'darkvision': 60, 'passive_perception': 14})",
                    ),
                ),
                (
                    "languages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Languages the creature speaks/understands",
                    ),
                ),
                (
                    "telepathy",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Telepathy range in feet (0 if none)"
                    ),
                ),
                (
                    "challenge_rating",
                    models.CharField(
                        choices=[
                            ("0", "0"),
                            ("1/8", "1/8"),
                            ("1/4", "1/4"),
                            ("1/2", "1/2"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                            ("16", "16"),
                            ("17", "17"),
                            ("18", "18"),
                            ("19", "19"),
                            ("20", "20"),
                            ("21", "21"),
                            ("22", "22"),
                            ("23", "23"),
                            ("24", "24"),
                            ("25", "25"),
                            ("26", "26"),
                            ("27", "27"),
                            ("28", "28"),
                            ("29", "29"),
                            ("30", "30"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "proficiency_bonus",
                    models.PositiveSmallIntegerField(
                        help_text="Proficiency bonus based on CR",
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(9),
                        ],
                    ),
                ),
                (
                    "traits",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Special traits as list of {name, description} objects",
                    ),
                ),
                (
                    "actions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Actions as list of {name, description} objects",
                    ),
                ),
                (
                    "reactions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Reactions as list of {name, description} objects",
                    ),
                ),
                (
                    "legendary_actions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Legendary actions as list of {name, description, cost} objects",
                    ),
                ),
                (
                    "legendary_action_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Number of legendary actions per round (typically 3)",
                    ),
                ),
                (
                    "lair_actions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lair actions as list of {description} objects",
                    ),
                ),
                ("has_lair", models.BooleanField(default=False)),
                (
                    "spellcasting",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Spellcasting details if the creature is a spellcaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "monster settings",
                "verbose_name_plural": "monster settings",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Monster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instance_name",
                    models.CharField(
                        blank=True,
                        help_text="Name for this specific instance",
                        max_length=100,
                    ),
                ),
                ("hp_current", models.SmallIntegerField()),
                ("hp_max", models.PositiveSmallIntegerField()),
                ("hp_temp", models.PositiveSmallIntegerField(default=0)),
                (
                    "legendary_actions_remaining",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("notes", models.TextField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "combat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monsters",
                        to="game.combat",
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="character.monstersettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "monster",
                "verbose_name_plural": "monsters",
                "ordering": ["settings__name", "instance_name"],
            },
        ),
    ]
