# Generated by Django 4.2.5 on 2023-09-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0019_alter_ability_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ability",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
