# Generated by Django 5.2.9 on 2026-01-19 16:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0019_monsters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monstersettings",
            name="name",
            field=models.CharField(
                choices=[
                    ("Aboleth", "Aboleth"),
                    ("Ape", "Ape"),
                    ("Bat", "Bat"),
                    ("Black Bear", "Black Bear"),
                    ("Boar", "Boar"),
                    ("Brown Bear", "Brown Bear"),
                    ("Cat", "Cat"),
                    ("Constrictor Snake", "Constrictor Snake"),
                    ("Crocodile", "Crocodile"),
                    ("Dire Wolf", "Dire Wolf"),
                    ("Frog", "Frog"),
                    ("Giant Ape", "Giant Ape"),
                    ("Giant Bat", "Giant Bat"),
                    ("Giant Boar", "Giant Boar"),
                    ("Giant Constrictor Snake", "Giant Constrictor Snake"),
                    ("Giant Crocodile", "Giant Crocodile"),
                    ("Giant Eagle", "Giant Eagle"),
                    ("Giant Frog", "Giant Frog"),
                    ("Giant Goat", "Giant Goat"),
                    ("Giant Lizard", "Giant Lizard"),
                    ("Giant Octopus", "Giant Octopus"),
                    ("Giant Owl", "Giant Owl"),
                    ("Giant Poisonous Snake", "Giant Poisonous Snake"),
                    ("Giant Rat", "Giant Rat"),
                    ("Giant Scorpion", "Giant Scorpion"),
                    ("Giant Shark", "Giant Shark"),
                    ("Giant Spider", "Giant Spider"),
                    ("Giant Toad", "Giant Toad"),
                    ("Giant Vulture", "Giant Vulture"),
                    ("Giant Wasp", "Giant Wasp"),
                    ("Giant Weasel", "Giant Weasel"),
                    ("Giant Wolf Spider", "Giant Wolf Spider"),
                    ("Hawk", "Hawk"),
                    ("Hunter Shark", "Hunter Shark"),
                    ("Lion", "Lion"),
                    ("Mammoth", "Mammoth"),
                    ("Mastiff", "Mastiff"),
                    ("Owl", "Owl"),
                    ("Panther", "Panther"),
                    ("Poisonous Snake", "Poisonous Snake"),
                    ("Polar Bear", "Polar Bear"),
                    ("Rat", "Rat"),
                    ("Raven", "Raven"),
                    ("Reef Shark", "Reef Shark"),
                    ("Riding Horse", "Riding Horse"),
                    ("Saber-Toothed Tiger", "Saber Toothed Tiger"),
                    ("Tiger", "Tiger"),
                    ("Warhorse", "Warhorse"),
                    ("Wolf", "Wolf"),
                    ("Couatl", "Couatl"),
                    ("Animated Armor", "Animated Armor"),
                    ("Flying Sword", "Flying Sword"),
                    ("Iron Golem", "Iron Golem"),
                    ("Stone Golem", "Stone Golem"),
                    ("Adult Black Dragon", "Adult Black Dragon"),
                    ("Adult Blue Dragon", "Adult Blue Dragon"),
                    ("Adult Green Dragon", "Adult Green Dragon"),
                    ("Adult Red Dragon", "Adult Red Dragon"),
                    ("Adult White Dragon", "Adult White Dragon"),
                    ("Ancient Black Dragon", "Ancient Black Dragon"),
                    ("Ancient Blue Dragon", "Ancient Blue Dragon"),
                    ("Ancient Green Dragon", "Ancient Green Dragon"),
                    ("Ancient Red Dragon", "Ancient Red Dragon"),
                    ("Ancient White Dragon", "Ancient White Dragon"),
                    ("Black Dragon Wyrmling", "Black Dragon Wyrmling"),
                    ("Blue Dragon Wyrmling", "Blue Dragon Wyrmling"),
                    ("Green Dragon Wyrmling", "Green Dragon Wyrmling"),
                    ("Red Dragon Wyrmling", "Red Dragon Wyrmling"),
                    ("White Dragon Wyrmling", "White Dragon Wyrmling"),
                    ("Young Black Dragon", "Young Black Dragon"),
                    ("Young Blue Dragon", "Young Blue Dragon"),
                    ("Young Green Dragon", "Young Green Dragon"),
                    ("Young Red Dragon", "Young Red Dragon"),
                    ("Young White Dragon", "Young White Dragon"),
                    ("Air Elemental", "Air Elemental"),
                    ("Earth Elemental", "Earth Elemental"),
                    ("Fire Elemental", "Fire Elemental"),
                    ("Water Elemental", "Water Elemental"),
                    ("Balor", "Balor"),
                    ("Barbed Devil", "Barbed Devil"),
                    ("Bearded Devil", "Bearded Devil"),
                    ("Bone Devil", "Bone Devil"),
                    ("Chain Devil", "Chain Devil"),
                    ("Dretch", "Dretch"),
                    ("Erinyes", "Erinyes"),
                    ("Glabrezu", "Glabrezu"),
                    ("Hezrou", "Hezrou"),
                    ("Horned Devil", "Horned Devil"),
                    ("Ice Devil", "Ice Devil"),
                    ("Imp", "Imp"),
                    ("Lemure", "Lemure"),
                    ("Marilith", "Marilith"),
                    ("Nalfeshnee", "Nalfeshnee"),
                    ("Pit Fiend", "Pit Fiend"),
                    ("Quasit", "Quasit"),
                    ("Vrock", "Vrock"),
                    ("Cloud Giant", "Cloud Giant"),
                    ("Fire Giant", "Fire Giant"),
                    ("Frost Giant", "Frost Giant"),
                    ("Hill Giant", "Hill Giant"),
                    ("Ogre", "Ogre"),
                    ("Stone Giant", "Stone Giant"),
                    ("Storm Giant", "Storm Giant"),
                    ("Acolyte", "Acolyte"),
                    ("Assassin", "Assassin"),
                    ("Bandit", "Bandit"),
                    ("Bandit Captain", "Bandit Captain"),
                    ("Berserker", "Berserker"),
                    ("Commoner", "Commoner"),
                    ("Cultist", "Cultist"),
                    ("Cult Fanatic", "Cult Fanatic"),
                    ("Gladiator", "Gladiator"),
                    ("Guard", "Guard"),
                    ("Knight", "Knight"),
                    ("Mage", "Mage"),
                    ("Noble", "Noble"),
                    ("Orc", "Orc"),
                    ("Priest", "Priest"),
                    ("Scout", "Scout"),
                    ("Spy", "Spy"),
                    ("Thug", "Thug"),
                    ("Tribal Warrior", "Tribal Warrior"),
                    ("Veteran", "Veteran"),
                    ("Basilisk", "Basilisk"),
                    ("Cockatrice", "Cockatrice"),
                    ("Grick", "Grick"),
                    ("Griffon", "Griffon"),
                    ("Harpy", "Harpy"),
                    ("Hippogriff", "Hippogriff"),
                    ("Hydra", "Hydra"),
                    ("Medusa", "Medusa"),
                    ("Minotaur", "Minotaur"),
                    ("Owlbear", "Owlbear"),
                    ("Phase Spider", "Phase Spider"),
                    ("Remorhaz", "Remorhaz"),
                    ("Roc", "Roc"),
                    ("Winter Wolf", "Winter Wolf"),
                    ("Worg", "Worg"),
                    ("Black Pudding", "Black Pudding"),
                    ("Gelatinous Cube", "Gelatinous Cube"),
                    ("Gray Ooze", "Gray Ooze"),
                    ("Ochre Jelly", "Ochre Jelly"),
                    ("Shambling Mound", "Shambling Mound"),
                    ("Treant", "Treant"),
                    ("Ghost", "Ghost"),
                    ("Ghoul", "Ghoul"),
                    ("Lich", "Lich"),
                    ("Mummy", "Mummy"),
                    ("Mummy Lord", "Mummy Lord"),
                    ("Skeleton", "Skeleton"),
                    ("Specter", "Specter"),
                    ("Vampire", "Vampire"),
                    ("Wight", "Wight"),
                    ("Wraith", "Wraith"),
                    ("Zombie", "Zombie"),
                ],
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="LairActionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(max_length=500)),
                ("save_dc", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "save_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("STR", "Strength"),
                            ("DEX", "Dexterity"),
                            ("CON", "Constitution"),
                            ("INT", "Intelligence"),
                            ("WIS", "Wisdom"),
                            ("CHA", "Charisma"),
                        ],
                        default="none",
                        max_length=5,
                    ),
                ),
                (
                    "save_effect",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("half_damage", "Half Damage"),
                            ("negates", "Negates Effect"),
                            ("ends_effect", "Ends Effect"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "area_shape",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("sphere", "Sphere"),
                            ("cube", "Cube"),
                            ("cone", "Cone"),
                            ("line", "Line"),
                            ("cylinder", "Cylinder"),
                        ],
                        default="none",
                        max_length=15,
                    ),
                ),
                ("area_size", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("effects", models.JSONField(blank=True, default=list)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "monster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lair_action_templates",
                        to="character.monstersettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "lair action template",
                "verbose_name_plural": "lair action templates",
                "ordering": ["monster", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="MonsterActionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("melee_weapon", "Melee Weapon Attack"),
                            ("ranged_weapon", "Ranged Weapon Attack"),
                            ("melee_spell", "Melee Spell Attack"),
                            ("ranged_spell", "Ranged Spell Attack"),
                            ("multiattack", "Multiattack"),
                            ("special", "Special Ability"),
                            ("legendary", "Legendary Action"),
                            ("lair", "Lair Action"),
                            ("reaction", "Reaction"),
                        ],
                        default="special",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Full description text for the action",
                        max_length=1000,
                    ),
                ),
                (
                    "attack_bonus",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="Bonus to attack roll (e.g., +5)",
                        null=True,
                    ),
                ),
                (
                    "reach",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Melee reach in feet", null=True
                    ),
                ),
                (
                    "range_normal",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Normal range in feet", null=True
                    ),
                ),
                (
                    "range_long",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Long range in feet (with disadvantage)",
                        null=True,
                    ),
                ),
                (
                    "targets",
                    models.CharField(
                        default="one target",
                        help_text="Target description (e.g., 'one target', 'one creature')",
                        max_length=100,
                    ),
                ),
                (
                    "damage_dice",
                    models.CharField(
                        blank=True,
                        help_text="Damage dice (e.g., '2d6+4')",
                        max_length=30,
                    ),
                ),
                (
                    "damage_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("acid", "Acid"),
                            ("bludgeoning", "Bludgeoning"),
                            ("cold", "Cold"),
                            ("fire", "Fire"),
                            ("force", "Force"),
                            ("lightning", "Lightning"),
                            ("necrotic", "Necrotic"),
                            ("piercing", "Piercing"),
                            ("poison", "Poison"),
                            ("psychic", "Psychic"),
                            ("radiant", "Radiant"),
                            ("slashing", "Slashing"),
                            ("thunder", "Thunder"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "extra_damage_dice",
                    models.CharField(
                        blank=True,
                        help_text="Additional damage dice (e.g., '1d6' poison)",
                        max_length=30,
                    ),
                ),
                (
                    "extra_damage_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("acid", "Acid"),
                            ("bludgeoning", "Bludgeoning"),
                            ("cold", "Cold"),
                            ("fire", "Fire"),
                            ("force", "Force"),
                            ("lightning", "Lightning"),
                            ("necrotic", "Necrotic"),
                            ("piercing", "Piercing"),
                            ("poison", "Poison"),
                            ("psychic", "Psychic"),
                            ("radiant", "Radiant"),
                            ("slashing", "Slashing"),
                            ("thunder", "Thunder"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "versatile_damage",
                    models.CharField(
                        blank=True,
                        help_text="Damage dice when used two-handed",
                        max_length=30,
                    ),
                ),
                (
                    "save_dc",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Saving throw DC", null=True
                    ),
                ),
                (
                    "save_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("STR", "Strength"),
                            ("DEX", "Dexterity"),
                            ("CON", "Constitution"),
                            ("INT", "Intelligence"),
                            ("WIS", "Wisdom"),
                            ("CHA", "Charisma"),
                        ],
                        default="none",
                        max_length=5,
                    ),
                ),
                (
                    "save_effect",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("half_damage", "Half Damage"),
                            ("negates", "Negates Effect"),
                            ("ends_effect", "Ends Effect"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "area_shape",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("sphere", "Sphere"),
                            ("cube", "Cube"),
                            ("cone", "Cone"),
                            ("line", "Line"),
                            ("cylinder", "Cylinder"),
                        ],
                        default="none",
                        max_length=15,
                    ),
                ),
                (
                    "area_size",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Size of the area in feet", null=True
                    ),
                ),
                (
                    "recharge",
                    models.CharField(
                        choices=[
                            ("none", "No Recharge"),
                            ("5-6", "Recharge 5-6"),
                            ("6", "Recharge 6"),
                            ("4-6", "Recharge 4-6"),
                            ("short_rest", "Recharges on Short Rest"),
                            ("long_rest", "Recharges on Long Rest"),
                            ("daily_1", "1/Day"),
                            ("daily_2", "2/Day"),
                            ("daily_3", "3/Day"),
                        ],
                        default="none",
                        max_length=15,
                    ),
                ),
                (
                    "effects",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Additional effects as list of {type, description}",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "monster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_templates",
                        to="character.monstersettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "monster action template",
                "verbose_name_plural": "monster action templates",
                "ordering": ["monster", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="LegendaryActionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=500)),
                (
                    "cost",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Legendary action cost (1-3)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "monster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legendary_action_templates",
                        to="character.monstersettings",
                    ),
                ),
                (
                    "action_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to action template if this uses an existing action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legendary_uses",
                        to="character.monsteractiontemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "legendary action template",
                "verbose_name_plural": "legendary action templates",
                "ordering": ["monster", "sort_order", "cost", "name"],
            },
        ),
        migrations.CreateModel(
            name="MonsterMultiattack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Text description of the multiattack", max_length=500
                    ),
                ),
                (
                    "monster",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multiattack",
                        to="character.monstersettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "monster multiattack",
                "verbose_name_plural": "monster multiattacks",
            },
        ),
        migrations.CreateModel(
            name="MonsterReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=500)),
                (
                    "trigger",
                    models.CharField(
                        help_text="What triggers this reaction", max_length=200
                    ),
                ),
                (
                    "action_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reaction_uses",
                        to="character.monsteractiontemplate",
                    ),
                ),
                (
                    "monster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reaction_templates",
                        to="character.monstersettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "monster reaction",
                "verbose_name_plural": "monster reactions",
                "ordering": ["monster", "name"],
            },
        ),
        migrations.CreateModel(
            name="MonsterTrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=1000)),
                (
                    "uses_per_day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Number of uses per day (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "recharge",
                    models.CharField(
                        choices=[
                            ("none", "No Recharge"),
                            ("5-6", "Recharge 5-6"),
                            ("6", "Recharge 6"),
                            ("4-6", "Recharge 4-6"),
                            ("short_rest", "Recharges on Short Rest"),
                            ("long_rest", "Recharges on Long Rest"),
                            ("daily_1", "1/Day"),
                            ("daily_2", "2/Day"),
                            ("daily_3", "3/Day"),
                        ],
                        default="none",
                        max_length=15,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "monster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trait_templates",
                        to="character.monstersettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "monster trait",
                "verbose_name_plural": "monster traits",
                "ordering": ["monster", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MultiattackAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Number of times this action is used in multiattack",
                    ),
                ),
                (
                    "is_optional",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this action is optional (e.g., 'or' options)",
                    ),
                ),
                (
                    "group",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Group number for 'or' options (same group = choose one)",
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multiattack_uses",
                        to="character.monsteractiontemplate",
                    ),
                ),
                (
                    "multiattack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="character.monstermultiattack",
                    ),
                ),
            ],
            options={
                "verbose_name": "multiattack action",
                "verbose_name_plural": "multiattack actions",
                "ordering": ["multiattack", "group", "-count"],
            },
        ),
    ]
