# Generated by Django 5.0.1 on 2024-01-19 20:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0019_rename_ability_abilityscoreincrease_ability_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skill",
            old_name="ability",
            new_name="ability_type",
        ),
    ]
