# Generated by Django 5.0.1 on 2024-01-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0020_rename_ability_skill_ability_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="description",
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
