# Generated by Django 4.2.5 on 2023-09-06 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0020_alter_ability_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advancement",
            options={"ordering": ["xp"]},
        ),
    ]
