# Generated by Django 6.0.1 on 2026-01-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0021_character_wizard_enhancements"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="death_save_failures",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="death_save_successes",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="temp_hp",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="classspellcasting",
            name="caster_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("prepared", "Prepared"),
                    ("known", "Known"),
                    ("pact", "Pact"),
                ],
                help_text="Empty for non-casters",
                max_length=10,
            ),
        ),
    ]
