# Generated by Django 4.2.5 on 2023-09-06 19:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0021_alter_advancement_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ability",
            options={"verbose_name_plural": "abilities"},
        ),
    ]
