# Generated by Django 4.2.5 on 2023-09-06 19:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0022_alter_ability_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ability",
            options={"ordering": ["name"], "verbose_name_plural": "abilities"},
        ),
    ]
