# Generated by Django 6.0.1 on 2026-02-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0022_add_temp_hp_and_death_saves"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="location",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
