# Generated by Django 4.2.5 on 2023-09-08 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0023_alter_ability_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbilityScoreIncrease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ability",
                    models.CharField(
                        choices=[
                            ("strength", "Strength"),
                            ("dexterity", "Dexterity"),
                            ("constitution", "Constitution"),
                            ("intelligence", "Intelligence"),
                            ("wisdom", "Wisdom"),
                            ("charisma", "Charisma"),
                        ],
                        max_length=20,
                    ),
                ),
                ("increase", models.SmallIntegerField()),
                (
                    "racial_trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.racialtrait",
                    ),
                ),
            ],
        ),
    ]
