# Generated by Django 5.0.2 on 2024-02-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0023_rename_savingthrow_savingthrowproficiency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sense",
            name="name",
            field=models.CharField(
                choices=[
                    ("DV", "Darkvision"),
                    ("DR", "Dwarven Resilience"),
                    ("DC", "Dwarven Combat Training"),
                    ("TP", "Tool Proficiency"),
                    ("SC", "Stonecunning"),
                    ("KS", "Keen Senses"),
                    ("FA", "Fey Ancestry"),
                    ("TR", "Trance"),
                    ("LU", "Lucky"),
                    ("BR", "Brave"),
                    ("HN", "Halfling Nimbleness"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
