# Generated by Django 5.0.2 on 2024-02-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0024_alter_sense_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SkillsProficiency",
            new_name="SkillProficiency",
        ),
        migrations.RenameModel(
            old_name="ToolsProficiency",
            new_name="ToolProficiency",
        ),
        migrations.RenameModel(
            old_name="WeaponsProficiency",
            new_name="WeaponProficiency",
        ),
        migrations.AlterField(
            model_name="sense",
            name="name",
            field=models.CharField(
                choices=[
                    ("BR", "Brave"),
                    ("DV", "Darkvision"),
                    ("DC", "Dwarven Combat Training"),
                    ("DR", "Dwarven Resilience"),
                    ("FA", "Fey Ancestry"),
                    ("HN", "Halfling Nimbleness"),
                    ("KS", "Keen Senses"),
                    ("LU", "Lucky"),
                    ("SC", "Stonecunning"),
                    ("TP", "Tool Proficiency"),
                    ("TR", "Trance"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
