# Generated by Django 6.0.1 on 2026-02-10 16:20
# Updated FK references from character models to equipment models.
# State-only migration: the DB columns already point to the correct tables.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0024_split_apps"),
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="armorproficiency",
                    name="armor",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipment.armorsettings",
                    ),
                ),
                migrations.AlterField(
                    model_name="character",
                    name="inventory",
                    field=models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipment.inventory",
                    ),
                ),
                migrations.AlterField(
                    model_name="toolproficiency",
                    name="tool",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipment.toolsettings",
                    ),
                ),
                migrations.AlterField(
                    model_name="weaponproficiency",
                    name="weapon",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipment.weaponsettings",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
