# Generated by Django 5.0.2 on 2024-02-24 04:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0025_rename_skillsproficiency_skillproficiency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="racialtrait",
            name="languages",
        ),
        migrations.RemoveField(
            model_name="racialtrait",
            name="senses",
        ),
        migrations.DeleteModel(
            name="AbilityScoreIncrease",
        ),
        migrations.DeleteModel(
            name="RacialTrait",
        ),
    ]
