# Generated by Django 6.0.2 on 2026-02-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0025_alter_armorproficiency_armor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="name",
            field=models.CharField(
                choices=[
                    ("dragonborn", "Dragonborn"),
                    ("dwarf", "Dwarf"),
                    ("elf", "Elf"),
                    ("gnome", "Gnome"),
                    ("goliath", "Goliath"),
                    ("halfling", "Halfling"),
                    ("human", "Human"),
                    ("orc", "Orc"),
                    ("tiefling", "Tiefling"),
                ],
                max_length=20,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="speciestrait",
            name="name",
            field=models.CharField(
                choices=[
                    ("breath_weapon", "Breath Weapon"),
                    ("draconic_ancestry", "Draconic Ancestry"),
                    ("draconic_damage_resistance", "Draconic Damage Resistance"),
                    ("dwarven_resilience", "Dwarven Resilience"),
                    ("dwarven_toughness", "Dwarven Toughness"),
                    ("stonecunning", "Stonecunning"),
                    ("fey_ancestry", "Fey Ancestry"),
                    ("keen_senses", "Keen Senses"),
                    ("trance", "Trance"),
                    ("gnomish_cunning", "Gnomish Cunning"),
                    ("giant_ancestry", "Giant Ancestry"),
                    ("large_form", "Large Form"),
                    ("powerful_build", "Powerful Build"),
                    ("brave", "Brave"),
                    ("halfling_nimbleness", "Halfling Nimbleness"),
                    ("lucky", "Lucky"),
                    ("resourceful", "Resourceful"),
                    ("skillful", "Skillful"),
                    ("versatile", "Versatile"),
                    ("adrenaline_rush", "Adrenaline Rush"),
                    ("relentless_endurance", "Relentless Endurance"),
                    ("fiendish_legacy", "Fiendish Legacy"),
                    ("otherworldly_presence", "Otherworldly Presence"),
                ],
                max_length=30,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
