# Generated by Django 5.0.2 on 2024-03-01 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0026_remove_racialtrait_languages_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ClassAdvancement",
            new_name="KlassAdvancement",
        ),
        migrations.RenameModel(
            old_name="ClassFeature",
            new_name="KlassFeature",
        ),
    ]
