# Generated by Django 4.2.5 on 2023-09-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0026_character_abilities_character_adult_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(
                choices=[
                    ("C", "Common"),
                    ("D", "Dwarvish"),
                    ("E", "Elvish"),
                    ("H", "Halfling"),
                ],
                max_length=1,
                unique=True,
            ),
        ),
    ]
