# Generated by Django 6.0.2 on 2026-02-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0026_alter_species_name_alter_speciestrait_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speciestrait",
            name="name",
            field=models.CharField(
                choices=[
                    ("breath_weapon", "Breath Weapon"),
                    ("draconic_ancestry", "Draconic Ancestry"),
                    ("draconic_damage_resistance", "Draconic Damage Resistance"),
                    ("draconic_flight", "Draconic Flight"),
                    ("dwarven_resilience", "Dwarven Resilience"),
                    ("dwarven_toughness", "Dwarven Toughness"),
                    ("stonecunning", "Stonecunning"),
                    ("fey_ancestry", "Fey Ancestry"),
                    ("keen_senses", "Keen Senses"),
                    ("trance", "Trance"),
                    ("gnomish_cunning", "Gnomish Cunning"),
                    ("gnomish_lineage", "Gnomish Lineage"),
                    ("giant_ancestry", "Giant Ancestry"),
                    ("large_form", "Large Form"),
                    ("powerful_build", "Powerful Build"),
                    ("brave", "Brave"),
                    ("halfling_nimbleness", "Halfling Nimbleness"),
                    ("lucky", "Lucky"),
                    ("resourceful", "Resourceful"),
                    ("skillful", "Skillful"),
                    ("versatile", "Versatile"),
                    ("adrenaline_rush", "Adrenaline Rush"),
                    ("relentless_endurance", "Relentless Endurance"),
                    ("fiendish_legacy", "Fiendish Legacy"),
                    ("otherworldly_presence", "Otherworldly Presence"),
                ],
                max_length=30,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
