# Generated by Django 6.0.2 on 2026-02-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0027_add_draconic_flight_gnomish_lineage_traits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="background",
            field=models.CharField(
                choices=[
                    ("acolyte", "Acolyte"),
                    ("artisan", "Artisan"),
                    ("charlatan", "Charlatan"),
                    ("criminal", "Criminal"),
                    ("entertainer", "Entertainer"),
                    ("farmer", "Farmer"),
                    ("guard", "Guard"),
                    ("guide", "Guide"),
                    ("hermit", "Hermit"),
                    ("merchant", "Merchant"),
                    ("noble", "Noble"),
                    ("pilgrim", "Pilgrim"),
                    ("sage", "Sage"),
                    ("sailor", "Sailor"),
                    ("scribe", "Scribe"),
                    ("soldier", "Soldier"),
                    ("wayfarer", "Wayfarer"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="feat",
            name="name",
            field=models.CharField(
                choices=[
                    ("alert", "Alert"),
                    ("crafter", "Crafter"),
                    ("healer", "Healer"),
                    ("lucky", "Lucky"),
                    ("magic_initiate_bard", "Magic Initiate (Bard)"),
                    ("magic_initiate_cleric", "Magic Initiate (Cleric)"),
                    ("magic_initiate_druid", "Magic Initiate (Druid)"),
                    ("magic_initiate_sorcerer", "Magic Initiate (Sorcerer)"),
                    ("magic_initiate_warlock", "Magic Initiate (Warlock)"),
                    ("magic_initiate_wizard", "Magic Initiate (Wizard)"),
                    ("musician", "Musician"),
                    ("savage_attacker", "Savage Attacker"),
                    ("skilled", "Skilled"),
                    ("tavern_brawler", "Tavern Brawler"),
                    ("tough", "Tough"),
                ],
                max_length=30,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
