# Generated by Django 5.0.2 on 2024-03-01 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0027_rename_classadvancement_klassadvancement_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="klassadvancement",
            options={"ordering": ["klass"]},
        ),
        migrations.RenameField(
            model_name="character",
            old_name="class_name",
            new_name="klass",
        ),
        migrations.RenameField(
            model_name="hitpoints",
            old_name="class_feature",
            new_name="klass_feature",
        ),
        migrations.RenameField(
            model_name="klassadvancement",
            old_name="class_name",
            new_name="klass",
        ),
        migrations.RenameField(
            model_name="klassfeature",
            old_name="class_name",
            new_name="klass",
        ),
    ]
