# Generated by Django 4.2.5 on 2023-09-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0027_alter_language_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="class_name",
            field=models.CharField(
                choices=[
                    ("C", "Cleric"),
                    ("F", "Fighter"),
                    ("R", "Rogue"),
                    ("W", "Wizard"),
                ],
                max_length=1,
                verbose_name="class",
            ),
        ),
    ]
