# Generated by Django 4.2.5 on 2023-09-09 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0028_alter_character_class_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_name",
                    models.CharField(
                        choices=[
                            ("C", "Cleric"),
                            ("F", "Fighter"),
                            ("R", "Rogue"),
                            ("W", "Wizard"),
                        ],
                        max_length=1,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("weight", models.SmallIntegerField()),
                (
                    "inventory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="character.inventory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HitPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hit_dice", models.CharField(max_length=5)),
                ("hit_points_first_level", models.CharField(max_length=20)),
                ("hit_points_higher_levels", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Proficiency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("armor", models.TextField(max_length=50)),
                ("weapons", models.TextField(max_length=50)),
                ("tools", models.TextField(max_length=50)),
                ("saving_throws", models.TextField(max_length=50)),
                ("skills", models.TextField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Weapon",
        ),
        migrations.AddField(
            model_name="classfeature",
            name="equipment",
            field=models.ManyToManyField(to="character.equipment"),
        ),
        migrations.AddField(
            model_name="classfeature",
            name="hit_points",
            field=models.ManyToManyField(to="character.hitpoint"),
        ),
        migrations.AddField(
            model_name="classfeature",
            name="proficiencies",
            field=models.ManyToManyField(to="character.proficiency"),
        ),
    ]
