# Generated by Django 4.2.5 on 2023-09-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0029_classfeature_equipment_hitpoint_proficiency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassAdvancement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.SmallIntegerField(unique=True)),
                ("proficiency_bonus", models.SmallIntegerField()),
            ],
            options={
                "ordering": ["level"],
            },
        ),
    ]
