# Generated by Django 5.0.3 on 2024-03-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0030_alter_character_race"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sense",
            name="name",
            field=models.CharField(
                choices=[
                    ("brave", "Brave"),
                    ("darkvision", "Darkvision"),
                    ("dwarven_combat_training", "Dwarven Combat Training"),
                    ("dwarven_resilience", "Dwarven Resilience"),
                    ("fey_ancestry", "Fey Ancestry"),
                    ("halfling_nimbleness", "Halfling Nimbleness"),
                    ("keen_senses", "Keen Senses"),
                    ("lucky", "Lucky"),
                    ("stonecunning", "Stonecunning"),
                    ("tool_proficiency", "Tool Proficiency"),
                    ("trance", "Trance"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
