# Generated by Django 4.2.5 on 2023-09-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0031_remove_classadvancement_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classadvancement",
            options={"ordering": ["class_name"]},
        ),
        migrations.AddField(
            model_name="classadvancement",
            name="class_name",
            field=models.CharField(
                choices=[
                    ("C", "Cleric"),
                    ("F", "Fighter"),
                    ("R", "Rogue"),
                    ("W", "Wizard"),
                ],
                default="C",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="classadvancement",
            unique_together={("class_name", "level")},
        ),
    ]
