# Generated by Django 5.0.3 on 2024-03-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0031_alter_sense_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="height",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="character",
            name="weight",
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sense",
            name="name",
            field=models.CharField(
                choices=[
                    ("brave", "Brave"),
                    ("cantrip", "Cantrip"),
                    ("darkvision", "Darkvision"),
                    ("dwarven_armor_training", "Dwarven Armor Training"),
                    ("dwarven_combat_training", "Dwarven Combat Training"),
                    ("dwarven_resilience", "Dwarven Resilience"),
                    ("dwarven_toughness", "Dwarven Toughness"),
                    ("elf_weapon_training", "Elf Weapon Training"),
                    ("extra_language", "Extra Language"),
                    ("fey_ancestry", "Fey Ancestry"),
                    ("fleet_of_foot", "Fleet of Foot"),
                    ("halfling_nimbleness", "Halfling Nimbleness"),
                    ("keen_senses", "Keen Senses"),
                    ("lucky", "Lucky"),
                    ("mask_of_the_wild", "Mask of the Wild"),
                    ("stonecunning", "Stonecunning"),
                    ("tool_proficiency", "Tool Proficiency"),
                    ("trance", "Trance"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
