# Generated by Django 5.0.3 on 2024-03-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0032_character_height_character_weight_alter_sense_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="height",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="character",
            name="weight",
            field=models.SmallIntegerField(default=0),
        ),
    ]
