# Generated by Django 4.2.5 on 2023-09-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0032_alter_classadvancement_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advancement",
            name="id",
        ),
        migrations.AlterField(
            model_name="advancement",
            name="level",
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
