# Generated by Django 5.0.3 on 2024-03-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0033_alter_character_height_alter_character_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(
                choices=[
                    ("common", "Common"),
                    ("dwarvish", "Dwarvish"),
                    ("elvish", "Elvish"),
                    ("halfling", "Halfling"),
                ],
                max_length=8,
                unique=True,
            ),
        ),
    ]
