# Generated by Django 4.2.5 on 2023-09-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0033_remove_advancement_id_alter_advancement_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="charisma_modifier",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="constitution_modifier",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="dexterity_modifier",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="intelligence_modifier",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="strength_modifier",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="wisdom_modifier",
            field=models.SmallIntegerField(default=0),
        ),
    ]
