# Generated by Django 5.0.3 on 2024-03-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0036_alter_language_script"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="bonds",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="flaws",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="ideals",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="personality_traits",
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
