# Generated by Django 5.0.3 on 2024-03-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0037_character_bonds_character_flaws_character_ideals_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="background",
            field=models.CharField(
                choices=[
                    ("acolyte", "Acolyte"),
                    ("criminal", "Criminal"),
                    ("folk_hero", "Folk Hero"),
                    ("noble", "Noble"),
                    ("sage", "Sage"),
                    ("soldier", "Soldier"),
                ],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
