# Generated by Django 5.0.3 on 2024-03-15 03:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0038_alter_language_language_type"),
        ("character", "0038_character_background"),
    ]

    operations = []
