# Generated by Django 5.0.3 on 2024-03-23 07:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0040_alter_character_bonds_alter_character_flaws_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="character",
            old_name="bonds",
            new_name="bond",
        ),
        migrations.RenameField(
            model_name="character",
            old_name="flaws",
            new_name="flaw",
        ),
        migrations.RenameField(
            model_name="character",
            old_name="ideals",
            new_name="ideal",
        ),
        migrations.RenameField(
            model_name="character",
            old_name="personality_traits",
            new_name="personality_trait",
        ),
    ]
