# Generated by Django 5.0.3 on 2024-03-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0041_rename_bonds_character_bond_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="cost",
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="equipment",
            name="weight",
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
