# Generated by Django 5.0.3 on 2024-03-26 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0042_equipment_cost_equipment_weight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="armor",
            name="name",
        ),
        migrations.AddField(
            model_name="armor",
            name="ac",
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="armor",
            name="equipment_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="character.equipment",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="armor",
            name="stealth",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="armor",
            name="strength",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
