# Generated by Django 5.0.3 on 2024-04-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0043_remove_armor_name_armor_ac_armor_equipment_ptr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="inventory",
        ),
        migrations.AddField(
            model_name="inventory",
            name="equipment",
            field=models.ManyToManyField(to="character.equipment"),
        ),
    ]
