# Generated by Django 5.0.3 on 2024-04-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0044_remove_equipment_inventory_inventory_equipment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="name",
        ),
        migrations.AddField(
            model_name="armor",
            name="name",
            field=models.CharField(
                choices=[
                    ("Padded", "Padded"),
                    ("Leather", "Leather"),
                    ("Studded leather", "Studded Leather"),
                    ("Hide", "Hide"),
                    ("Chain shirt", "Chain Shirt"),
                    ("Scale mail", "Scale Mail"),
                    ("Breastplate", "Breastplate"),
                    ("Half plate", "Half Plate"),
                    ("Ring mail", "Ring Mail"),
                    ("Chain mail", "Chain Mail"),
                    ("Splint", "Splint"),
                    ("Plate", "Plate"),
                    ("Shield", "Shield"),
                ],
                default="",
                max_length=30,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
