# Generated by Django 5.0.3 on 2024-04-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0044_remove_equipment_inventory_inventory_equipment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="id",
        ),
        migrations.AlterField(
            model_name="equipment",
            name="name",
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
