# Generated by Django 5.0.3 on 2024-04-12 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0046_remove_inventory_equipment_inventory_armor"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArmorSetting",
            fields=[
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Padded", "Padded"),
                            ("Leather", "Leather"),
                            ("Studded leather", "Studded Leather"),
                            ("Hide", "Hide"),
                            ("Chain shirt", "Chain Shirt"),
                            ("Scale mail", "Scale Mail"),
                            ("Breastplate", "Breastplate"),
                            ("Half plate", "Half Plate"),
                            ("Ring mail", "Ring Mail"),
                            ("Chain mail", "Chain Mail"),
                            ("Splint", "Splint"),
                            ("Plate", "Plate"),
                            ("Shield", "Shield"),
                        ],
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "armor_type",
                    models.CharField(
                        choices=[
                            ("LA", "Light Armor"),
                            ("MA", "Medium Armor"),
                            ("HA", "Heavy Armor"),
                            ("SH", "Shield"),
                        ],
                        max_length=2,
                    ),
                ),
                ("cost", models.SmallIntegerField()),
                ("ac", models.SmallIntegerField()),
                ("strength", models.CharField(blank=True, max_length=6, null=True)),
                ("stealth", models.CharField(blank=True, max_length=1, null=True)),
                ("weight", models.SmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="armor",
            name="equipment_ptr",
        ),
        migrations.RemoveField(
            model_name="klassfeature",
            name="equipment",
        ),
        migrations.AlterField(
            model_name="armorproficiency",
            name="armor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="character.armorsetting"
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="armor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="character.armorsetting",
            ),
        ),
        migrations.DeleteModel(
            name="Equipment",
        ),
        migrations.DeleteModel(
            name="Armor",
        ),
    ]
