# Generated by Django 5.0.3 on 2024-04-12 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0047_armorsetting_remove_armor_equipment_ptr_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ArmorSetting",
            new_name="ArmorSettings",
        ),
        migrations.AlterModelOptions(
            name="armorsettings",
            options={"verbose_name_plural": "armor settings"},
        ),
    ]
