# Generated by Django 5.0.4 on 2024-04-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0049_armor_alter_inventory_armor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="armorsettings",
            name="ac",
            field=models.CharField(max_length=25),
        ),
    ]
