# Generated by Django 5.0.4 on 2024-04-28 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0050_alter_armorsettings_ac"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Weapon",
            new_name="WeaponSettings",
        ),
        migrations.AlterModelOptions(
            name="weaponsettings",
            options={"verbose_name_plural": "weapon settings"},
        ),
    ]
