# Generated by Django 5.0.4 on 2024-04-28 16:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0052_weapon"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pack",
            new_name="PackSettings",
        ),
    ]
