# Generated by Django 5.0.4 on 2024-04-28 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0054_pack"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Gear",
            new_name="GearSettings",
        ),
    ]
