# Generated by Django 5.0.4 on 2024-05-01 05:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0056_gear"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tool",
            new_name="ToolSettings",
        ),
        migrations.AlterModelOptions(
            name="toolsettings",
            options={"verbose_name_plural": "tool settings"},
        ),
    ]
