# Generated by Django 5.0.4 on 2024-05-01 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0058_tool"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gearsettings",
            options={"verbose_name_plural": "gear settings"},
        ),
        migrations.AlterModelOptions(
            name="packsettings",
            options={"verbose_name_plural": "pack settings"},
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="armor",
        ),
        migrations.AddField(
            model_name="armor",
            name="inventory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="character.inventory",
            ),
        ),
        migrations.AddField(
            model_name="gear",
            name="inventory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="character.inventory",
            ),
        ),
        migrations.AddField(
            model_name="pack",
            name="inventory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="character.inventory",
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="inventory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="character.inventory",
            ),
        ),
        migrations.AddField(
            model_name="weapon",
            name="inventory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="character.inventory",
            ),
        ),
    ]
