# Generated by Django 5.0.6 on 2024-05-09 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0060_dexteritycheckdisadvantage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbilityCheckDisadvantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ability_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.abilitytype",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                    ),
                ),
            ],
        ),
    ]
