# Generated by Django 5.0.6 on 2024-05-09 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0062_attackrolldisadvantage_savingthrowdisadvantage_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DexterityCheckDisadvantage",
        ),
    ]
