# Generated by Django 5.0.6 on 2024-05-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0063_delete_dexteritycheckdisadvantage"),
    ]

    operations = [
        migrations.AddField(
            model_name="weaponsettings",
            name="cost",
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weaponsettings",
            name="damage",
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weaponsettings",
            name="properties",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weaponsettings",
            name="weight",
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
