# Generated by Django 5.0.6 on 2024-05-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0064_weaponsettings_cost_weaponsettings_damage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weaponsettings",
            name="properties",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
