# Generated by Django 5.0.6 on 2024-05-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0065_alter_weaponsettings_properties"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weaponsettings",
            name="damage",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="weaponsettings",
            name="properties",
            field=models.CharField(max_length=60, null=True),
        ),
    ]
