# Generated by Django 4.1.3 on 2022-12-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_remove_master_name_character_master_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
