# Generated by Django 4.1.3 on 2022-12-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='mp',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('H', 'Human'), ('O', 'Orc'), ('E', 'Elf'), ('D', 'Dwarf')], max_length=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='xp',
            field=models.SmallIntegerField(default=0),
        ),
    ]
