# Generated by Django 6.0.2 on 2026-03-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="anthropic_api_key",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
