from django.db.models import TextChoices

from equipment.constants.equipment import ToolName
from .feats import FeatName
from .skills import SkillName


class Background(TextChoices):
    ACOLYTE = "acolyte", "Acolyte"
    ARTISAN = "artisan", "Artisan"
    CHARLATAN = "charlatan", "Charlatan"
    CRIMINAL = "criminal", "Criminal"
    ENTERTAINER = "entertainer", "Entertainer"
    FARMER = "farmer", "Farmer"
    GUARD = "guard", "Guard"
    GUIDE = "guide", "Guide"
    HERMIT = "hermit", "Hermit"
    MERCHANT = "merchant", "Merchant"
    NOBLE = "noble", "Noble"
    PILGRIM = "pilgrim", "Pilgrim"
    SAGE = "sage", "Sage"
    SAILOR = "sailor", "Sailor"
    SCRIBE = "scribe", "Scribe"
    SOLDIER = "soldier", "Soldier"
    WAYFARER = "wayfarer", "Wayfarer"


BACKGROUNDS: dict = {
    Background.ACOLYTE: {
        "skill_proficiencies": {SkillName.INSIGHT, SkillName.RELIGION},
        "tool_proficiency": ToolName.CALLIGRAPHERS_SUPPLIES,
        "origin_feat": FeatName.MAGIC_INITIATE_CLERIC,
        "personality_traits": {
            1: "I idolize a particular hero of my faith, and constantly refer to that person's deeds and example.",
            2: "I can find common ground between the fiercest enemies, empathizing with them and always working toward peace.",
            3: "I see omens in every event and action. The gods try to speak to us, we just need to listen.",
            4: "Nothing can shake my optimistic attitude.",
            5: "I quote (or misquote) sacred texts and proverbs in almost every situation.",
            6: "I am tolerant (or intolerant) of other faiths and respect (or condemn) the worship of other gods.",
            7: "I've enjoyed fine food, drink, and high society among my temple's elite. Rough living grates on me.",
            8: "I've spent so long in the temple that I have little practical experience dealing with people in the outside world.",
        },
        "ideals": {
            1: "Tradition. The ancient traditions of worship and sacrifice must be preserved and upheld. (Lawful)",
            2: "Charity. I always try to help those in need, no matter what the personal cost. (Good)",
            3: "Change. We must help bring about the changes the gods are constantly working in the world. (Chaotic)",
            4: "Power. I hope to one day rise to the top of my faith's religious hierarchy. (Lawful)",
            5: "Faith. I trust that my deity will guide my actions. I have faith that if I work hard, things will go well. (Lawful)",
            6: "Aspiration. I seek to prove myself worthy of my god's favor by matching my actions against his or her teachings. (Any)",
        },
        "bonds": {
            1: "I would die to recover an ancient relic of my faith that was lost long ago.",
            2: "I will someday get revenge on the corrupt temple hierarchy who branded me a heretic.",
            3: "I owe my life to the priest who took me in when my parents died.",
            4: "Everything I do is for the common people.",
            5: "I will do anything to protect the temple where I served.",
            6: "I seek to preserve a sacred text that my enemies consider heretical and seek to destroy.",
        },
        "flaws": {
            1: "I judge others harshly, and myself even more severely.",
            2: "I put too much trust in those who wield power within my temple's hierarchy.",
            3: "My piety sometimes leads me to blindly trust those that profess faith in my god.",
            4: "I am inflexible in my thinking.",
            5: "I am suspicious of strangers and expect the worst of them.",
            6: "Once I pick a goal, I become obsessed with it to the detriment of everything else in my life.",
        },
    },
    Background.ARTISAN: {
        "skill_proficiencies": {SkillName.INSIGHT, SkillName.PERSUASION},
        "tool_proficiency": ToolName.CARPENTERS_TOOLS,
        "origin_feat": FeatName.CRAFTER,
        "personality_traits": {
            1: "I believe that anything worth doing is worth doing right. I can't help it - I'm a perfectionist.",
            2: "I'm a snob who looks down on those who can't appreciate fine craftsmanship.",
            3: "I always want to know how things work and what makes people tick.",
            4: "I'm full of witty aphorisms and have a proverb for every occasion.",
            5: "I'm rude to people who are rude to me.",
            6: "I like to talk at length about my profession.",
            7: "I don't part with my money easily and will haggle tirelessly to get the best deal possible.",
            8: "I'm well known for my work, and I want to make sure everyone appreciates it.",
        },
        "ideals": {
            1: "Community. It is the duty of all civilized people to strengthen the bonds of community and the security of civilization. (Lawful)",
            2: "Generosity. My talents were given to me so that I could use them to benefit the world. (Good)",
            3: "Freedom. Everyone should be free to pursue his or her own livelihood. (Chaotic)",
            4: "Greed. I'm only in it for the money. (Evil)",
            5: "People. I'm committed to the people I care about, not to ideals. (Neutral)",
            6: "Aspiration. I work hard to be the best there is at my craft. (Any)",
        },
        "bonds": {
            1: "The workshop where I learned my trade is the most important place in the world to me.",
            2: "I created a great work for someone, and then found them unworthy to receive it. I'm still looking for someone worthy.",
            3: "I owe my guild a great debt for forging me into the person I am today.",
            4: "I pursue wealth to secure someone's love.",
            5: "One day I will return to my guild and prove that I am the greatest artisan of them all.",
            6: "I will get revenge on the evil forces that destroyed my place of business and ruined my livelihood.",
        },
        "flaws": {
            1: "I'll do anything to get my hands on something rare or priceless.",
            2: "I'm quick to assume that someone is trying to cheat me.",
            3: "No one must ever learn that I once stole from a guild vault.",
            4: "I'm never satisfied with what I have - I always want more.",
            5: "I would kill to acquire a signature piece of work from a great master artisan.",
            6: "I'm horribly jealous of anyone who can outshine my handiwork.",
        },
    },
    Background.CHARLATAN: {
        "skill_proficiencies": {SkillName.DECEPTION, SkillName.SLEIGHT_OF_HAND},
        "tool_proficiency": ToolName.FORGERY_KIT,
        "origin_feat": FeatName.SKILLED,
        "personality_traits": {
            1: "I fall in and out of love easily, and am always pursuing someone.",
            2: "I have a joke for every occasion, especially occasions where humor is inappropriate.",
            3: "Flattery is my preferred trick for getting what I want.",
            4: "I'm a born gambler who can't resist the thrill of a good bet.",
            5: "I lie about almost everything, even when there's no good reason to.",
            6: "Sarcasm and insults are my weapons of choice.",
            7: "I keep multiple holy symbols on me and invoke whatever deity seems most appropriate for my current scheme.",
            8: "I pocket anything I see that might have some value.",
        },
        "ideals": {
            1: "Independence. I am a free spirit - no one tells me what to do. (Chaotic)",
            2: "Fairness. I never target people who can't afford to lose a few coins. (Lawful)",
            3: "Charity. I distribute the money I acquire to the people who really need it. (Good)",
            4: "Creativity. I never run the same con twice. (Chaotic)",
            5: "Friendship. Material goods come and go. Bonds of friendship last forever. (Good)",
            6: "Aspiration. I'm determined to make something of myself. (Any)",
        },
        "bonds": {
            1: "I fleeced the wrong person and must work to ensure that this individual never crosses paths with me or those I care about.",
            2: "I owe everything to my mentor - a horrible person who's probably rotting in jail somewhere.",
            3: "Somewhere out there, I have a child who doesn't know me. I'm making the world better for him or her.",
            4: "I come from a noble family, and one day I'll reclaim my lands and title from those who stole them from me.",
            5: "A powerful person killed someone I love. Some day soon, I'll have my revenge.",
            6: "I swindled and ruined a person who didn't deserve it. I seek to atone for my misdeeds but might never be able to forgive myself.",
        },
        "flaws": {
            1: "I can't resist a pretty face.",
            2: "I'm always in debt. I spend my ill-gotten gains on decadent luxuries faster than I bring them in.",
            3: "I'm convinced that no one could ever fool me the way I fool others.",
            4: "I'm too greedy for my own good. I can't resist taking a risk if there's money involved.",
            5: "I can't resist swindling people who are more powerful than me.",
            6: "I hate to admit it and will reluctantly do so, but I'll run and preserve my own hide if the going gets tough.",
        },
    },
    Background.CRIMINAL: {
        "skill_proficiencies": {SkillName.SLEIGHT_OF_HAND, SkillName.STEALTH},
        "tool_proficiency": ToolName.THIEVES_TOOLS,
        "origin_feat": FeatName.ALERT,
        "personality_traits": {
            1: "I always have a plan for what to do when things go wrong.",
            2: "I am always calm, no matter what the situation. I never raise my voice or let my emotions control me.",
            3: "The first thing I do in a new place is note the locations of everything valuable - or where such things could be hidden.",
            4: "I would rather make a new friend than a new enemy.",
            5: "I am incredibly slow to trust. Those who seem the fairest often have the most to hide.",
            6: "I don't pay attention to the risks in a situation. Never tell me the odds.",
            7: "The best way to get me to do something is to tell me I can't do it.",
            8: "I blow up at the slightest insult.",
        },
        "ideals": {
            1: "Honor. I don't steal from others in the trade. (Lawful)",
            2: "Freedom. Chains are meant to be broken, as are those who would forge them. (Chaotic)",
            3: "Charity. I steal from the wealthy so that I can help people in need. (Good)",
            4: "Greed. I will do whatever it takes to become wealthy. (Evil)",
            5: "People. I'm loyal to my friends, not to any ideals, and everyone else can take a trip down the Styx for all I care. (Neutral)",
            6: "Redemption. There's a spark of good in everyone. (Good)",
        },
        "bonds": {
            1: "I'm trying to pay off an old debt I owe to a generous benefactor.",
            2: "My ill-gotten gains go to support my family.",
            3: "Something important was taken from me, and I aim to steal it back.",
            4: "I will become the greatest thief that ever lived.",
            5: "I'm guilty of a terrible crime. I hope I can redeem myself for it.",
            6: "Someone I loved died because of I mistake I made. That will never happen again.",
        },
        "flaws": {
            1: "When I see something valuable, I can't think about anything but how to steal it.",
            2: "When faced with a choice between money and my friends, I usually choose the money.",
            3: "If there's a plan, I'll forget it. If I don't forget it, I'll ignore it.",
            4: "I have a 'tell' that reveals when I'm lying.",
            5: "I turn tail and run when things look bad.",
            6: "An innocent person is in prison for a crime that I committed. I'm okay with that.",
        },
    },
    Background.ENTERTAINER: {
        "skill_proficiencies": {SkillName.ACROBATICS, SkillName.PERFORMANCE},
        "tool_proficiency": ToolName.LUTE,
        "origin_feat": FeatName.MUSICIAN,
        "personality_traits": {
            1: "I know a story relevant to almost every situation.",
            2: "Whenever I come to a new place, I collect local rumors and spread gossip.",
            3: "I'm a hopeless romantic, always searching for that 'special someone'.",
            4: "Nobody stays angry at me for long, since I can defuse any amount of tension.",
            5: "I love a good insult, even one directed at me.",
            6: "I get bitter if I'm not the center of attention.",
            7: "I'll settle for nothing less than perfection.",
            8: "I change my mood or my mind as quickly as I change key in a song.",
        },
        "ideals": {
            1: "Beauty. When I perform, I make the world better than it was. (Good)",
            2: "Tradition. The stories, legends, and songs of the past must never be forgotten. (Lawful)",
            3: "Creativity. The world is in need of new ideas and bold action. (Chaotic)",
            4: "Greed. I'm only in it for the money and fame. (Evil)",
            5: "People. I like seeing the smiles on people's faces when I perform. That's all that matters. (Neutral)",
            6: "Honesty. Art should reflect the soul; it should come from within and reveal who we really are. (Any)",
        },
        "bonds": {
            1: "My instrument is my most treasured possession, and it reminds me of someone I love.",
            2: "Someone stole my precious instrument, and someday I'll get it back.",
            3: "I want to be famous, whatever it takes.",
            4: "I idolize a hero of the old tales and measure my deeds against that person's.",
            5: "I will do anything to prove myself superior to my hated rival.",
            6: "I would do anything for the other members of my old troupe.",
        },
        "flaws": {
            1: "I'll do anything to win fame and renown.",
            2: "I'm a sucker for a pretty face.",
            3: "A scandal prevents me from ever going home again. That kind of trouble seems to follow me around.",
            4: "I once satirized a noble who still wants my head. It was a mistake that I will likely repeat.",
            5: "I have trouble keeping my true feelings hidden. My sharp tongue lands me in trouble.",
            6: "Despite my best efforts, I am unreliable to my friends.",
        },
    },
    Background.FARMER: {
        "skill_proficiencies": {SkillName.ANIMAL_HANDLING, SkillName.NATURE},
        "tool_proficiency": ToolName.CARPENTERS_TOOLS,
        "origin_feat": FeatName.TOUGH,
        "personality_traits": {
            1: "I judge people by their actions, not their words.",
            2: "If someone is in trouble, I'm always ready to lend help.",
            3: "When I set my mind to something, I follow through no matter what gets in my way.",
            4: "I have a strong sense of fair play and always try to find the most equitable solution to arguments.",
            5: "I'm confident in my own abilities and do what I can to instill that confidence in others.",
            6: "Thinking is for other people. I prefer action.",
            7: "I misuse long words in an attempt to sound smarter.",
            8: "I get bored easily. When am I going to get on with my destiny?",
        },
        "ideals": {
            1: "Respect. People deserve to be treated with dignity. (Good)",
            2: "Fairness. No one should get preferential treatment before the law, and no one is above the law. (Lawful)",
            3: "Freedom. Tyrants must not be allowed to oppress the people. (Chaotic)",
            4: "Might. If I become strong, I can take what I want - what I deserve. (Evil)",
            5: "Sincerity. There's no good in pretending to be something I'm not. (Neutral)",
            6: "Destiny. Nothing and no one can steer me away from my higher calling. (Any)",
        },
        "bonds": {
            1: "I have a family, but I have no idea where they are. One day, I hope to see them again.",
            2: "I worked the land to earn everything I have, and I'll fight to protect it.",
            3: "A proud noble once gave me a horrible beating, and I will take my revenge on any bully I encounter.",
            4: "My tools are symbols of my past life, and I carry them so that I will never forget my roots.",
            5: "I protect those who cannot protect themselves.",
            6: "I wish my childhood sweetheart had come with me to pursue my destiny.",
        },
        "flaws": {
            1: "The tyrant who rules my land will stop at nothing to see me killed.",
            2: "I'm convinced of the significance of my destiny, and blind to my shortcomings and the risk of failure.",
            3: "The people who knew me when I was young know my shameful secret, so I can never go home again.",
            4: "I have a weakness for the vices of the city, especially hard drink.",
            5: "Secretly, I believe that things would be better if I were a tyrant lording over the land.",
            6: "I have trouble trusting in my allies.",
        },
    },
    Background.GUARD: {
        "skill_proficiencies": {SkillName.ATHLETICS, SkillName.PERCEPTION},
        "tool_proficiency": None,  # Gaming set choice - handled in form
        "origin_feat": FeatName.ALERT,
        "personality_traits": {
            1: "I'm always on the lookout for potential threats.",
            2: "I have a strong sense of duty and never abandon my post.",
            3: "I have little respect for those who don't earn their keep.",
            4: "I'm not above bending the rules to get the job done.",
            5: "I treat everyone as a potential suspect until proven otherwise.",
            6: "I follow orders without question when given by a superior.",
            7: "I believe that a well-maintained peace is the highest civic virtue.",
            8: "I've seen enough of the darker side of society that little shocks me.",
        },
        "ideals": {
            1: "Protection. My duty is to keep the innocent safe from harm. (Good)",
            2: "Order. Civilization depends on following rules and maintaining order. (Lawful)",
            3: "Justice. Those who break the law should face consequences. (Lawful)",
            4: "Power. I work to build my own reputation and influence within the guard. (Evil)",
            5: "Pragmatism. I do what needs to be done, regardless of what the law says. (Neutral)",
            6: "Community. I protect the community that I grew up in. (Any)",
        },
        "bonds": {
            1: "I still seek justice for a crime that was never solved.",
            2: "My fellow guards are the most important people in my life.",
            3: "Someone I protected was killed on my watch, and I carry that guilt every day.",
            4: "I'm loyal to the captain who gave me a chance when no one else would.",
            5: "The city I protect is my home, and I'd die to keep it safe.",
            6: "I'm searching for a corrupt guard who betrayed everything the watch stands for.",
        },
        "flaws": {
            1: "I have a tendency to overlook the crimes of those who pay me well.",
            2: "I'm quick to assume the worst of strangers.",
            3: "I follow orders even when I know they're wrong.",
            4: "I can be bribed with the right offer.",
            5: "I've grown callous to suffering through years of exposure to crime.",
            6: "I'm not above planting evidence when I know someone is guilty.",
        },
    },
    Background.GUIDE: {
        "skill_proficiencies": {SkillName.ATHLETICS, SkillName.SURVIVAL},
        "tool_proficiency": ToolName.CARTOGRAPHERS_TOOLS,
        "origin_feat": FeatName.MAGIC_INITIATE_DRUID,
        "personality_traits": {
            1: "I'm driven by a wanderlust that led me away from home.",
            2: "I watch over my friends as if they were a litter of newborn pups.",
            3: "I once ran twenty-five miles without stopping to warn to my clanfolk. I'd do it again if I had to.",
            4: "I have a lesson for every situation, drawn from observing nature.",
            5: "I place no stock in wealthy or well-mannered folk. Money and manners won't save you from a hungry owlbear.",
            6: "I'm always picking things up, absently fiddling with them, and sometimes accidentally breaking them.",
            7: "I feel far more comfortable around animals than people.",
            8: "I was, in fact, raised by wolves.",
        },
        "ideals": {
            1: "Change. Life is like the seasons, in constant change, and we must change with it. (Chaotic)",
            2: "Greater Good. It is each person's responsibility to make the most happiness for the whole tribe. (Good)",
            3: "Honor. If I dishonor myself, I dishonor my whole clan. (Lawful)",
            4: "Might. The strongest are meant to rule. (Evil)",
            5: "Nature. The natural world is more important than all the constructs of civilization. (Neutral)",
            6: "Glory. I must earn glory in battle, for myself and my clan. (Any)",
        },
        "bonds": {
            1: "My family, clan, or tribe is the most important thing in my life, even when they are far from me.",
            2: "An injury to the unspoiled wilderness of my home is an injury to me.",
            3: "I will bring terrible wrath down on the evildoers who destroyed my homeland.",
            4: "I am the last of my tribe, and it is up to me to ensure their names enter legend.",
            5: "I suffer awful visions of a coming disaster and will do anything to prevent it.",
            6: "It is my duty to provide children to sustain my tribe.",
        },
        "flaws": {
            1: "I am too enamored of ale, wine, and other intoxicants.",
            2: "There's no room for caution in a life lived to the fullest.",
            3: "I remember every insult I've received and nurse a silent resentment toward anyone who's ever wronged me.",
            4: "I am slow to trust members of other races, tribes, and societies.",
            5: "Violence is my answer to almost any challenge.",
            6: "Don't expect me to save those who can't save themselves. It is nature's way that the strong thrive and the weak perish.",
        },
    },
    Background.HERMIT: {
        "skill_proficiencies": {SkillName.MEDICINE, SkillName.RELIGION},
        "tool_proficiency": ToolName.HERBALISM_KIT,
        "origin_feat": FeatName.MAGIC_INITIATE_CLERIC,
        "personality_traits": {
            1: "I've been isolated for so long that I rarely speak, preferring gestures and the occasional grunt.",
            2: "I am utterly serene, even in the face of disaster.",
            3: "The leader of my community had something wise to say on every topic, and I am eager to share that wisdom.",
            4: "I feel tremendous empathy for all who suffer.",
            5: "I'm oblivious to etiquette and social expectations.",
            6: "I connect everything that happens to me to a grand, cosmic plan.",
            7: "I often get lost in my own thoughts and contemplation, becoming oblivious to my surroundings.",
            8: "I am working on a grand philosophical theory and love sharing my ideas.",
        },
        "ideals": {
            1: "Greater Good. My gifts are meant to be shared with all, not used for my own benefit. (Good)",
            2: "Logic. Emotions must not cloud our logical thinking. (Lawful)",
            3: "Free Thinking. Inquiry and curiosity are the pillars of progress. (Chaotic)",
            4: "Power. Solitude and contemplation are paths toward mystical or magical power. (Evil)",
            5: "Live and Let Live. Meddling in the affairs of others only causes trouble. (Neutral)",
            6: "Self-Knowledge. If you know yourself, there's nothing left to know. (Any)",
        },
        "bonds": {
            1: "Nothing is more important than the other members of my hermitage, order, or association.",
            2: "I entered seclusion to hide from the ones who might still be hunting me. I must someday confront them.",
            3: "I'm still seeking the enlightenment I pursued in my seclusion, and it still eludes me.",
            4: "I entered seclusion because I loved someone I could not have.",
            5: "Should my discovery come to light, it could bring ruin to the world.",
            6: "My isolation gave me great insight into a great evil that only I can destroy.",
        },
        "flaws": {
            1: "Now that I've returned to the world, I enjoy its delights a little too much.",
            2: "I harbor dark, bloodthirsty thoughts that my isolation and meditation failed to quell.",
            3: "I am dogmatic in my thoughts and philosophy.",
            4: "I let my need for isolation and contemplation interfere with meeting the needs of those who depend on me.",
            5: "I'd risk too much to uncover a lost bit of knowledge.",
            6: "I like keeping secrets and won't share them with anyone.",
        },
    },
    Background.MERCHANT: {
        "skill_proficiencies": {SkillName.ANIMAL_HANDLING, SkillName.PERSUASION},
        "tool_proficiency": ToolName.NAVIGATORS_TOOLS,
        "origin_feat": FeatName.LUCKY,
        "personality_traits": {
            1: "I believe that anything can be bought or sold.",
            2: "I always have a plan for when things go wrong.",
            3: "I'm always looking for the next opportunity to turn a profit.",
            4: "I keep meticulous records of every transaction I make.",
            5: "I never reveal what I really know or think.",
            6: "I'm always calculating the value of everything I see.",
            7: "I'm quick to make friends and even quicker to exploit them.",
            8: "I live by the motto: a fair deal is a good deal.",
        },
        "ideals": {
            1: "Fairness. I deal honestly and expect others to do the same. (Lawful)",
            2: "Greed. Profit is the only true measure of success. (Evil)",
            3: "Generosity. The mark of a good merchant is one who gives back to the community. (Good)",
            4: "Freedom. The free market is the foundation of a free society. (Chaotic)",
            5: "People. My customers are my most valuable asset. (Neutral)",
            6: "Aspiration. I want to build the most successful trading empire ever seen. (Any)",
        },
        "bonds": {
            1: "I owe a great debt to a merchant who gave me my start.",
            2: "My trading house is my family, and I will protect it at all costs.",
            3: "Someone cheated me out of my life's work, and I'll have revenge.",
            4: "I'm searching for a rare item that my best customer has requested.",
            5: "My wealth is a means to an end - funding a worthy cause.",
            6: "I keep careful records of every deal I've made, lest I forget a debt owed or a favor promised.",
        },
        "flaws": {
            1: "I'll do anything legal - and a few things that aren't - to make a profit.",
            2: "I can't resist a bargain, even when I know it's too good to be true.",
            3: "I put too much faith in the power of money to solve any problem.",
            4: "I'm suspicious of people who give things away freely - what are they really after?",
            5: "I've cut corners before and gotten away with it. One day that luck will run out.",
            6: "I have a weakness for luxury goods and spend more than I should.",
        },
    },
    Background.NOBLE: {
        "skill_proficiencies": {SkillName.HISTORY, SkillName.PERSUASION},
        "tool_proficiency": None,  # Gaming set choice - handled in form
        "origin_feat": FeatName.SKILLED,
        "personality_traits": {
            1: "My eloquent flattery makes everyone I talk to feel like the most wonderful and important person in the world.",
            2: "The common folk love me for my kindness and generosity.",
            3: "No one could doubt by looking at my regal bearing that I am a cut above the unwashed masses.",
            4: "I take great pains to always look my best and follow the latest fashions.",
            5: "I don't like to get my hands dirty, and I won't be caught dead in unsuitable accommodations.",
            6: "Despite my noble birth, I do not place myself above other folk. We all have the same blood.",
            7: "My favor, once lost, is lost forever.",
            8: "If you do me an injury, I will crush you, ruin your name, and salt your fields.",
        },
        "ideals": {
            1: "Respect. Respect is due to me because of my position, but all people regardless of station deserve to be treated with dignity. (Good)",
            2: "Responsibility. It is my duty to respect the authority of those above me, just as those below me must respect mine. (Lawful)",
            3: "Independence. I must prove that I can handle myself without the coddling of my family. (Chaotic)",
            4: "Power. If I can attain more power, no one will tell me what to do. (Evil)",
            5: "Family. Blood runs thicker than water. (Any)",
            6: "Noble Obligation. It is my duty to protect and care for the people beneath me. (Good)",
        },
        "bonds": {
            1: "I will face any challenge to win the approval of my family.",
            2: "My house's alliance with another noble family must be sustained at all costs.",
            3: "Nothing is more important than the other members of my family.",
            4: "I am in love with the heir of a family that my family despises.",
            5: "My loyalty to my sovereign is unwavering.",
            6: "The common folk must see me as a hero of the people.",
        },
        "flaws": {
            1: "I secretly believe that everyone is beneath me.",
            2: "I hide a truly scandalous secret that could ruin my family forever.",
            3: "I too often hear veiled insults and threats in every word addressed to me.",
            4: "I have an insatiable desire for carnal pleasures.",
            5: "In fact, the world does revolve around me.",
            6: "By my words and actions, I often bring shame to my family.",
        },
    },
    Background.PILGRIM: {
        "skill_proficiencies": {SkillName.INSIGHT, SkillName.RELIGION},
        "tool_proficiency": ToolName.HERBALISM_KIT,
        "origin_feat": FeatName.HEALER,
        "personality_traits": {
            1: "I see the divine in all living things.",
            2: "I'm always calm, even when I should be alarmed.",
            3: "I quote sacred scripture in almost every situation.",
            4: "I've walked a thousand miles and have a story about every one of them.",
            5: "I believe that fate will provide - I never worry about tomorrow.",
            6: "I give generously to those I meet on the road.",
            7: "My faith sustains me through any hardship.",
            8: "I am always looking for signs and omens in the world around me.",
        },
        "ideals": {
            1: "Faith. I trust in the divine plan, even when I cannot see it. (Lawful)",
            2: "Charity. The gods call us to care for the weak and the suffering. (Good)",
            3: "Devotion. My pilgrimage is an act of love for my deity. (Lawful)",
            4: "Freedom. The road itself is a form of liberation. (Chaotic)",
            5: "Peace. I seek to bring harmony wherever I travel. (Neutral)",
            6: "Enlightenment. Every step of my journey brings me closer to truth. (Any)",
        },
        "bonds": {
            1: "I walk in honor of a loved one who could not make this journey.",
            2: "The shrine I seek is sacred above all other things to me.",
            3: "My traveling companions are my new family.",
            4: "I carry a holy relic that I must deliver to a distant temple.",
            5: "I seek forgiveness for a great sin, and this pilgrimage is my penance.",
            6: "I spread the teachings of my faith to every soul I meet.",
        },
        "flaws": {
            1: "I am too quick to judge those of different faiths.",
            2: "I expect others to share my level of devotion, and I'm disappointed when they don't.",
            3: "I can be dangerously naive about the intentions of strangers.",
            4: "My faith can make me inflexible in the face of pragmatic solutions.",
            5: "I sometimes speak too openly of my beliefs, causing offense.",
            6: "I have trouble putting my faith aside and acting on cold logic.",
        },
    },
    Background.SAGE: {
        "skill_proficiencies": {SkillName.ARCANA, SkillName.HISTORY},
        "tool_proficiency": ToolName.CALLIGRAPHERS_SUPPLIES,
        "origin_feat": FeatName.MAGIC_INITIATE_WIZARD,
        "personality_traits": {
            1: "I use polysyllabic words that convey the impression of great erudition.",
            2: "I've read every book in the world's greatest libraries - or I like to boast that I have.",
            3: "I'm used to helping out those who aren't as smart as I am, and I patiently explain anything and everything to others.",
            4: "There's nothing I like more than a good mystery.",
            5: "I'm willing to listen to every side of an argument before I make my own judgment.",
            6: "I . . . speak . . . slowly . . . when talking . . . to idiots, . . . which . . . almost . . . everyone . . . is . . . compared . . . to me.",
            7: "I am horribly, horribly awkward in social situations.",
            8: "I'm convinced that people are always trying to steal my secrets.",
        },
        "ideals": {
            1: "Knowledge. The path to power and self-improvement is through knowledge. (Neutral)",
            2: "Beauty. What is beautiful points us beyond itself toward what is true. (Good)",
            3: "Logic. Emotions must not cloud our logical thinking. (Lawful)",
            4: "No Limits. Nothing should fetter the infinite possibility inherent in all existence. (Chaotic)",
            5: "Power. Knowledge is the path to power and domination. (Evil)",
            6: "Self-Improvement. The goal of a life of study is the betterment of oneself. (Any)",
        },
        "bonds": {
            1: "It is my duty to protect my students.",
            2: "I have an ancient text that holds terrible secrets that must not fall into the wrong hands.",
            3: "I work to preserve a library, university, scriptorium, or monastery.",
            4: "My life's work is a series of tomes related to a specific field of lore.",
            5: "I've been searching my whole life for the answer to a certain question.",
            6: "I sold my soul for knowledge. I hope to do great deeds and win it back.",
        },
        "flaws": {
            1: "I am easily distracted by the promise of information.",
            2: "Most people scream and run when they see a demon. I stop and take notes on its anatomy.",
            3: "Unlocking an ancient mystery is worth the price of a civilization.",
            4: "I overlook obvious solutions in favor of complicated ones.",
            5: "I speak without really thinking through my words, invariably insulting others.",
            6: "I can't keep a secret to save my life, or anyone else's.",
        },
    },
    Background.SAILOR: {
        "skill_proficiencies": {SkillName.ACROBATICS, SkillName.PERCEPTION},
        "tool_proficiency": ToolName.NAVIGATORS_TOOLS,
        "origin_feat": FeatName.TAVERN_BRAWLER,
        "personality_traits": {
            1: "My friends know they can rely on me, no matter what.",
            2: "I work hard so that I can play hard when the work is done.",
            3: "I enjoy sailing into new ports and making new friends over a flagon of ale.",
            4: "I stretch the truth for the sake of a good story.",
            5: "To me, a tavern brawl is a nice way to get to know a new city.",
            6: "I never pass up a friendly wager.",
            7: "My language is as foul as an otyugh nest.",
            8: "I like a job well done, especially if I can convince someone else to do it.",
        },
        "ideals": {
            1: "Respect. The thing that keeps a ship together is mutual respect between captain and crew. (Good)",
            2: "Fairness. We all do the work, so we all share in the rewards. (Lawful)",
            3: "Freedom. The sea is freedom - the freedom to go anywhere and do anything. (Chaotic)",
            4: "Mastery. I'm a predator, and the other ships on the sea are my prey. (Evil)",
            5: "People. I'm committed to my crewmates, not to ideals. (Neutral)",
            6: "Aspiration. Someday I'll own my own ship and chart my own destiny. (Any)",
        },
        "bonds": {
            1: "I'm loyal to my captain first, everything else second.",
            2: "The ship is most important - crewmates and captains come and go.",
            3: "I'll always remember my first ship, the Moonsea Privateer.",
            4: "In a harbor town, I have a paramour whose eyes nearly stole me from the sea.",
            5: "I was cheated out of my fair share of the profits, and I want to get my due.",
            6: "Ruthless pirates murdered my captain and crewmates, plundered our ship, and left me to die. Vengeance will be mine.",
        },
        "flaws": {
            1: "I follow orders, even if I think they're wrong.",
            2: "I'll say anything to avoid having to do extra work.",
            3: "Once someone questions my courage, I never back down no matter how dangerous the situation.",
            4: "Once I start drinking, it's hard for me to stop.",
            5: "I can't help but pocket loose coins and other trinkets I come across.",
            6: "My pride will probably lead to my destruction.",
        },
    },
    Background.SCRIBE: {
        "skill_proficiencies": {SkillName.INVESTIGATION, SkillName.PERCEPTION},
        "tool_proficiency": ToolName.CALLIGRAPHERS_SUPPLIES,
        "origin_feat": FeatName.SKILLED,
        "personality_traits": {
            1: "I'm used to helping out those who aren't as educated as I am, and I patiently explain anything and everything to others.",
            2: "I've read every document of significance in the city's archives - or I like to boast that I have.",
            3: "I prefer to record events exactly as they happened, without embellishment.",
            4: "I'm always on the lookout for new and interesting texts to add to my collection.",
            5: "I believe that knowledge, once written down, is never truly lost.",
            6: "I have little patience for those who don't appreciate the importance of careful documentation.",
            7: "I'm always taking notes, even when it's not appropriate.",
            8: "I'm convinced that there's a hidden pattern in every document, waiting to be discovered.",
        },
        "ideals": {
            1: "Knowledge. The written word preserves truth for all time. (Neutral)",
            2: "Honesty. A false record is worse than no record at all. (Lawful)",
            3: "Access. Knowledge should be available to all, not just the privileged. (Chaotic)",
            4: "Power. He who controls information controls the world. (Evil)",
            5: "Preservation. I safeguard history so that future generations can learn from it. (Good)",
            6: "Perfectionism. Every document I produce should be flawless. (Any)",
        },
        "bonds": {
            1: "I protect a collection of ancient texts that must not fall into the wrong hands.",
            2: "I'm searching for a lost document that could change everything.",
            3: "I owe a great debt to the master who taught me to read and write.",
            4: "My greatest work is a comprehensive history that I've spent years compiling.",
            5: "I copy forbidden texts because someone has to preserve dangerous knowledge.",
            6: "I work to expose a conspiracy that has been concealed within official records.",
        },
        "flaws": {
            1: "I'm obsessed with documentation and refuse to act without a written record.",
            2: "I've forged documents before and justified it as preserving a greater truth.",
            3: "I have a habit of reading others' correspondence when they're not looking.",
            4: "I'm a perfectionist who would rather miss a deadline than produce imperfect work.",
            5: "I hoard information and am reluctant to share what I know.",
            6: "I'm easily distracted by an interesting text, even in the middle of a crisis.",
        },
    },
    Background.SOLDIER: {
        "skill_proficiencies": {SkillName.ATHLETICS, SkillName.INTIMIDATION},
        "tool_proficiency": None,  # Gaming set choice - handled in form
        "origin_feat": FeatName.SAVAGE_ATTACKER,
        "personality_traits": {
            1: "I'm always polite and respectful.",
            2: "I'm haunted by memories of war. I can't get the images of violence out of my mind.",
            3: "I've lost too many friends, and I'm slow to make new ones.",
            4: "I'm full of inspiring and cautionary tales from my military experience relevant to almost every combat situation.",
            5: "I can stare down a hell hound without flinching.",
            6: "I enjoy being strong and like breaking things.",
            7: "I have a crude sense of humor.",
            8: "I face problems head-on. A simple, direct solution is the best path to success.",
        },
        "ideals": {
            1: "Greater Good. Our lot is to lay down our lives in defense of others. (Good)",
            2: "Responsibility. I do what I must and obey just authority. (Lawful)",
            3: "Independence. When people follow orders blindly, they embrace a kind of tyranny. (Chaotic)",
            4: "Might. In life as in war, the stronger force wins. (Evil)",
            5: "Live and Let Live. Ideals aren't worth killing over or going to war for. (Neutral)",
            6: "Nation. My city, nation, or people are all that matter. (Any)",
        },
        "bonds": {
            1: "I would still lay down my life for the people I served with.",
            2: "Someone saved my life on the battlefield. To this day, I will never leave a friend behind.",
            3: "My honor is my life.",
            4: "I'll never forget the crushing defeat my company suffered or the enemies who dealt it.",
            5: "Those who fight beside me are those worth dying for.",
            6: "I fight for those who cannot fight for themselves.",
        },
        "flaws": {
            1: "The monstrous enemy we faced in battle still leaves me quivering with fear.",
            2: "I have little respect for anyone who is not a proven warrior.",
            3: "I made a terrible mistake in battle that cost many lives - and I would do anything to keep that mistake secret.",
            4: "My hatred of my enemies is blind and unreasoning.",
            5: "I obey the law, even if the law causes misery.",
            6: "I'd rather eat my armor than admit when I'm wrong.",
        },
    },
    Background.WAYFARER: {
        "skill_proficiencies": {SkillName.INSIGHT, SkillName.STEALTH},
        "tool_proficiency": ToolName.THIEVES_TOOLS,
        "origin_feat": FeatName.LUCKY,
        "personality_traits": {
            1: "I'm always moving, and I get restless if I stay in one place too long.",
            2: "I know the roads and shortcuts that others don't.",
            3: "I've learned to take nothing for granted - everything can be lost in an instant.",
            4: "I have a talent for blending into my surroundings.",
            5: "I trust my instincts more than maps or the advice of others.",
            6: "I'm quick to pick up local customs and use them to my advantage.",
            7: "I've survived by my wits, and I have little patience for those who haven't.",
            8: "I'm always watching the exits.",
        },
        "ideals": {
            1: "Freedom. No walls, no masters, no roots. (Chaotic)",
            2: "Survival. I do what I must to live another day. (Neutral)",
            3: "Solidarity. Wanderers must look out for one another. (Good)",
            4: "Opportunity. Every new place is a new chance to take what I need. (Evil)",
            5: "Self-Reliance. I depend on no one but myself. (Neutral)",
            6: "Wanderlust. The journey itself is the destination. (Any)",
        },
        "bonds": {
            1: "I'm searching for a family member who disappeared on the road years ago.",
            2: "I carry a keepsake from the home I can never return to.",
            3: "A fellow wanderer saved my life, and I owe them an unpayable debt.",
            4: "I'm running from something, and I can't afford to stop moving.",
            5: "I protect other travelers from the dangers of the road.",
            6: "There's a community of wanderers I consider my true family.",
        },
        "flaws": {
            1: "I'm suspicious of anyone who stays in one place too long.",
            2: "I take what I need without always asking first.",
            3: "I'm slow to trust people who haven't earned it through hardship.",
            4: "I leave before things get complicated - relationships, debts, obligations.",
            5: "I've stolen from good people and told myself they could afford it.",
            6: "I have a terrible sense of direction despite all my years on the road.",
        },
    },
}
