from django.db.models import TextChoices


class FeatType(TextChoices):
    ORIGIN = "O", "Origin"
    GENERAL = "G", "General"


class FeatName(TextChoices):
    ABILITY_SCORE_IMPROVEMENT = "ability_score_improvement", "Ability Score Improvement"
    ACTOR = "actor", "Actor"
    ALERT = "alert", "Alert"
    ATHLETE = "athlete", "Athlete"
    CHARGER = "charger", "Charger"
    CHEF = "chef", "Chef"
    CRAFTER = "crafter", "Crafter"
    CROSSBOW_EXPERT = "crossbow_expert", "Crossbow Expert"
    CRUSHER = "crusher", "Crusher"
    DEFENSIVE_DUELIST = "defensive_duelist", "Defensive Duelist"
    DUAL_WIELDER = "dual_wielder", "Dual Wielder"
    DURABLE = "durable", "Durable"
    ELEMENTAL_ADEPT = "elemental_adept", "Elemental Adept"
    FEY_TOUCHED = "fey_touched", "Fey-Touched"
    GRAPPLER = "grappler", "Grappler"
    GREAT_WEAPON_MASTER = "great_weapon_master", "Great Weapon Master"
    HEALER = "healer", "Healer"
    HEAVY_ARMOR_MASTER = "heavy_armor_master", "Heavy Armor Master"
    INSPIRING_LEADER = "inspiring_leader", "Inspiring Leader"
    LUCKY = "lucky", "Lucky"
    MAGE_SLAYER = "mage_slayer", "Mage Slayer"
    MAGIC_INITIATE_BARD = "magic_initiate_bard", "Magic Initiate (Bard)"
    MAGIC_INITIATE_CLERIC = "magic_initiate_cleric", "Magic Initiate (Cleric)"
    MAGIC_INITIATE_DRUID = "magic_initiate_druid", "Magic Initiate (Druid)"
    MAGIC_INITIATE_SORCERER = "magic_initiate_sorcerer", "Magic Initiate (Sorcerer)"
    MAGIC_INITIATE_WARLOCK = "magic_initiate_warlock", "Magic Initiate (Warlock)"
    MAGIC_INITIATE_WIZARD = "magic_initiate_wizard", "Magic Initiate (Wizard)"
    MOUNTED_COMBATANT = "mounted_combatant", "Mounted Combatant"
    MUSICIAN = "musician", "Musician"
    OBSERVANT = "observant", "Observant"
    POLEARM_MASTER = "polearm_master", "Polearm Master"
    RESILIENT = "resilient", "Resilient"
    SAVAGE_ATTACKER = "savage_attacker", "Savage Attacker"
    SENTINEL = "sentinel", "Sentinel"
    SHADOW_TOUCHED = "shadow_touched", "Shadow-Touched"
    SHARPSHOOTER = "sharpshooter", "Sharpshooter"
    SHIELD_MASTER = "shield_master", "Shield Master"
    SKILLED = "skilled", "Skilled"
    SKULKER = "skulker", "Skulker"
    SLASHER = "slasher", "Slasher"
    SPELL_SNIPER = "spell_sniper", "Spell Sniper"
    TAVERN_BRAWLER = "tavern_brawler", "Tavern Brawler"
    TOUGH = "tough", "Tough"
    WAR_CASTER = "war_caster", "War Caster"
    WEAPON_MASTER = "weapon_master", "Weapon Master"
