# Generated by Django 6.0.2 on 2026-02-24 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("synopsis", models.TextField(blank=True, max_length=3000)),
                ("main_conflict", models.TextField(blank=True, max_length=1000)),
                ("objective", models.TextField(blank=True, max_length=500)),
                ("party_level", models.SmallIntegerField(default=1)),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("heroic", "Heroic"),
                            ("dark", "Dark"),
                            ("comedic", "Comedic"),
                            ("mystery", "Mystery"),
                            ("horror", "Horror"),
                        ],
                        default="heroic",
                        max_length=10,
                    ),
                ),
                ("setting", models.TextField(blank=True, max_length=1000)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
