# Generated by Django 6.0.2 on 2026-02-24 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adventure", "0001_initial"),
        ("bestiary", "0007_drop_remaining_json_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Act",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("order", models.PositiveSmallIntegerField(default=1)),
                ("summary", models.TextField(blank=True, max_length=2000)),
                ("goal", models.TextField(blank=True, max_length=500)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acts",
                        to="adventure.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, max_length=2000)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("dungeon", "Dungeon"),
                            ("city", "City"),
                            ("wilderness", "Wilderness"),
                            ("sea", "Sea"),
                            ("planar", "Planar"),
                            ("underdark", "Underdark"),
                        ],
                        default="dungeon",
                        max_length=10,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="adventure.campaign",
                    ),
                ),
                (
                    "connections",
                    models.ManyToManyField(blank=True, to="adventure.location"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NPC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(blank=True, max_length=20)),
                ("motivation", models.TextField(blank=True, max_length=500)),
                ("personality", models.TextField(blank=True, max_length=500)),
                ("appearance", models.TextField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True, max_length=1000)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="npcs",
                        to="adventure.campaign",
                    ),
                ),
                (
                    "stat_block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="npcs",
                        to="bestiary.monstersettings",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("order", models.PositiveSmallIntegerField(default=1)),
                (
                    "scene_type",
                    models.CharField(
                        choices=[
                            ("C", "Combat"),
                            ("S", "Social Interaction"),
                            ("E", "Exploration"),
                            ("R", "Rest"),
                            ("T", "Transition"),
                        ],
                        default="E",
                        max_length=1,
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=3000)),
                ("hook", models.TextField(blank=True, max_length=500)),
                ("resolution", models.TextField(blank=True, max_length=500)),
                (
                    "act",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenes",
                        to="adventure.act",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
