# Generated by Django 6.0.2 on 2026-02-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adventure", "0002_act_location_npc_scene"),
    ]

    operations = [
        migrations.AlterField(
            model_name="npc",
            name="role",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="act",
            unique_together={("campaign", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="scene",
            unique_together={("act", "order")},
        ),
    ]
