# Generated by Django 6.0.2 on 2026-02-24 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adventure", "0003_alter_npc_role_alter_act_unique_together_and_more"),
        ("bestiary", "0007_drop_remaining_json_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "encounter_type",
                    models.CharField(
                        choices=[
                            ("C", "Combat"),
                            ("S", "Social"),
                            ("T", "Trap"),
                            ("P", "Puzzle"),
                            ("E", "Exploration"),
                        ],
                        default="C",
                        max_length=1,
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=2000)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("E", "Easy"),
                            ("M", "Medium"),
                            ("H", "Hard"),
                            ("D", "Deadly"),
                        ],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("rewards", models.TextField(blank=True, max_length=500)),
                (
                    "npcs",
                    models.ManyToManyField(
                        blank=True, related_name="encounters", to="adventure.npc"
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters",
                        to="adventure.scene",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EncounterMonster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveSmallIntegerField(default=1)),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounter_monsters",
                        to="adventure.encounter",
                    ),
                ),
                (
                    "monster_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounter_monsters",
                        to="bestiary.monstersettings",
                    ),
                ),
            ],
            options={
                "unique_together": {("encounter", "monster_settings")},
            },
        ),
        migrations.AddField(
            model_name="encounter",
            name="monsters",
            field=models.ManyToManyField(
                blank=True,
                related_name="encounters",
                through="adventure.EncounterMonster",
                to="bestiary.monstersettings",
            ),
        ),
    ]
