# Generated by Django 6.0.2 on 2026-02-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adventure", "0004_encounter_encountermonster_encounter_monsters"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="encounter",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="encounter",
            name="order",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name="encounter",
            unique_together={("scene", "order")},
        ),
    ]
